<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
  </head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/rwclaim/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">請求書発行待ちリスト(初回)</h3>

    <table style="clear:both;" width="862" class="datatable" cellpadding="0" cellspacing="0" border="1"><tr>
    <!-- ページナビゲーション -->
    <?php echo $this->render('cbadmin/page_navigation.php'); ?></tr>
    </table>

    <h4>

    <form name="sform" method="post" action="rwclaim/list">
      <font color="red">検索条件を変更した場合は、必ず[検索]ボタンを押してください</font>
      </p>
      請求書<?php echo $this->billIssueStateTag; ?>
      用紙　<?php echo $this->paperTypeTag; ?>
      売上確定日<input style="text-align: left;" type="text" size="10" name="salesDicisionDate" id="salesDicisionDate" value="<?php echo f_e($this->salesDicisionDate); ?>" />以前(YYYY-MM-DD形式で入力)
      <input style="margin-left: 50px;" id="search" type="submit" value="　検　索　" />

      </p>
      OEM<?php echo $this->oemTag; ?>
      </p>
      加盟店ID(後方一致)<input style="text-align: left;" type="text" size="10" name="entid" id="endid" value="<?php echo f_e($this->entid); ?>" />
      加盟店名(部分一致)<input style="text-align: left;" type="text" size="20" name="entnm" id="endnm" value="<?php echo f_e($this->entnm); ?>" />
      注文ID(後方一致)<input style="text-align: left;" type="text" size="10" name="odrid" id="odrid" value="<?php echo f_e($this->odrid); ?>" />
    </form>
    </h4>

    <h4><span class="cnt"><?php echo $this->cnt; ?></span>　件の伝票番号登録が完了しています。</h4>
    <?php if ($this->combinedCnlFlg) { ?>
    <h4><font color="red">キャンセル承認されていない取りまとめデータが存在します。<br />請求書印刷前にキャンセル確認をしてください。</font></h4>
    <?php } ?>
    <form id="form" name="form" method="post" action="rwclaim/up">
      <table style="clear:both;" width="862" cellpadding="1" cellspacing="1" border="0">
        <tr>
          <td align="right">
            <input type="button" onclick="allChecked(true, this.form,'chkPrint'       );" value="　印刷全選択　" />
            <input type="button" onclick="allChecked(true, this.form,'chkWaitDecision');" value="　確定全選択　" /></p>
            <input type="button" onclick="allChecked(false,this.form,'chkPrint'       );" value="　印刷全解除　" />
            <input type="button" onclick="allChecked(false,this.form,'chkWaitDecision');" value="　確定全解除　" />
            </p>
          </td>
        </tr>
      </table>
	  <table style="clear:both;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
	      <tr>
          	<th>状態</th>
            <th>注文<br />SEQ</th>
          	<th>注文ID</th>
          	<th>注文登録日時</th>
          	<th>属性</th>
          	<th>事業者名</th>
          	<th>請求先氏名</th>
          	<th>住所</th>
          	<th>利用額</th>
          	<th>印刷書式</th>
          	<th>印刷</th>
          	<th>確定<br />待ち</th>
          </tr>
          <?php
          // count関数対策
			$listCount = 0;
			if (!empty($this->list)) {
			$listCount = count($this->list);
            }
            for ($i = 0 ; $i < $listCount ; $i++) { ?>
          <tr>
            <td class="l_data"><?php echo $this->list[$i]["ConfirmWaitingStr"]; ?></td>
            <td class="r_data"><?php echo $this->list[$i]["OrderSeq"]; ?>
              <input type="hidden" name="OrderSeq<?php echo $i; ?>" value="<?php echo $this->list[$i]["OrderSeq"]; ?>"/>
              <input type="hidden" name="Eid<?php echo $i; ?>" value="<?php echo $this->list[$i]["EnterpriseId"]; ?>"/>
              <input type="hidden" name="UseAmount<?php echo $i; ?>" value="<?php echo $this->list[$i]["UseAmount"]; ?>"/>
              <input type="hidden" name="SiteId<?php echo $i; ?>" value="<?php echo $this->list[$i]["SiteId"]; ?>"/>
              <input type="hidden" name="OemId<?php echo $i; ?>" value="<?php echo $this->list[$i]["OemId"]; ?>"/>
            </td>
            <td class="l_data">
              <a target="_blank" href="rworder/detail/oseq/<?php echo $this->list[$i]["OrderSeq"]; ?>"><?php echo $this->list[$i]["OrderId"]; ?></a>
            </td>
            <td class="c_data"><?php echo $this->list[$i]["RegistDate"]; ?></td>
            <td class="c_data"><?php echo $this->list[$i]["IncreArCaption"]; ?></td>
            <td class="l_data"><?php echo $this->list[$i]["EnterpriseNameKj"]; ?></td>
            <td class="l_data">
              <a target="_blank" href="customerinquiry/detail/custid/<?php echo $this->list[$i]["CustomerId"]; ?>"><?php echo $this->list[$i]["NameKj"]; ?></a>
            </td>
            <td class="l_data" ><?php echo $this->list[$i]["UnitingAddress"]; ?>...</td>
            <td class="r_data"><?php echo f_nf($this->list[$i]["UseAmount"], '#,##0'); ?></td>
            <td class="l_data"><?php echo $this->list[$i]["PrintFormat"]; ?></td>
            <td class="c_data"><input type="checkbox" name="chkPrint<?php echo $i; ?>" id="chkPrint<?php echo $i; ?>" /></td>
            <td class="c_data"><input type="checkbox" name="chkWaitDecision<?php echo $i; ?>" id="chkWaitDecision<?php echo $i; ?>" <?php if( !$this->list[$i]['ConfirmWaitingFlg']) { echo 'disabled="disabled" '; } ?> /></td>
          </tr>
          <?php } ?>
        </tbody>
      </table>
      <table style="clear:both;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
            <td class="l_data">
                <span style="float:left">  <button id="submit-button" type="button">　　印刷済に更新　　</button></span>
                <span style="float:right">
                    <input type="hidden" name="searchKey" id="searchKey" value="<?php echo f_e($this->searchKey); ?>" />
                    <button id="submit2" type="button">　　CSV出力　　</button>
                    <!-- button id="submit3" type="button">　　　　印刷　　　　</button -->
                </span>
            </td>
          </tr>
        </tbody>
      </table>
    </form>

  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
<script src="../member/js/cover.js"></script>
<script type="text/javascript">
Event.observe( window, "load", function() {
    window.WindowCover = createCover();
    document.body.appendChild( window.WindowCover );

} );
</script>

<script type="text/javascript">
//チェックボックス全件選択
function allChecked(check, targetForm, colnm){
    for (var j=0, k=targetForm.length; j<k; j++){
        var str = targetForm.elements[j].name;
        if (str.indexOf(colnm) == 0){
            // オブジェクトがイネーブル時に限り処理を行う
            if (!targetForm.elements[j].disabled) {
                targetForm.elements[j].checked = check;
            }
        }
    }
}

Event.observe(window, 'load', function() {
    Event.observe($('submit-button'), 'click', function() {
        $('submit-button').disabled = true;
        setTimeout(function() {
            $('form').submit();
        }, 0);
    });
});

Event.observe($("submit2"), "click", function() {

	WindowCover.show();

	// AJAX通信でフォーム情報をセッションに設定
    var str = Form.serialize('form');   // フォーム内容をシリアライズ
    var url = "<?php echo $this->baseUrl; ?>/rwclaim/jobparamsetcsv";
    var ajax = new Ajax.Request( url, {method: 'post', parameters: str, onComplete: submit2OnComplete, asynchronous: true });

});

function submit2OnComplete(httpObj){

	var res = eval('(' + httpObj.responseText + ')');
    if  (res['status'] == 2) {

    	var msg = "以下の注文の請求データ作成に失敗しました。\n";
    	msg += "エラー内容を確認し、注文情報を修正してください。\n\n";
    	msg += "\n";
    	msg += res['message']
    	msg += "\n\n";
    	msg += "ファイルのダウンロードは、[OK]ボタンをクリックした後に行われます。\n";
    	msg += "(エラーが発生した上記注文は含まれません)\n";

    	alert(msg);
    }

    if  (res['status'] == 9) {
    	var msg = "エラーが発生しました。エラーが頻発する場合は、システム管理者へご連絡ください。\n";
    	msg += res['message'];
    	alert(msg);
    	location.reload(true);
        return;
    }

    // CSV出力処理
    var url = "<?php echo $this->baseUrl; ?>/rwclaim/csvoutput";
    var ref = window.open( url );


    // CSV出力が終わったら随時リロードする
    // 最大10秒待機させる
    var wait = 0;
    var intvl = setInterval(function() {
    	wait++;
        if (ref.closed == true || wait == 50){
            clearInterval(intvl);
            location.reload(true);
        }
    }, 200);
}


//Event.observe($("submit3"), "click", function() {
//
//    // OEMID混在のチェック
//    var str = Form.serialize('form');   // フォーム内容をシリアライズ
//    var url = "<?php echo $this->baseUrl; ?>/rwclaim/ismixoemid";
//    var ajax = new Ajax.Request( url, {method: 'post', parameters: str, asynchronous: false });
//	var res = eval('(' + ajax.transport.responseText + ')');
//	if  (res['status'] != 1) {
//		alert(res['status']);
//		return;
//	}
//
//	WindowCover.show();
//
//	// AJAX通信でフォーム情報をセッションに設定
//    var str = Form.serialize('form');   // フォーム内容をシリアライズ
//    var url = "<?php echo $this->baseUrl; ?>/rwclaim/jobparamset";
//    var ajax = new Ajax.Request( url, {method: 'post', parameters: str, onComplete: submit3OnComplete, asynchronous: true });
//
//});

function submit3OnComplete(httpObj){

	var res = eval('(' + httpObj.responseText + ')');
    if  (res['status'] == 2) {

    	var msg = "以下の注文の請求データ作成に失敗しました。\n";
    	msg += "エラー内容を確認し、注文情報を修正してください。\n\n";
    	msg += "\n";
    	msg += res['message']
    	msg += "\n\n";
    	msg += "ファイルのダウンロードは、[OK]ボタンをクリックした後に行われます。\n";
    	msg += "(エラーが発生した上記注文は含まれません)\n";

    	alert(msg);
    }

    if  (res['status'] == 9) {
    	var msg = "エラーが発生しました。エラーが頻発する場合は、システム管理者へご連絡ください。\n";
    	msg += res['message'];
    	alert(msg);
    	location.reload(true);
        return;
    }

    // PDF出力処理
    var url = "<?php echo $this->baseUrl; ?>/rwclaim/print";
    var ref = window.open( url );

    // PDF出力が終わったら随時リロードする
    // 最大10秒待機させる
    var wait = 0;
    var intvl = setInterval(function() {
    	wait++;
        if (ref.closed == true || wait == 50){
            clearInterval(intvl);
            location.reload(true);
        }
    }, 200);
}

</script>
</html>
