<?php
namespace Coral\Coral\Mail;

use Zend\Db\Adapter\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-08 at 05:27:33.
 */
class CoralMailTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CoralMail
     */
    protected $object;

    /**
     * Adapterインスタンス
     * @var Adapter
     */
    protected $_db ;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $driver = array(
                'driver'    => $GLOBALS['adapter'],
                'host'      => $GLOBALS['host'],
                'database'  => $GLOBALS['dbname'],
                'username'  => $GLOBALS['username'],
                'password'  => $GLOBALS['password'],
                'charset'   => $GLOBALS['charset'],
        );
        $this->_db = new Adapter($driver);

        $smtpServer = '192.168.5.133';
        $this->object = new CoralMail($this->_db, $smtpServer, 'ISO-2022-JP');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->_db->getDriver()->getConnection()->disconnect();
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::sendDone
     * @todo   Implement testSendDone().
     */
    public function testSendDone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendExamMail
     * @todo   Implement testSendExamMail().
     */
    public function testSendExamMail()
    {
        $eid = "1";
        $this->object->SendExamMail($eid);
//         // Remove the following lines when you implement this test.
//         $this->markTestIncomplete(
//             'This test has not been implemented yet.'
//         );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendPasswdInfoMail
     * @todo   Implement testSendPasswdInfoMail().
     */
    public function testSendPasswdInfoMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendTestMailForEnterprise
     * @todo   Implement testSendTestMailForEnterprise().
     */
    public function testSendTestMailForEnterprise()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendOrderedMail
     * @todo   Implement testSendOrderedMail().
     */
    public function testSendOrderedMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendCreditFinishMail
     * @todo   Implement testSendCreditFinishMail().
     */
    public function testSendCreditFinishMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendCreditFinishEachEnt
     * @todo   Implement testSendCreditFinishEachEnt().
     */
    public function testSendCreditFinishEachEnt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendIssueBillMail
     * @todo   Implement testSendIssueBillMail().
     */
    public function testSendIssueBillMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendRcptConfirmMail
     * @todo   Implement testSendRcptConfirmMail().
     */
    public function testSendRcptConfirmMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendExecChargeMail
     * @todo   Implement testSendExecChargeMail().
     */
    public function testSendExecChargeMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendCancelMail
     * @todo   Implement testSendCancelMail().
     */
    public function testSendCancelMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendCheckMail
     * @todo   Implement testSendCheckMail().
     */
    public function testSendCheckMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendModifyEntMail
     * @todo   Implement testSendModifyEntMail().
     */
    public function testSendModifyEntMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendPaymentSoonMail
     * @todo   Implement testSendPaymentSoonMail().
     */
    public function testSendPaymentSoonMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendLimitPassageMail
     * @todo   Implement testSendLimitPassageMail().
     */
    public function testSendLimitPassageMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendSlipNumberDifference
     * @todo   Implement testSendSlipNumberDifference().
     */
    public function testSendSlipNumberDifference()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendReturnBillMail
     * @todo   Implement testSendReturnBillMail().
     */
    public function testSendReturnBillMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coral\Coral\Mail\CoralMail::SendCjMail
     * @todo   Implement testSendCjMail().
     */
    public function testSendCjMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
