<?php
// HTMLヘッダ
echo $this->render('oemadmin/document_header.php');
?>
</head>
<body>
    <div id="logincontents">
        <div id="frame">
            <div>
				<div id="header_logo">
                    <img src="resource/image/type/logo-l" alt="<?php echo f_e($this->oemInfo['ServiceName']); ?>" style="height: 25px" />
				</div>
                <div id="loginheadertitle">オペレーター認証エラー</div>
                <?php if (isset($this->isAccountLock)) { ?>
                <div align="center" padding-left="10px;">
                <?php
                echo "ログイン エラー回数が規定回数を超えました。 <br>";
                echo "セキュリティ保護のため、ログインを制限しています。<br>";
                echo "制限を解除するためには、お手数ですがサポート<br>";
                echo "センターまでお電話にてお問い合わせください。<br><br>";
                echo "サポートセンター電話番号： <br>";
                echo "TEL: 0120-667-690（10:00 ～ 18:00）";
                ?>
                </div>
                <?php } ?>
            </div>
            <p style="width: 90%; margin: 0 auto">
              <?php echo f_e($this->errMessage); ?>
            </p>
            <p style="text-align: center; margin-top: 40px"><a href="index">トップページへ</a></p>
        </div>
        <div id="loginfooter"><?php echo $this->oemInfo['Copyright']; ?></div>
    </div>
</body>
</html>