<?php
// HTMLヘッダ
echo $this->render('document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('page_header.php'); ?>
  <?php echo $this->render('page_menu.php'); ?>
  
  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">OEM先検索</h3>
    <form name="form" method="post" action="oemsearche/search">
      <table style="clear:both;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tr>
          <th>項目</th>
          <th>指定値</th>
          <th>項目補足</th>
        </tr>
        <tr>
          <td colspan="3" class="l_label">【基本情報】</td>
        </tr>
        <tr>
          <td class="r_label">申込日</td>
          <td class="l_data"><input type="text" name="ApplicationDateF" id="ApplicationDateF" />～<input type="text" name="ApplicationDateT" id="ApplicationDateT" /></td>
          <td class="l_data">YYYY-MM-DD形式で入力</td>
        </tr>
        <tr>
          <td class="r_label">OEM先名</td>
          <td class="l_data"><input type="text" size="50" name="OemNameKj" id="OemNameKj" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td class="r_label">OEM先名カナ</td>
          <td class="l_data"><input type="text" size="50" name="OemNameKn" id="OemNameKn" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td class="r_label">所在地</td>
          <td class="l_data"><input type="text" size="50" name="UnitingAddress" id="UnitingAddress" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td class="r_label">代表者氏名</td>
          <td class="l_data"><input type="text" size="50" name="RepNameKj" id="RepNameKj" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td class="r_label">代表者氏名カナ</td>
          <td class="l_data"><input type="text" size="50" name="RepNameKn" id="RepNameKn" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td class="r_label">代表電話番号</td>
          <td class="l_data"><input type="text" size="50" name="Phone" id="Phone" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td colspan="3" class="l_label">【連絡先情報】</td>
        </tr>
        <tr>
          <td class="r_label">担当者氏名</td>
          <td class="l_data"><input type="text" size="50" name="CpNameKj" id="CpNameKj" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td class="r_label">担当者氏名カナ</td>
          <td class="l_data"><input type="text" size="50" name="CpNameKn" id="CpNameKn" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td class="r_label">部署名</td>
          <td class="l_data"><input type="text" size="50" name="DivisionName" id="DivisionName" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td class="r_label">電話番号</td>
          <td class="l_data"><input type="text" size="50" name="ContactPhoneNumber" id="ContactPhoneNumber" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>
        <tr>
          <td class="r_label">メールアドレス</td>
          <td class="l_data"><input type="text" size="50" name="MailAddress" id="MailAddress" /></td>
          <td class="l_data">部分一致検索</td>
        </tr>

        <tr>
          <td colspan="3" class="l_data">&nbsp;</td>
        </tr>
        <tr>
          <td colspan="3" class="c_label"><input type="submit" value="　検　索　" /></td>
        </tr>
      </table>
    </form>
  </div>
  <!-- end contents -->
  
  <?php echo $this->render('page_footer.php'); ?>
</div>
</body>
</html>
