<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/template/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">削除確認</h3>
    <h4><center>テンプレート内部ID：<?php echo $this->templateid . '-' . f_e($this->templateseq); ?>を削除します。<br />よろしいですか？<br /><br />
    <a href="template/edit/mode/del/templateseq/<?php echo f_e($this->templateseq); ?>">はい</a>　　　　　<a href="template/index">いいえ</a>
    </center></h4>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
