<?php
// HTMLヘッダ
echo $this->render('document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('page_header.php'); ?>
  <?php echo $this->render('page_menu.php'); ?>
  
<!-- start contents -->
<div id="contents">
<h3>OMEオペレーター登録完了</h3>
<table class="datatable" width="860" cellpadding="1" cellspacing="1" border="0">
  <tr>
    <td class="label">ID</td>
    <td class="data"><?php echo $this->data["OemOpId"]; ?></td>
  </tr>
  <tr>
    <td class="label">ログインID</td>
    <td class="data"><?php echo $this->data["LoginId"]; ?></td>
  </tr>
  <tr>
    <td class="label">OEMID</td>
    <td class="data"><?php echo $this->oemidlist[$this->data["OemId"]]; ?></td>
  </tr>
  <?php if( isset($this->data['LoginPasswd']) ) { ?>
  <tr>
    <td class="label">パスワード</td>
    <td class="data"><?php echo $this->data["LoginPasswd"]; ?></td>
  </tr>
  <?php } ?>
  <tr>
    <td class="label">氏名</td>
    <td class="data"><?php echo $this->data["NameKj"]; ?></td>
  </tr>
  <tr>
    <td class="label">氏名カナ</td>
    <td class="data"><?php echo $this->data["NameKn"]; ?></td>
  </tr>
  <tr>
    <td class="label">所属</td>
    <td class="data"><?php echo $this->data["Division"]; ?></td>
  </tr>
</table>
</div>
  <?php echo $this->render('page_footer.php'); ?>
</div>
</body>
</html>
