<?php
// HTMLヘッダ
echo $this->render('oemadmin/document_header.php');
?>

<style>
    table {
        width: 900px;
        border: 1px gray solid;
    }
    table.top {
        background-color: #fff;
        border-radius: 3px;
    }
    .layout_container table.datatable {
        border: 1px lightgray solid;
    }
    table.datatable td.under {
        border-bottom: 3px solid lightgray;
    }
    .l_height {
        line-height: 17px;
    }
    table.margin0 {
        margin-bottom: 0px;
        font-size: 12px;
    }
    .scroll {
        height: 300px;
        overflow-y: scroll;
        border: 1px lightgray solid;
        margin-bottom: 10px;
    }
    .scroll table {
        width: 880px;
        margin: 0px;
    }
    .scrollbar {
        width: 12px;
        background-color: lightgray;
    }
    .width_80 {
        width: 80px;
    }
    .width_81 {
        width: 81px;
    }
    .width_100 {
        width: 100px;
    }
    .width_101 {
        width: 101px;
    }
    .width_220 {
        width: 220px;
    }
    .l_height {
        line-height: 15px;
    }
</style>
</head>
<body>
  <!-- start contents -->
  <div id="contents">
  <?php echo $this->render('oemadmin/page_header.php'); ?>
  <?php echo $this->render('oemadmin/monthly/page_menu.php'); ?>
  <div class="title"><span>キャンセル返金明細</span></div>

  <table class="datatable top">
    <tbody>
      <tr>
        <td class="l_data">
        <?php echo f_e($this->from."～".$this->to);?>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="layout_container">
    <table class="datatable width_500">
      <tbody>
        <tr>
            <td class="r_label width_250 under">対象店舗名</td>
            <td class="c_data under" style="background-color: lightyellow;"><?php echo $this->cancel_data['EnterpriseName'];?></td>
        </tr>
        <tr>
            <td class="r_label">対象店舗キャンセル返金総額</td>
            <td class="r_data"><?php echo f_nf(nvl($this->cancel_data['RepayTotal'],0),'#,##0');?>円</td>
        </tr>
        <tr>
            <td class="r_label">対象店舗キャンセル返金額(CB)</td>
            <td class="r_data">CBからの返金額：<?php echo f_nf(nvl($this->cancel_data['CbRefund'],0),'#,##0');?> 円</td>
        </tr>
        <tr>
            <td class="r_label">対象店舗キャンセル返金額(OEM)</td>
            <td class="r_data">OEMからの返金額：<?php echo f_nf(nvl($this->cancel_data['OemRefund'],0),'#,##0');?> 円</td>
        </tr>
      </tbody>
    </table>

    <table class="datatable margin0">
      <tbody>
        <tr>
            <td class="c_label width_81">注文ID</td>
            <td class="c_label width_80">任意注文番号</td>
            <td class="c_label width_100">購入者</td>
            <td class="c_label width_80">注文日</td>
            <td class="c_label width_80">立替締日</td>
            <td class="c_label width_80">キャンセル日</td>
            <td class="c_label width_100">請求額</td>
            <td class="c_label width_220">キャンセル返金額</td>
            <td class="scrollbar"> </td>
        </tr>
      </tbody>
    </table>
    <div class="scroll">
      <table class="datatable">
        <tbody>
            <?php foreach($this->cancel_detail_data as $value){?>
          <tr>
              <td class="l_data width_80"><?php echo f_e(nvl($value['OrderId'], 0));?></td>
              <td class="l_data width_80"><?php echo f_e(nvl($value['Ent_OrderId'], ""));?></td>
              <td class="l_data width_100"><?php echo f_e(nvl($value['NameKj'], 0));?></td>
              <td class="l_data width_80"><?php echo f_e(nvl($value['ReceiptOrderDate'], ""));?></td>
              <td class="l_data width_80"><?php echo f_e(nvl($value['Chg_FixedDate'],""));?></td>
              <td class="l_data width_80"><?php echo f_e(nvl($value['CancelDate'],""));?></td>
              <td class="r_data width_100"><?php echo f_nf(nvl($value['UseAmount'],0),'#,##0');?>円</td>
              <td class="r_data width_220 l_height">合計返金額：<?php echo f_nf(nvl($value['RepayTotal'],0),'#,##0');?>円<br />CBからの返金額：<?php echo f_nf(nvl($value['CbFee'],0),'#,##0');?>円<br />OEMからの返金額：<?php echo f_nf(nvl($value['OemFee'], 0),'#,##0');?>円<br /></td>
          </tr>
        <?php } ?>
        </tbody>
      </table>
    </div>
  <!-- end contents -->
  <!--
  <div style="font-size: 9pt; margin: 0px 8px; float: none; clear: both; width: 870px">
      ※「印紙代合計」とは、購入者様のコンビニ決済によるお支払金額が税込で\54,000以上の場合に発生する印紙代金の合計金額です。
  </div>
  -->
  <div class="note">
    <ul>
        <li>
            表示金額はすべて税込金額となっております。
        </li>
        <li>
            決済手数料の1円未満の端数は切捨てとなっております。
        </li>
    </ul>
  </div>

  <?php echo $this->render('oemadmin/page_footer.php'); ?>
</div>
</body>
</html>
