<?php
// HTMLヘッダ
echo $this->render('oemadmin/document_header.php');
?>
<style>
    table {
        width: 900px;
        border: 1px gray solid;
    }
    table.top {
        background-color: #fff;
        border-radius: 3px;
    }
	.layout_container table.datatable {
		border: 1px lightgray solid;
	}
	table.datatable td.under {
		border-bottom: 3px solid lightgray;
	}
	.l_height {
		line-height: 17px;
	}
	.width_400 {
		width: 400px;
	}
</style>
</head>
<body>
  <!-- start contents -->
  <div id="contents">
  <?php echo $this->render('oemadmin/page_header.php'); ?>
  <?php echo $this->render('oemadmin/monthly/page_menu.php'); ?>
      <div class="title"><span>店舗別精算明細</span></div>

  <table class="datatable top">
	<tbody>
	  <tr>
		<td class="l_data">
            <?php echo $this->from."～".$this->to;?>
		</td>
	  </tr>
	</tbody>
  </table>

<div class="layout_container">

      <table class="datatable">
        <tbody>
          <tr>
			  <td class="r_label width_400 under">対象店舗名</td>
			  <td class="c_data under" style="background-color: lightyellow;">
				<a href="monthly/trading/eid/<?php echo $this->enterprise_settlement['EnterpriseId'];?>/fd/<?php echo $this->enterprise_settlement['SpanFrom']."_".$this->enterprise_settlement['SpanTo'];?>">
					<?php echo f_e($this->enterprise_settlement['EnterpriseId']); ?>：<?php echo f_e($this->enterprise_settlement['EnterpriseNameKj']); ?>
				</a>
			  </td>
		  </tr>
          <tr>
			  <td class="r_label">対象店舗利用総額</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['UseAmount'],0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">対象店舗立替総額</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['PC_DecisionPayment'],0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">対象店舗精算総額</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['FixedTransferAmount'],0) + ($this->addtcflg ? nvl($this->enterprise_settlement['PC_TransferCommission'],0) : 0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label under">OEM手数料総額</td>
			  <td class="r_data under"><?php echo  f_nf(nvl($this->enterprise_settlement['OM_TotalProfit'],0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">店舗月額固定費</td>
			  <td class="r_data l_height">合計：<?php echo  f_nf(nvl($this->enterprise_settlement['CB_EntMonthlyFee'] + $this->enterprise_settlement['OM_EntMonthlyFee'],0),'#,##0'); ?>　円
			  <br />
			  CB請求額：<?php echo  f_nf(nvl($this->enterprise_settlement['CB_EntMonthlyFee'],0),'#,##0'); ?>　円
			  <br />
			  精算額：<?php echo  f_nf(nvl($this->enterprise_settlement['OM_EntMonthlyFee'],0),'#,##0'); ?>　円
			  <br />
			  </td>
		  </tr>
          <tr>
			  <td class="r_label">取引件数</td>
			  <td class="r_data"><?php echo $this->enterprise_settlement['OrderCount']; ?>　件</td>
		  </tr>
          <tr>
			  <td class="r_label">決済手数料率</td>
			  <td class="r_data l_height">合計：
			  <?php echo $this->enterprise_settlement['OecSettlementFeeRate'] - 0; ?>　％
			  <br />
			  CB決算手数料率：<?php echo $this->enterprise_settlement['OecSettlementFeeRate'] - $this->enterprise_settlement['OecOemSettlementFeeRate']; ?>　％
			  <br />
			  決算手数料率：<?php echo $this->enterprise_settlement['OecOemSettlementFeeRate'] - 0; ?>　％
			  <br /></td>
		  </tr>
          <tr>
			  <td class="r_label">決済手数料</td>
			  <td class="r_data l_height">合計：
			  <?php echo  f_nf(nvl($this->enterprise_settlement['CB_SettlementFee'] + $this->enterprise_settlement['OM_SettlementFee'],0),'#,##0'); ?>　円
			  <br />
			  CB請求額：<?php echo  f_nf(nvl($this->enterprise_settlement['CB_SettlementFee'],0),'#,##0'); ?>　円
			  <br />
			  精算額：<?php echo  f_nf(nvl($this->enterprise_settlement['OM_SettlementFee'],0),'#,##0'); ?>　円
			  <br />
			  </td>
		  </tr>
          <tr>
			  <td class="r_label">請求手数料(別送)</td>
			  <td class="r_data l_height">合計：<?php echo  f_nf(nvl($this->enterprise_settlement['CB_ClaimFeeBS'] + $this->enterprise_settlement['OM_ClaimFeeBS'],0),'#,##0'); ?>　円
			  <br />
			  CB請求額：<?php echo  f_nf(nvl($this->enterprise_settlement['CB_ClaimFeeBS'],0),'#,##0'); ?>　円
			  <br />
			  精算額：<?php echo  f_nf(nvl($this->enterprise_settlement['OM_ClaimFeeBS'],0),'#,##0'); ?>　円
			  <br />
			  </td>
		  </tr>
          <tr>
			  <td class="r_label">請求手数料(同梱)</td>
			  <td class="r_data l_height">合計：<?php echo  f_nf(nvl($this->enterprise_settlement['CB_ClaimFeeDK'] + $this->enterprise_settlement['OM_ClaimFeeDK'],0),'#,##0'); ?>　円
			  <br />
			  CB請求額：<?php echo  f_nf(nvl($this->enterprise_settlement['CB_ClaimFeeDK'],0),'#,##0'); ?>　円
			  <br />
			  精算額：<?php echo  f_nf(nvl($this->enterprise_settlement['OM_ClaimFeeDK'],0),'#,##0'); ?>　円
			  <br />
			  </td>
		  </tr>
          <tr>
			  <td class="r_label">キャンセルによる返金</td>
			  <td class="r_data">
			  <?php echo  f_nf(nvl($this->enterprise_settlement['CR_TotalAmount'],0),'#,##0'); ?>　円
			  <br />
			  入金額：<?php echo  f_nf(nvl($this->enterprise_settlement['CR_OemAmount'],0),'#,##0'); ?>　円
			  <br />
			  費用：<?php echo  f_nf(nvl($this->enterprise_settlement['CR_EntAmount'],0),'#,##0'); ?>　円
			  <br />
			  </td>
		  </tr>
          <tr>
			  <td class="r_label">前月持越</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['PC_CarryOver'],0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">印紙代</td>
			  <td class="r_data"><?php echo  f_nf(nvl(abs($this->enterprise_settlement['PC_StampFeeTotal']),0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">振り込み手数料</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['PC_TransferCommission'],0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">立替精算戻し額</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['PayBackAmount'],0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">精算調整額</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['PC_AdjustmentAmount'],0),'#,##0'); ?>　円</td>
		  </tr>
        </tbody>
      </table>
  <!-- end contents -->
<!--
<div style="font-size: 9pt; margin: 0px 8px; float: none; clear: both; width: 870px">
	※「印紙代合計」とは、購入者様のコンビニ決済によるお支払金額が税込で\54,000以上の場合に発生する印紙代金の合計金額です。(不必要？)
</div>
-->
<div class="note">
	<ul>
		<li>
			表示金額はすべて税込金額となっております。
		</li>
		<li>
			決済手数料の1円未満の端数は切捨てとなっております。
		</li>
	</ul>
</div>

  <?php echo $this->render('oemadmin/page_footer.php'); ?>
</div>
</body>
</html>
