<?php
// HTMLヘッダ
echo $this->render('oemadmin/document_header.php');
?>
<style>
    table {
        width: 900px;
        border: 1px gray solid;
    }
    table.top {
        background-color: #fff;
        border-radius: 3px;
    }
	.layout_container table.datatable {
		border: 1px lightgray solid;
	}
	table.datatable td.under {
		border-bottom: 3px solid lightgray;
	}
	.l_height {
		line-height: 17px;
	}
	table.margin0 {
		margin-bottom: 0px;
		font-size: 12px;
	}
	.scroll {
		height: 300px;
		overflow-y: scroll;
		border: 1px lightgray solid;
		margin-bottom: 10px;
	}
	.scroll table {
		width: 880px;
		margin: 0px;
	}
	.scrollbar {
		width: 11px;
		background-color: lightgray;
	}
	.width_70 {
		width: 70px;
	}
	.width_80 {
		width: 80px;
	}
	.width_81 {
		width: 81px;
	}
	.width_100 {
		width: 100px;
	}
</style>
</head>
<body>
  <!-- start contents -->
  <div id="contents">
  <?php echo $this->render('oemadmin/page_header.php'); ?>
  <?php echo $this->render('oemadmin/monthly/page_menu.php'); ?>
      <div class="title"><span>取引別精算明細</span></div>

  <table class="datatable top">
	<tbody>
	  <tr>
		<td class="l_data">
            <?php echo $this->from."～".$this->to;?>
		</td>
	  </tr>
	</tbody>
  </table>

<div class="layout_container">
      <table class="datatable width_440">
        <tbody>
          <tr>
			  <td class="r_label width_150 under">対象店舗名</td>
			  <td class="c_data under" style="background-color: lightyellow;"><?php echo f_e($this->enterprise_settlement['EnterpriseNameKj']);?></td>
		  </tr>
          <tr>
			  <td class="r_label">対象店舗利用総額</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['UseAmount'],0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">対象店舗立替総額</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['PC_DecisionPayment'],0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">対象店舗精算総額</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['FixedTransferAmount'],0),'#,##0'); ?>　円</td>
		  </tr>
          <tr>
			  <td class="r_label">OEM手数料総額</td>
			  <td class="r_data"><?php echo  f_nf(nvl($this->enterprise_settlement['OM_TotalProfit'],0),'#,##0'); ?>　円</td>
		  </tr>
        </tbody>
      </table>
      <table class="datatable margin0">
        <tbody>
		  <tr>
			  <td class="c_label width_81">注文ID</td>
			  <td class="c_label width_80">任意注文番号</td>
			  <td class="c_label width_80">購入者</td>
			  <td class="c_label width_70">注文日</td>
			  <td class="c_label width_70">伝票登録日</td>
			  <td class="c_label width_70">立替締日</td>
			  <td class="c_label width_80">請求額</td>
			  <td class="c_label width_80">決済手数料</td>
			  <td class="c_label width_100">請求手数料(別送)</td>
			  <td class="c_label width_100">請求手数料(同梱)</td>
			  <td class="scrollbar"> </td>
		  </tr>
        </tbody>
      </table>
	<div class="scroll">
      <table class="datatable">
        <tbody>
            <?php foreach($this->oem_trading_settlement as $value){;?>
                  <tr>
                      <td class="l_data width_80"><?php echo f_e($value['OrderId']);?></td>
                      <td class="l_data width_80"><?php echo f_e($value['Ent_OrderId']);?></td>
                      <td class="l_data width_80"><?php echo f_e($value['NameKj']);?></td>
                      <td class="l_data width_70"><?php echo f_e($value['ReceiptOrderDate']);?></td>
                      <td class="l_data width_70"><?php echo f_e($value['Deli_JournalIncDate']);?></td>
                      <td class="l_data width_70"><?php echo f_e($value['Chg_FixedDate']);?></td>
                      <td class="r_data width_80"><?php echo f_nf($value['UseAmount'],'#,##0');?>円</td>
                      <td class="r_data width_80">合計：<?php echo f_nf(nvl($value['SettlementFeeTotal'],0),'#,##0'); ?>円
                      <br />
                      CB：<?php echo f_nf(nvl($value['SettlementFeeCB'],0),'#,##0'); ?>円
                      <br />
                      OEM：<?php echo f_nf(nvl($value['SettlementFeeOEM'],0),'#,##0'); ?>円
                      <br /></td>
                      <td class="r_data width_100">合計：<?php echo f_nf(nvl($value['ClaimFeeTypeTotal'],0),'#,##0'); ?>円
                      <br />
                      CB：<?php echo f_nf(nvl($value['ClaimFeeTypeCB'],0),'#,##0'); ?>円
                      <br />
                      OEM：<?php echo f_nf(nvl($value['ClaimFeeTypeOEM'],0),'#,##0'); ?>円
                      <br /></td>
                      <td class="r_data width_100">合計：<?php echo f_nf(nvl($value['ClaimFeeType2Total'],0),'#,##0'); ?>円
                      <br />
                      CB：<?php echo f_nf(nvl($value['ClaimFeeType2CB'],0),'#,##0'); ?>円
                      <br />
                      OEM：<?php echo f_nf(nvl($value['ClaimFeeType2OEM'],0),'#,##0'); ?>円
                      <br /></td>
                  </tr>
		    <?php } ?>
        </tbody>
      </table>
	</div>
  <!-- end contents -->
  <!--
<div style="font-size: 9pt; margin: 0px 8px; float: none; clear: both; width: 870px">
	※「印紙代合計」とは、購入者様のコンビニ決済によるお支払金額が税込で\54,000以上の場合に発生する印紙代金の合計金額です。
</div>
  -->
<div class="note">
	<ul>
		<li>
			表示金額はすべて税込金額となっております。
		</li>
		<li>
			決済手数料の1円未満の端数は切捨てとなっております。
		</li>
	</ul>
</div>

  <?php echo $this->render('oemadmin/page_footer.php'); ?>
</div>
</body>
</html>
