<?php
use models\Logic\LogicOemClaimAccount;

// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
if( ! isset($this->error) || ! is_array($this->error) ) $this->error = array();

function show_error_message($messages) {
    if( empty($messages) ) return;
    if( ! is_array($messages) ) $messages = array($messages);
    $list = array();
    foreach($messages as $msg) $list[] = f_e($msg);
    echo '<div class="input_error_message">';
    echo join('<br />', $list);
    echo '</div>';
}

$data = $this->data;
$logic_name_map = array();
foreach($this->agents as $agent) {
  if($agent['ReceiptAgentId'] == $data['Cv_ReceiptAgentId']) {
    $this->Cv_ReceiptAgentName = $agent['ReceiptAgentName'];
    $this->Cv_BarcodeLogicName = $agent['BarcodeLogicName'];
    $this->Cv_ReceiptAgentCode = $agent['ReceiptAgentCode'];
    break;
  }
}
?>
<style type="text/css">
<!--
#contents table.datatable {
  width: 862px;
  margin-top: 0;
  margin-bottom: 10px;
}
#contents h4.category-title {
  width: 840px;
  margin-top: 10px;
  margin-bottom: 0;
  padding-right: 0;
  border: solid 1px #ddd;
  border-bottom-width: 0;
}

#contents div.submit-area {
  width: 842px;
  margin: 10px 25px 20px 25px;
  padding: 5px 10px;
  border: none 0;
  text-align: center;
}

.submit-area button,
.submit-area input[type=button],
.submit-area input[type=submit],
.submit-area a {
  padding: 4px 25px;
}

#contents td {
  padding-top: 2px;
  padding-bottom: 2px;
}

td.l_label {
    text-align: left;
    padding: 0px 0px 0px 5px;
    background-color: #eeeeee;
    width: 180px;
    white-space: nowrap;
}

td.r_label {
    text-align: right;
    padding: 0px 5px 0px 0px;
    background-color: #eeeeee;
    width: 180px;
    white-space: nowrap;
}

td.c_label {
    text-align: center;
    /*padding: 2px 10px 2px 0px;*/
    background-color: #eeeeee;
}

td.l_data {
    text-align: left;
    padding: 0px 0px 0px 5px;
    background-color: #ffffff;
}

td.l_data span.wrap_container {
    width: 398px;
    overflow: hidden;
    float: left;
}

td.r_data {
    text-align: right;
    padding: 0px 5px 0px 0px;
    background-color: #ffffff;
}

td.c_data {
    text-align: center;
    padding: 2px 0px 2px 0px;
    background-color: #ffffff;
}

div {
    margin: 0px;
    padding: 0px;
    font-size: 12px;
    font-family: "ＭＳ Ｐゴシック", Osaka, "ヒラギノ角ゴ Pro W3";
}

.detail-tools {
  margin: 5px 25px;
  font-size: 16px;
  text-align: right;
}

.detail-tools a,
.detail-tools span.dummy-link {
    margin: 0 0 0 12px;
}
#contents .warning {
  width: 842px;
  margin: 5px 25px;
  font-size: 1em;
  font-weight: bold;
  color: red;
  border: solid 1px firebrick;
  background-color: mistyrose;
  padding: 8px 12px;
}
-->
</style>
<script type="text/javascript">
Event.observe(window, 'load', function() {
  Event.observe($('submit-button'), 'click', function() {
    $('main-form').submit();
  });
  Event.observe($('undo-button'), 'click', function() {
    var url = [
        (document.getElementsByTagName('base')[0] || { href : '' }).href.replace(/\/*$/, ''),
        'claimaccount/edit/oid',
        $('oid').value
    ].join('/');
    $('main-form').action = url;
    $('main-form').submit();
  });
});
</script>
</head>
<body>
<div id="wrapper"><!-- start #wrapper -->
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/claimaccount/page_menu.php'); ?>

<!-- start #contents -->
<div id="contents">
  <h3>請求口座登録内容確認 - <?php echo f_e($this->oname); ?></h3>

<?php if($this->hisCount) { ?>
  <div class="warning">
    ※：未印刷の請求が <?php echo f_nf($this->hisCount, '#,##0'); ?> 件あります。これらの請求情報に設定内容の変更は反映されません。
  </div>
<?php } ?>

<form id="main-form" action="claimaccount/save" method="post">
  <input id="oid" name="form[OemId]" value="<?php echo f_e($this->oid); ?>" type="hidden" />
  <input name="hashed" value="<?php echo f_e($this->hashed); ?>" type="hidden" />
  <h4 class="category-title">銀行口座</h4>
  <table class="datatable" cellpadding="1" cellspacing="1" border="0">
    <tbody>

    <tr>
      <td class="r_label">口座サービス区分</td>
      <td class="l_data">
        <?php
        $map = $this->master_map[LogicOemClaimAccount::MAPKEY_BK_SERVICE_KIND];
        echo f_e(nvl($map[$data['Bk_ServiceKind']], $data['Bk_ServiceKind']));
        ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">銀行名</td>
      <td class="l_data">
        <?php echo f_e($data['Bk_BankName']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">銀行コード</td>
      <td class="l_data">
        <?php echo f_e($data['Bk_BankCode']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">支店名</td>
      <td class="l_data">
        <?php echo f_e($data['Bk_BranchName']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">支店コード</td>
      <td class="l_data">
        <?php echo f_e($data['Bk_BranchCode']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">口座種別</td>
      <td class="l_data">
        <?php
        $map = $this->master_map[LogicOemClaimAccount::MAPKEY_BK_DEPOSIT_CLASS];
        echo f_e(nvl($map[$data['Bk_DepositClass']], $data['Bk_DepositClass']));
        ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">口座番号</td>
      <td class="l_data">
        <?php echo f_e($data['Bk_AccountNumber']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">口座名義</td>
      <td class="l_data">
        <?php echo f_e($data['Bk_AccountHolder']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">口座名義カナ</td>
      <td class="l_data">
        <?php echo f_e($data['Bk_AccountHolderKn']); ?>
      </td>
    </tr>
    </tbody>
  </table>

  <h4 class="category-title">ゆうちょ口座</h4>
  <table class="datatable" cellpadding="1" cellspacing="1" border="0">
    <tbody>

    <tr>
      <td width="100" class="r_label">加入者名</td>
      <td class="l_data">
        <?php echo f_e($data['Yu_SubscriberName']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">口座番号</td>
      <td class="l_data">
        <?php echo f_e($data['Yu_AccountNumber']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">払込負担区分</td>
      <td class="l_data">
        <?php
        $map = $this->master_map[LogicOemClaimAccount::MAPKEY_YU_CHARGE_CLASS];
        echo f_e(nvl($map[$data['Yu_ChargeClass']], $data['Yu_ChargeClass']));
        ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">加入者固有データ</td>
      <td class="l_data">
        <?php echo f_e($data['Yu_SubscriberData']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">オプション1</td>
      <td class="l_data">
        <?php echo f_e($data['Yu_Option1']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">オプション2</td>
      <td class="l_data">
        <?php echo f_e($data['Yu_Option2']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">オプション3</td>
      <td class="l_data">
        <?php echo f_e($data['Yu_Option3']); ?>
      </td>
    </tr>
    </tbody>
  </table>

  <h4 class="category-title">コンビニ収納代行</h4>
  <table class="datatable" cellpadding="1" cellspacing="1" border="0">
    <tbody>

    <tr>
      <td width="100" class="r_label" rowspan="3">収納代行会社</td>
      <td class="l_data">
        <?php echo f_e(sprintf('%s：%s', $data['Cv_ReceiptAgentId'], $this->Cv_ReceiptAgentName)); ?>
      </td>
    </tr>
    <tr>
      <td class="l_data" style="padding-left: 20px">
        バーコード生成ロジック： <?php echo f_e($this->Cv_BarcodeLogicName); ?>
      </td>
    </tr>
    <tr>
      <td class="l_data" style="padding-left: 20px">
        収納代行会社固有コード： <?php echo f_e($this->Cv_ReceiptAgentCode); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">加入者固有コード</td>
      <td class="l_data">
        <?php echo f_e($data['Cv_SubscriberCode']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">加入者名</td>
      <td class="l_data">
        <?php echo f_br($data['Cv_SubscriberName']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">オプション1</td>
      <td class="l_data">
        <?php echo f_e($data['Cv_Option1']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">オプション2</td>
      <td class="l_data">
        <?php echo f_e($data['Cv_Option2']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">オプション3</td>
      <td class="l_data">
        <?php echo f_e($data['Cv_Option3']); ?>
      </td>
    </tr>
    </tbody>
  </table>

<?php if($data['Bk_ServiceKind'] == 1) { ?>
  <h4 class="category-title">SMBC決済ステーション</h4>
  <table class="datatable" cellpadding="1" cellspacing="1" border="0">
    <tbody>

    <tr>
      <td width="100" class="r_label">連携アカウント名</td>
      <td class="l_data">
        <?php echo f_e($data['Smbc_DisplayName']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">APIバージョン</td>
      <td class="l_data">
        <?php echo f_e($data['Smbc_ApiVersion']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">決済手段区分／決済種別コード</td>
      <td class="l_data">
        <?php echo f_e(join('／', array($data['Smbc_BillMethod'], $data['Smbc_KessaiId']))); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">契約コード</td>
      <td class="l_data">
        <?php echo f_e($data['Smbc_ShopCd']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">収納企業コード</td>
      <td class="l_data">
        圧着用：<?php echo f_e($data['Smbc_SyunoCoCd1']); ?> ／
        封書用：<?php echo f_e($data['Smbc_SyunoCoCd2']); ?> ／
        同梱用：<?php echo f_e($data['Smbc_SyunoCoCd3']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">収納企業コード（LINE Pay）</td>
      <td class="l_data">
        圧着用：<?php echo f_e($data['Smbc_SyunoCoCd4']); ?> ／
        封書用：<?php echo f_e($data['Smbc_SyunoCoCd5']); ?> ／
        同梱用：<?php echo f_e($data['Smbc_SyunoCoCd6']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">アクセスパスワード1（圧着用）</td>
      <td class="l_data"><?php echo f_e($data['Smbc_ShopPwd1']); ?></td>
    </tr>
    <tr>
      <td width="100" class="r_label">アクセスパスワード2（封書用）</td>
      <td class="l_data"><?php echo f_e($data['Smbc_ShopPwd2']); ?></td>
    </tr>
    <tr>
      <td width="100" class="r_label">アクセスパスワード3（同梱用）</td>
      <td class="l_data"><?php echo f_e($data['Smbc_ShopPwd3']); ?></td>
    </tr>
    <tr>
      <td width="100" class="r_label">アクセスパスワード4（LINE Pay圧着用）</td>
      <td class="l_data"><?php echo f_e($data['Smbc_ShopPwd4']); ?></td>
    </tr>
    <tr>
      <td width="100" class="r_label">アクセスパスワード5（LINE Pay封書用）</td>
      <td class="l_data"><?php echo f_e($data['Smbc_ShopPwd5']); ?></td>
    </tr>
    <tr>
      <td width="100" class="r_label">アクセスパスワード6（LINE Pay同梱用）</td>
      <td class="l_data"><?php echo f_e($data['Smbc_ShopPwd6']); ?></td>
    </tr>
    <tr>
      <td width="100" class="r_label">請求内容／カナ</td>
      <td class="l_data">
        <?php echo f_e(join('／', array($data['Smbc_SeikyuuName'], $data['Smbc_SeikyuuKana']))); ?>
      </td>
    </tr>

    <tr>
      <td width="100" class="r_label">ゆうちょ加入者名</td>
      <td class="l_data">
        <?php echo f_e($data['Smbc_Yu_SubscriberName']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">ゆうちょ口座番号／払込負担区分</td>
      <td class="l_data">
        <?php
        $map = $this->master_map[LogicOemClaimAccount::MAPKEY_YU_CHARGE_CLASS];
        $kbn = nvl($map[$data['Smbc_Yu_ChargeClass']], $data['Smbc_Yu_ChargeClass']);
        ?>
        <?php echo f_e(join('／', array($data['Smbc_Yu_AccountNumber'], $kbn))); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">コンビニ収納代行会社名</td>
      <td class="l_data">
        <?php echo f_e($data['Smbc_Cv_ReceiptAgentName']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">コンビニ収納ファイナンスコード</td>
      <td class="l_data">
        <?php echo f_e($data['Smbc_Cv_ReceiptAgentCode']); ?>
      </td>
    </tr>
    <tr>
      <td width="100" class="r_label">コンビニ収納代行加入者名</td>
      <td class="l_data">
        <?php echo f_e($data['Smbc_Cv_SubscriberName']); ?>
      </td>
    </tr>
    </tbody>
  </table>
<?php } ?>

  <div class="submit-area">
    <button id="submit-button" type="button">登録内容確定</button>
    <button id="undo-button" type="button">内容を修正する</button>
    <a href="claimaccount/detail/oid/<?php echo f_e($this->oid); ?>">キャンセル</a>
  </div>

</form>

</div><!-- end #contents -->


  <?php echo $this->render('cbadmin/page_footer.php'); ?>

</div><!-- end #wrapper -->
</body>
</html>
