<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<style>
table.datatable th {
  white-space: nowrap;
}

  a.download_link {
    padding: 8px;
    padding-left: 25px;
    background-image: url('../images/icon_download_s.gif');
    background-repeat: no-repeat;
    background-position: 8px center;
    font-size: 12px;
  }
  a.download_link,
  a.download_link:link,
  a.download_link:hover,
  a.download_link:active,
  a.download_link:visited {
    border: solid 1px silver;
    background-color: transparent;
    color: royalblue;
  }
  a.download_link:hover {
    background-color: azure;
    border-color: gray;
    color: blue;
  }

</style>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/enterprisecontract/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">加盟店サイト契約情報一覧</h3>
    <div style="margin: 5px 25px;">

    <table style="margin: 0px; clear:both;" width="862" id="search_result" class="datatable" cellpadding="1" cellspacing="1" border="0">
      <div class="page_nav">
        <span class="pager"><a class="download_link" href="enterprisecontract/download">詳細一覧をCSVダウンロード</a></span>
      </div>
      <tbody>
          <tr>
            <th rowspan="3">事業者ID</th>
            <th>ログインID</th>
            <th>事業者名</th>
            <th>プラン</th>
            <th style="width:100px">締め日</th>
            <th style="width:115px">担当者名</th>
            <th style="width:100px">担当部署</th>
            <th style="width:85px">連絡先</th>
          </tr>
          <tr>
            <th colspan="7">各種オプション</th>
          </tr>
          <tr>
            <th>サイトID</th>
            <th colspan="2">サイト名（カナ）</th>
            <th>登録日</th>
            <th colspan="3">URL</th>
          </tr>

          <?php $previous_enterprise_id = -1;/* 1つ前の加盟店ID */ ?>
          <?php $siteCounter = -1;/* ｻｲﾄ件数ｶｳﾝﾀ */ ?>
          <?php foreach ($this->list as $row) { ?>
          <?php     if ($previous_enterprise_id != $row['EnterpriseId']) { ?>
          <?php         $siteCounter = 0;/* ｻｲﾄ件数ｶｳﾝﾀのｾﾞﾛ初期化 */ ?>

          <tr class="data ent-row oem-<?php echo f_e(nvl($row['OemId'], 0)); ?>">
            <td rowspan="<?php echo 2 + (int)$row['SiteCount'];?>" class="r_data">
            <?php if ($row['IsLatest1stOrder'] == 1) { ?>
            <font color="red"><b>New</b></font></br>
            <?php echo f_e($row['EnterpriseId']); ?>
            <?php } else { ?>
            <?php echo f_e($row['EnterpriseId']); ?>
            <?php } ?>
            </td>
            <td class="c_data"><?php echo f_e($row['LoginId']); ?></td>
            <td class="l_data"><a href="enterprise/detail/eid/<?php echo f_e($row['EnterpriseId']); ?>"><?php echo f_e($row['EnterpriseNameKj']); ?></a></td>
            <td class="l_data"><?php echo f_e($row['PlanNm']); ?></td>
            <td class="l_data"><?php echo f_e($row['FixPatternNm']); ?></td>
            <td class="l_data"><?php echo f_e($row['CpNameKj']) . '<br />(' . f_e($row['CpNameKn']) . ')'; ?></td>
            <td class="l_data"><?php echo f_e($row['DivisionName']); ?></td>
            <td class="l_data"><?php echo f_e($row['ContactPhoneNumber']); ?></td>
          </tr>
          <tr class="data ent-row oem-<?php echo f_e(nvl($row['OemId'], 0)); ?>">
            <td colspan="7" class="l_data ent-options">
              <?php
              $opt = $this->optionMap[$row['EnterpriseId']];
              if($opt) {
                $cols = array(
                  sprintf('<span class="ent-option">与信モード：%s</span>', f_e($this->master_map['AutoCreditJudgeMode'][$opt['AutoCreditJudgeMode']])),
                  sprintf('<span class="ent-option">取りまとめ請求：%s</span>', f_e($this->master_map['CombinedClaimMode'][$opt['CombinedClaimMode']]))
                );
                if($opt['UseApi']) $cols[] = '<span class="ent-option">API利用</span>';
                if($opt['UseSelfBilling']) $cols[] = '<span class="ent-option">同梱利用</span>';
                if($opt['CanJournalUpdate']) $cols[] = '<span class="ent-option">伝票番号更新可能</span>';
                if($opt['UseFirstClaimLayout']) $cols[] = '<span class="ent-option">初回封書</span>';
                if($opt['UseAutoJournalInc']) $cols[] = '<span class="ent-option">伝票自動仮登録</span>';
                echo join('/', $cols);
              } else {
                echo '&nbsp;';
              }
            ?>
            </td>
          </tr>
          <?php     } ?>

              <?php if (!is_null($row['SiteId'])) {/* SiteIdが非null時は出力 */ ?>
          <tr class="data ent-row oem-<?php echo f_e(nvl($row['OemId'], 0)); ?>">
            <td class="c_data"><?php echo f_e($row['SiteId']); ?></td>
            <td class="l_data" colspan="2">
            <a href="<?php echo $this->baseUrl . '/site/edit/eid/' . $row['EnterpriseId'] . '/sid/' . $row['SiteId'] ; ?>"><?php echo f_e($row['SiteNameKj']); ?></a>　
            <?php echo f_e($row['SiteNameKn']); ?></td>
            <td class="c_data"><?php echo f_e(date('Y-m-d', strtotime($row['RegistDate']))); ?></td>
            <td class="l_data" colspan="3"><?php echo f_e($row['Url']); ?></td>
          </tr>
              <?php     $siteCounter++;/* ｻｲﾄ件数ｶｳﾝﾀのｲﾝｸﾘﾒﾝﾄ */ ?>
              <?php }?>

          <?php     if ($siteCounter == $row['SiteCount']) {/* ﾌｨｰﾙﾄﾞ件数とｻｲﾄ件数ｶｳﾝﾀを比較、一致時出力 */ ?>
          <tr class="border ent-row oem-<?php echo f_e(nvl($row['OemId'], 0)); ?>">
          </tr>
          <?php     } ?>

          <?php     $previous_enterprise_id = $row['EnterpriseId'];/* 1つ前の加盟店IDを現行値で更新 */ ?>
          <?php } ?>

      <tbody>
    </table>
    </div>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
<script>
// 結果テーブルをスクロール可能にする
// new base.UI.TableEx(document.getElementById("search_result"), { height : 500 } );
</script>
</html>
