      <table class="datatable">
        <tbody>
          <tr>
            <td class="l_data">
              <a style="margin-left:10px;" href="paying/trnlist/pcseq/<?php echo f_e($this->pcseq); ?>">[注文明細]</a>
              <a style="margin-left:10px;" href="paying/cnllist/pcseq/<?php echo f_e($this->pcseq); ?>">[キャンセル明細]</a>
              <a style="margin-left:10px;" href="paying/stamplist/pcseq/<?php echo f_e($this->pcseq); ?>">[印紙代明細]</a>
              <a style="margin-left:10px;" href="paying/paybacklist/pcseq/<?php echo f_e($this->pcseq); ?>">[立替精算戻し明細]</a>
              </td>
          </tr>
        </tbody>
      </table>
