<?php
use Coral\Coral\View\CoralViewCommandBar;
use Coral\Coral\View\CommandBar\CoralViewCommandBarButton;
use Zend\Json\Json;

// HTMLヘッダ
echo $this->render( 'member/document_header.php' );

// アプリケーション名割り当て
$this->applicationTitle = '後払い決済管理システム';

?>
<script type="text/javascript">
function doSubmit() {
	($('confirmed_form') || { submit : function() { alert('cannot post !!'); }}).submit();
}
Event.observe(window, 'load', function() {
	if($('result_table')) new base.UI.TableEx($('result_table'), { height : 300 });
	if($('error_table')) new base.UI.TableEx($('error_table'), { height : 300 });
});
</script>
</head>
<body>
<?php
// 共通ページヘッダ
echo $this->render( 'member/page_header.php' );
// ヘッダのメニュー
echo $this->render( 'member/header_menu.php' );

// システムメッセージ
echo $this->render( 'member/system_message.php' );

// ページタイトル
echo $this->render( 'member/page_title.php' );
?>
<div class="main_contents">

<?php if(!$this->hasData) { /* 更新可能行がない場合 */ ?>
<?php
$commandBar = new CoralViewCommandBar(
	// title
	f_nf($this->errorCount, '更新可能なデータがありません (#,##0 件のエラー)'),
	// buttons
	array(
		new CoralViewCommandBarButton(
			array(
				CoralViewCommandBarButton::OPTION_ID => 'backTo',
				CoralViewCommandBarButton::OPTION_HREF => 'shipping/changeCsv',
				CoralViewCommandBarButton::OPTION_TEXT => '一括配送伝票修正(CSV使用)へ戻る',
				CoralViewCommandBarButton::OPTION_TITLE => '前の画面に戻ってファイルを訂正してください'
			)
		)
	)
);

// コマンドバーのレンダリング
echo $commandBar->render();
?>

    <h3>エラー内容</h3>
    <center>
    <table class="csv_result" border="1" cellpadding="0" cellspacing="0">
        <thead><tr><th>行</th><th>注文ID</th><th>任意注文番号</th><th>エラー内容</th></tr></thead>
        <tbody>
    <?php foreach( $this->errorRows as $error ) { ?>
        <tr>
        <td><?php echo ($error->getLineNumber() + 1); ?></td>
        <td><?php echo escape( $error->getData()['_raw_data']['OrderId'] ); ?></td>
        <td><?php echo escape( $error->getData()['_raw_data']['Ent_OrderId'] ); ?></td>
        <td>
<?php
            foreach( $error->getData() as $key => $data ) {
                if( ! preg_match( '/^\d+$/', $key ) ) continue;
                $colName = key( $data );
                $colLabel = $colName;
                foreach( $this->colSchema as $schema ) {
                    if( $schema['ColumnName'] == $colName ) {
                        $colLabel = $schema['Caption'];
                    }
                }
                echo "$colLabel : {$data[$colName]}" . '<br/>';
            }
?>
        </td></tr>
<?php
    }
?>
        </tbody>
    </table>
    </center>

<?php } else {
$commandBar = new CoralViewCommandBar(
	// title
	$this->validCount ?
		sprintf('%s 件のデータが更新可能です (%s 件のエラー)', f_nf($this->validCount, '#,##0'), f_nf($this->errorCount, '#,##0')) :
		f_nf($this->errorCount, '更新可能なデータがありません (#,##0 件のエラー)')
);

// buttons
if($this->validCount) {
	$commandBar
		->addButton(
			new CoralViewCommandBarButton(
				array(
					CoralViewCommandBarButton::OPTION_ID => 'confirmed',
					CoralViewCommandBarButton::OPTION_HREF => 'javascript:doSubmit()',
					CoralViewCommandBarButton::OPTION_TEXT => 'この内容で更新',
					CoralViewCommandBarButton::OPTION_TITLE => '内容に問題がなければ、ここをクリックして更新を実行します'
				)
			)
		);
}
	$commandBar
		->addButton(
			new CoralViewCommandBarButton(
				array(
					CoralViewCommandBarButton::OPTION_ID => 'backTo',
					CoralViewCommandBarButton::OPTION_HREF => 'shipping/changeCsv',
					CoralViewCommandBarButton::OPTION_TEXT => '一括配送伝票修正(CSV使用)へ戻る',
					CoralViewCommandBarButton::OPTION_TITLE => '前の画面に戻ってファイルを訂正してください'
				)
			)
		);
// コマンドバーのレンダリング
echo $commandBar->render();
?>
	<div style="padding-left: 40px">
<?php if(isset($this->validRows) && $this->validCount) { ?>
	<h4 class="csv_result_title">更新可能なデータ：<?php echo f_nf($this->validCount, '#,##0 件'); ?></h4>
	<table id="result_table" class="csv_result" border="1" cellpadding="0" cellspacing="0">
	    <thead>
			<tr>
				<th>行</th>
			<?php foreach($this->colSchema as $schema) { ?>
				<th><?php echo $schema['Caption']; ?></th>
			<?php } ?>

			</tr>
		</thead>
		<tbody>
		<?php foreach($this->validRows as $index => $validRow) { ?>
			<?php $row = $validRow->getData(); ?>
		<tr>
			<td style="text-align: right"><?php echo f_nf($validRow->getLineNumber() + 1, '#,##0'); ?></td>
			<?php foreach($this->colSchema as $schema) { ?>
			<?php     $col_name = $schema['ColumnName']; ?>
			<td<?php if($col_name == 'Deli_JournalNumber') echo ' class="main_col"'; ?>>
			<?php if($col_name == 'OrderId') { ?>
				<a href="search/detail/id/<?php echo f_e($row[$col_name]); ?>" target="_blank">
					<?php echo f_e($row[$col_name]); ?>
				</a>
			<?php } else { ?>
				<?php echo f_e($row[($col_name == 'Deli_DeliveryMethod') ? 'Deli_DeliveryMethodName' : $col_name]); ?>
			<?php } ?>
			</td>
			<?php } ?></tr>
		<?php } ?>
		</tbody>
	</table>
	<form id="confirmed_form" method="post" action="<?php echo 'shipping/saveCsv/mode/save/back/'. $this->back; ?>">
		<center>
			<button type="submit">この内容で更新</button>
		</center>
	</form>
<?php } ?>

<?php if(isset($this->errorRows) && $this->errorCount) { ?>
	<h4 class="csv_result_title">エラーデータ：<?php echo f_nf($this->errorCount, '#,##0 件'); ?></h4>
	<table id="error_table" class="csv_result" border="1" cellpadding="0" cellspacing="0">
		<thead>
			<tr>
				<th>行</th>
				<th style="width:150px">エラー内容</th>
			<?php foreach($this->colSchema as $schema) { ?>
				<th><?php echo $schema['Caption']; ?></th>
			<?php } ?>
			</tr>
		</thead>
		<tbody>
		<?php
		foreach($this->errorRows as $index => $errorRow) {
			$topRow = $errorRow->getData();
			$row = $topRow['_raw_data'];
			$errInfo = array();
			foreach($topRow as $i => $info) {
				if(!is_int($i)) continue;
				foreach($info as $key => $value) {
					if(!is_array($errInfo[$key])) $errInfo[$key] = array();
					$errInfo[$key][] = $value;
				}
			}
		?>
		<tr>
			<td style="text-align: right"><?php echo f_nf($errorRow->getLineNumber() + 1, '#,##0'); ?></td>
			<td class="error_info" style="white-space:normal;width:150px">
				<ul><?php foreach($errInfo as $key => $info) { ?>
					<?php foreach($info as $i => $value) { echo sprintf('<li>%s</li>', f_e($value)); } ?>
				<?php } ?></ul>
			</td>
			<?php foreach($this->colSchema as $schema) { ?>
			<?php     $col_name = $schema['ColumnName']; ?>
			<td<?php if($errInfo[$col_name]) { ?> style="background-color: pink"<?php }?>>
			<?php if($col_name == 'OrderId' && !$errInfo[$col_name]) { ?>
				<a href="search/detail/id/<?php echo f_e($row[$col_name]); ?>" target="_blank">
					<?php echo f_e($row[$col_name]); ?>
				</a>
			<?php } else { ?>
				<?php echo f_e($row[($col_name == 'Deli_DeliveryMethod') ? 'Deli_DeliveryMethodName' : $col_name]); ?>
			<?php } ?>
			</td>
			<?php } ?>
		</tr>
		<?php } ?>
		</tbody>
	</table>
<?php } ?>

	</div>
<?php } ?>
</div>
<?php
// フッタメニュー
echo $this->render( 'member/footer_menu.php' );

// 共通ページフッタ
echo $this->render( 'member/page_footer.php' );
?>
</body>
</html>
