<?php

use Coral\Coral\View\CoralViewCommandBar;
use Coral\Coral\View\CommandBar\CoralViewCommandBarButton;

// HTMLヘッダ
echo $this->render( 'member/document_header.php' );

// アプリケーション名割り当て
$this->applicationTitle = '後払い決済管理システム';

?>
</head>
<body>
<?php
// 共通ページヘッダ
echo $this->render( 'member/page_header.php' );
// ヘッダのメニュー
echo $this->render( 'member/header_menu.php' );

// システムメッセージ
echo $this->render( 'member/system_message.php' );

// ページタイトル
echo $this->render( 'member/page_title.php' );
?>

<div class="main_contents">
<?php
// コマンドバー使用
$commandBar = new CoralViewCommandBar(
    // title
    '伝票登録用のCSVファイルをアップロードします',
    // buttons
    array(
        new CoralViewCommandBarButton(
            array(
                CoralViewCommandBarButton::OPTION_ID => 'linkToRegist',
                CoralViewCommandBarButton::OPTION_HREF => 'shipping/regist',
                CoralViewCommandBarButton::OPTION_TEXT => '個別登録',
                CoralViewCommandBarButton::OPTION_TITLE => 'ブラウザから個別登録する場合はこちらから'
            )
        )
    )
);

// コマンドバーのレンダリング
echo $commandBar->render();
?>
    <center>
        <form id="csv_form" method="post" action="shipping/confirmCsv" enctype="multipart/form-data">

            <table class="regist_table" id="csv_form_table" border="yes" cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <th>CSVファイルの登録</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="file_item">
                            <input id="csv_file" name="<?php echo $this->field_name; ?>" type="file" size="60" />
                        </td>
                    </tr>
                    <tr>
                        <td class="submit_item">
                            <button id="csv_submit" type="submit">登録実行</button>
                        </td>
                    </tr>
                </tbody>
            </table>

        </form>
    </center>
</div>

<?php
// フッタメニュー
echo $this->render( 'member/footer_menu.php' );

// 共通ページフッタ
echo $this->render( 'member/page_footer.php' );
?>
</body>

</html>

