<?php
// HTMLヘッダ
echo $this->render( 'mypage/document_header_sp.php' );

// アプリケーション名割り当て
$this->applicationTitle = '顧客マイページ';

$fd = $this->data;
?>
</head>
<body>
<div id="wrapper">
<?php
// 共通ページヘッダ
echo $this->render( 'mypage/page_header_sp.php' );

// システムメッセージ
echo $this->render( 'mypage/system_message_sp.php' );

?>
<!-- start contents -->
<div id="contents">
    <div style="clear: both;" id="my_title">会員情報変更確認</div>
    <table style="float: left;" class="datatable" width="96%" cellpadding="1" cellspacing="1" border="0">
    <tbody>
        <tr>
            <td class="member_info">会員ID（メールアドレス）</td>
        <tr/>
        <tr>
            <td class="data"><?php echo f_e( $fd['MailAddress'] ); ?></td>
        </tr>
        <tr>
            <td class="member_info">パスワード</td>
        <tr/>
        <tr>
            <td class="data"><?php for( $i = 0; $i < $fd['LoginPasswd']; $i++ ) { echo '*'; } ?>　</td>
        </tr>
        <tr>
            <td class="member_info2">名前</td>
        <tr/>
        <tr>
            <td class="data"><span style="font-weight: bold">姓</span>　　<?php echo f_e( $fd['NameSeiKj'] ); ?>　　<span style="font-weight: bold">名</span>　　<?php echo f_e( $fd['NameMeiKj'] ); ?></td>
        </tr>
        <tr>
            <td class="member_info2">フリガナ</td>
        <tr/>
        <tr>
            <td class="data"><span style="font-weight: bold">セイ</span>　<?php echo f_e( $fd['NameSeiKn'] ); ?>　　<span style="font-weight: bold">メイ</span>　<?php echo f_e( $fd['NameMeiKn'] ); ?></td>
        </tr>
        <tr>
            <td class="member_info2">性別</td>
        <tr/>
        <tr>
            <td class="data"><?php if( $fd['Sex'] == 1 ) { echo '男'; } else if( $fd['Sex'] == 2 ) { echo '女'; } ?></td>
        </tr>
        <tr>
            <td class="member_info2">生年月日</td>
        <tr/>
        <tr>
            <td class="data"><span style="font-weight: bold">西暦</span>　<?php echo f_e( $fd['Birthday_y'] ); ?>　<span style="font-weight: bold">年</span>　<?php echo f_e( $fd['Birthday_m'] ); ?>　<span style="font-weight: bold">月</span>　<?php echo f_e( $fd['Birthday_d'] ); ?>　<span style="font-weight: bold">日</span></td>
        </tr>
        <tr>
            <td class="member_info2">郵便番号</td>
        <tr/>
        <tr>
            <td class="data"><?php echo f_e( $fd['PostalCode_1'] ); ?>　-　<?php echo f_e( $fd['PostalCode_2'] ); ?></td>
        </tr>
        <tr>
            <td class="member_info2">都道府県</td>
        <tr/>
        <tr>
            <td class="data"><?php echo f_e( $fd['PrefectureName'] ); ?></td>
        </tr>
        <tr>
            <td class="member_info2">住所</td>
        <tr/>
        <tr>
            <td class="data"><?php echo f_e( $fd['Address'] ); ?></td>
        </tr>
        <tr>
            <td class="member_info2">建物名・部屋番号</td>
        <tr/>
        <tr>
            <td class="data"><?php echo f_e( $fd['Building'] ); ?>　</td>
        </tr>
        <tr>
            <td class="member_info2">電話番号</td>
        <tr/>
        <tr>
        <!-- <td class="data"><?php echo f_e( $fd['Phone_1'] ); ?>　-　<?php echo f_e( $fd['Phone_2'] ); ?>　-　<?php echo f_e( $fd['Phone_3'] ); ?></td> -->
            <td class="data"><?php if ( strlen( $fd['Phone_1'] ) ) { echo f_e( $fd['Phone_1'] ) . '　-　' . f_e( $fd['Phone_2'] ) .'　-　' . f_e( $fd['Phone_3'] ); } ?></td>
        </tr>
        <tr>
            <td class="member_info2">電話番号(携帯）</td>
        <tr/>
        <tr>
        <!-- <td class="data"><?php echo f_e( $fd['MobilePhone_1'] ); ?>　-　<?php echo f_e( $fd['MobilePhone_2'] ); ?>　-　<?php echo f_e( $fd['MobilePhone_3'] ); ?></td> -->
            <td class="data"><?php if ( strlen( $fd['MobilePhone_1'] ) ) { echo f_e( $fd['MobilePhone_1'] ) . '　-　' . f_e( $fd['MobilePhone_2'] ) .'　-　' . f_e( $fd['MobilePhone_3'] ); } ?></td>
        </tr>
        <tr class="data">
            <form id="saveForm" action="edit/save" method="post">
            <input name="hash" type="hidden" value="<?php echo f_e( $this->encoded_data ); ?>" />
            <td colspan="2" align="center">
                <input id="red_btn" type="submit" value="確定" onclick="document.forms.saveForm.action='edit/save'" />
                <input id="green_btn" type="submit" value="取消" onclick="document.forms.saveForm.action='edit/back'" />
            </td>
            </form>
        </tr>
    </tbody>
    </table>

    <?php
        echo $this->render( 'mypage/menu_sp.php' );
    ?>
</div>
<!-- end contents -->
<?php
// 共通ページフッタ
echo $this->render( 'mypage/page_footer_sp.php' );
?>

</div>
</body>
</html>
