<?php
// HTMLヘッダ
echo $this->render( 'mypage/document_header_sp.php' );

// アプリケーション名割り当て
$this->applicationTitle = '顧客マイページ';
?>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new
Date();a=s.createElement(o),

m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71083479-1', 'auto');
  ga('send', 'pageview');
</script>
</head>
<body>
<div id="wrapper">
<?php
// 共通ページヘッダ
echo $this->render( 'mypage/login/page_header_sp.php' );

// システムメッセージ
echo $this->render( 'mypage/system_message_sp.php' );

?>
<!-- start contents -->
<?php if(isset($this->yearMessage))echo $this->yearMessage;?>
<div id="contents">
<div id="login_area">
    <h5>ログイン</h5>
    <h6>■ 会員の方</h6>
    <form name="login_form" method="post" action="login/auth">
    <table width="300px">
        <tr>
            <td class="l_area">会員ID（メールアドレス）</td>
        </tr>
        <tr>
            <td class="l_area"><input id="login_id" name="login_id" type="text" size="33" style="height:20px"/></td>
        </tr>
        <tr>
            <td class="l_area" style="padding-top: 10px; padding-bottom: 10px">パスワード</td>
        </tr>
        <tr>
            <td class="l_area"><input id="password" name="password" type="password" size="33" style="height:20px" /></td>
        </tr>
        <tr>
            <td colspan="2" class="c_area" style="padding: 10px 0px 10px 0px"><input name="autologin" type="checkbox" class="chkrd_info" value="1"<?php if( $this->autologin ) echo ' checked="checked"'; ?> />次回から自動ログイン</td>
        </tr>
        <?php if( !empty( $this->loginMessages ) ){ ?>
        <?php foreach( array_reverse( $this->loginMessages ) as $message ) { ?>
        <tr>
            <td style="color:red; padding-left:8%"><?php echo $message; ?></td>
        </tr>
        <?php } ?>
        <?php } ?>
        <?php if (isset($this->isAccountLock)) { ?>
        <tr>
            <td colspan="2" align="center"><font color="red">
            <?php
                echo "ログイン エラー回数が規定回数を超えました。 <br>";
                echo "セキュリティ保護のため、ログインを制限しています。<br>";
                echo "制限を解除するためには、お手数ですがサポート<br>";
                echo "センターまでお電話にてお問い合わせください。<br>";
                echo "サポートセンター電話番号： <br>";
                echo "TEL: 0120-667-690（10:00 ～ 18:00）";
            ?>
            </font>
            </td>
        </tr>
        <?php } ?>
        <tr>
            <td colspan="2" align="center"><input id="goto_button" type="submit" value="ログイン" /></td>
        </tr>
    </table>
    </form>
    <table width="100%" style="float: left;">
        <tr>
            <td class="l_area" style="font-size: 12px"><a href="login/reissue" target="_blank"><span id="l_pws">◇ パスワードを忘れた方　　　　</span></a></td>
        </tr>
    </table>
    <h6>■ 会員登録がお済みでない方</h6>
    <table width="300px">
        <tr>
            <td colspan="2" align="center"><input type="button" id="goto_button" onclick="window.open('regist/preregist')" value="新規会員登録" /></td>
        </tr>
    </table>
</div>
</div>
<!-- end contents -->
<?php
// 共通ページフッタ
echo $this->render( 'mypage/page_footer_sp.php' );
?>

</div>
</body>
</html>

