<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<style>
  a.download_link {
    padding: 8px;
    padding-left: 25px;
    background-image: url('../images/icon_download_s.gif');
    background-repeat: no-repeat;
    background-position: 8px center;
    font-size: 12px;
  }
  a.download_link,
  a.download_link:link,
  a.download_link:hover,
  a.download_link:active,
  a.download_link:visited {
    border: solid 1px silver;
    background-color: transparent;
    color: royalblue;
  }
  a.download_link:hover {
    background-color: azure;
    border-color: gray;
    color: blue;
  }

</style>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/customeradrslist/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">顧客統合 名寄せリスト</h3>
    <div class="page_nav" style="border-style: none; margin-top: 0px;">
      <span class="pager"><a class="download_link" href="customeradrslist/dcsv">一覧をCSVダウンロード</a></span>
    </div>
    <h4>該当件数　<?php echo $this->listCnt; ?> 件</h4>
    <table width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
      <tbody>
        <tr>
          <th>管理顧客番号</th>
          <th>氏名</th>
          <th>氏名カナ</th>
          <th>住所</th>
          <th>電話番号</th>
          <th>メールアドレス</th>
          <th>類似顧客</th>
          <th>統合指示</th>
        </tr>
        <?php foreach ($this->list as $row) { ?>
        <tr class="data">
          <td class="l_data"><?php echo $row['ManCustId']; ?></td>
          <td class="l_data"><a href="unifiinstr/unifiinstr/combinedlistid/<?php echo $row['CombinedListId']; ?>"><?php echo $row['NameKj']; ?></a></td>
          <td class="l_data"><?php echo $row['NameKn']; ?></td>
          <td class="l_data"><?php echo $row['UnitingAddress']; ?></td>
          <td class="l_data"><?php echo $row['Phone']; ?></td>
          <td class="l_data"><?php echo $row['MailAddress']; ?></td>
          <td class="l_data"><?php echo $row['Likeness']; ?>件</td>
          <td class="c_data"><?php if ($row['CombinedDictate'] >= 1) echo '済'; else echo '未'; ?></td>
        </tr>
        <?php } ?>
        <tr class="border">
          <td colspan="8">
            <img src="../images/spacer_gray.gif" height="1" width="1">
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
