<?php
// HTMLヘッダ
echo $this->render( 'orderpage/document_header.php' );

// アプリケーション名割り当て
$this->applicationTitle = '注文マイページ';
?>
</head>
<body>
<div id="wrapper">
<?php
// 共通ページヘッダ
echo $this->render( 'orderpage/login/page_header.php' );

// システムメッセージ
echo $this->render( 'orderpage/system_message.php' );

?>
<!-- start contents -->
<div id="contents">
<div id="login_area">
    <h5>注文情報確認ページ:(期限切れ)</h5>
    <?php echo $this->Note; ?>
</div>
</div>
<!-- end contents -->
<?php
// 共通ページフッタ
echo $this->render( 'orderpage/page_footer.php' );
?>

</div>
</body>
</html>

