<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/rwcredit/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <?php if (isset($this->error)) { ?>
    <h3 class="contents_title">社内与信確定（エラー）</h3>
      <table width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
          <td class="l_label" style="color: #ff0000">
          <?php foreach ($this->error as $row) { ?>
          <?php echo $row; ?><br>
          <?php } ?>
          </td>
          </tr>
        </tbody>
      </table>
    <?php } else { ?>
    <h3 class="contents_title">社内与信確定</h3>
      <table width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
            <td class="c_label">OK</td>
            <td class="c_data"><?php echo $this->okCnt; ?> 件</td>
          </tr>
          <tr>
            <td class="c_label">NG</td>
            <td class="c_data"><?php echo $this->ngCnt; ?> 件</td>
          </tr>
          <tr>
            <td class="c_label">保留</td>
            <td class="c_data"><?php echo $this->hoCnt; ?> 件</td>
          </tr>
        </tbody>
      </table>
    <?php } ?>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
