<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<style type="text/css">
#message-container {
    color: #f00;
}
</style>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/rwarvldata/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">配ポンインポートファイル出力</h3>
    <div style="margin: 5px 25px; margin-bottom: 80px;">
        <div id="message-container">ダウンロード要求中にエラーが発生しました。もう一度やり直してください。</div>
    </div>
  </div>
  <!-- end contents -->
  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
