<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<script type="text/javascript">
Event.observe(window, 'load', function() {
    setTimeout(function() {
        $('export-form').submit();
    }, 0);
    setTimeout(function() {
        Element.show($('backto-container'));
    }, 1000 * 60 * 2);
});
</script>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/rwarvldata/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">着荷確認データインポートファイル出力</h3>
    <div style="margin: 5px 25px; margin-bottom: 80px;">
        <div id="message-container">
            ファイルをダウンロードしています。しばらくお待ちください。<br />
            <span style="color: #f00; font-weight: bold">※：ファイルダウンロード完了前にページを移動すると、ファイルのダウンロードが完了しないので注意してください！！</span>
        </div>
        <div id="backto-container" style="display: none">
            <a href="rwarvldata/index">着荷確認データ連携 トップへ</a>
        </div>
        <form id="export-form" method="post" action="rwarvldata/export" style="display: none">
            <input type="hidden" name="mode" value="download" />
            <input type="hidden" name="exp-params" value="<?php echo f_e($this->params); ?>" />
        </form>
    </div>
  </div>
  <!-- end contents -->
  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
