<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
$info = $this->total_counts;
?>
<?php echo $this->render('cbadmin/rwarvldata/styles.php'); ?>
<script type="text/javascript">
Event.observe(window, 'load', function() {
    setTimeout(function() {
        $('redirect-form').submit();
    }, 250);
});
</script>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">インポート完了中</h3>
    <div style="margin: 5px 25px">
    しばらくお待ちください...
    </div>
    <form id="redirect-form" action="rwarvldata/impdone" method="post">
        <input type="hidden" name="total_counts[imported]" value="<?php echo f_e($info['imported']); ?>" />
        <input type="hidden" name="total_counts[processed]" value="<?php echo f_e($info['processed']); ?>" />
        <input type="hidden" name="total_counts[total]" value="<?php echo f_e($info['total']); ?>" />
    </form>
  </div>
  <!-- end contents -->
  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
