<?php
// HTMLヘッダ
echo $this->render( 'oemmypage/document_header_sp.php' );

// アプリケーション名割り当て
$this->applicationTitle = '顧客マイページ';

$fd = $this->data;

function show_error_message( $messages , $id = '' ) {
    if( empty( $messages ) ) return;
    if( ! is_array( $messages ) ) $messages = array( $messages );
    $list = array();
    foreach( $messages as $msg ) $list[] = f_e( $msg );
    if (!empty($id)) {
        echo '<div class="input_error_message" id="' . $id . '">';
    }
    else {
        echo '<div class="input_error_message">';
    }
    echo join('<br />', $list);
    echo '</div>';
}
?>
<script>
function getAddress(zip)
{
    var url = '<?php echo $this->baseUrl . '/edit/searchzip' ?>?zc=' + zip;

    var ajax = new Ajax.Request(
        url,
        {
            method: 'GET',
            onComplete: setAddress
        }
    );
}

function setAddress(orgReq)
{
    var jsonObj = eval('(' + orgReq.responseText + ')');

    $('PrefectureCode').selectedIndex = jsonObj["PrefectureCode"];
    $('Address').value = jsonObj["CityKanji"] + jsonObj["TownKanji"];

    if (jsonObj["ErrorMessage"] != "") {
        $('PostErrordiv').style.display = "";
        $('PostErrordiv').innerHTML = jsonObj["ErrorMessage"];
    }
    else {
        $('PostErrordiv').style.display = "none";
        $('PostErrordiv').innerHTML = "";
    }
}

function toFullWidth(element) {
	var str = element.value;
	var Kana1 = new Array("ｶﾞ", "ｷﾞ", "ｸﾞ", "ｹﾞ", "ｺﾞ","ｻﾞ", "ｼﾞ", "ｽﾞ", "ｾﾞ", "ｿﾞ",
			"ﾀﾞ", "ﾁﾞ", "ﾂﾞ", "ﾃﾞ", "ﾄﾞ","ﾊﾞ", "ﾋﾞ", "ﾌﾞ", "ﾍﾞ", "ﾎﾞ","ﾊﾟ", "ﾋﾟ", "ﾌﾟ", "ﾍﾟ", "ﾎﾟ", "ｳﾞ",
			"ｱ", "ｲ", "ｳ", "ｴ", "ｵ","ｶ", "ｷ", "ｸ", "ｹ", "ｺ","ｻ", "ｼ", "ｽ", "ｾ", "ｿ",
			"ﾀ", "ﾁ", "ﾂ", "ﾃ", "ﾄ","ﾅ", "ﾆ", "ﾇ", "ﾈ", "ﾉ","ﾊ", "ﾋ", "ﾌ", "ﾍ", "ﾎ",
			"ﾏ", "ﾐ", "ﾑ", "ﾒ", "ﾓ","ﾔ", "ﾕ", "ﾖ","ﾗ", "ﾘ", "ﾙ", "ﾚ", "ﾛ","ﾜ", "ｦ", "ﾝ",
			"ｧ", "ｨ", "ｩ", "ｪ", "ｫ","ｯ", "ｬ", "ｭ", "ｮ", "ｰ","｡", "､", "｢", "｣", "･");
	var Kana2 = new Array("ガ", "ギ", "グ", "ゲ", "ゴ", "ザ", "ジ", "ズ", "ゼ", "ゾ",
			"ダ", "ヂ", "ヅ", "デ", "ド","バ", "ビ", "ブ", "ベ", "ボ", "パ", "ピ", "プ", "ペ", "ポ", "ヴ",
			"ア", "イ", "ウ", "エ", "オ", "カ", "キ", "ク", "ケ", "コ", "サ", "シ", "ス", "セ", "ソ",
			"タ", "チ", "ツ", "テ", "ト", "ナ", "ニ", "ヌ", "ネ", "ノ", "ハ", "ヒ", "フ", "ヘ", "ホ",
			"マ", "ミ", "ム", "メ", "モ", "ヤ", "ユ", "ヨ", "ラ", "リ", "ル", "レ", "ロ", "ワ", "ヲ", "ン",
			"ァ", "ィ", "ゥ", "ェ", "ォ", "ッ", "ャ", "ュ", "ョ", "ー", "。", "、", "「", "」", "・");
	while(str.match(/[ｦ-ﾝ｡､｢｣･]/)){
		for(var i = 0; i < Kana1.length; i++){
			str = str.replace(Kana1[i], Kana2[i]);
		}
	}
	while(str.match(/[A-Za-z0-9-!#$%&()<>,.?_\[\]{}+*@^~/\\|]/)){
		str = str.replace( /[A-Za-z0-9-!#$%&()<>,.?_\[\]{}+*@^~/\\|]/g, function(s) {
			return String.fromCharCode(s.charCodeAt(0) + 0xFEE0);
		});
	}
	str = str.replace(/'/g, "’");
	str = str.replace(/"/g, "”");
	str = str.replace(/ /g, "　");
	return element.value = str;
}

window.onload = function(){
	toFullWidth(NameSeiKj);
	toFullWidth(NameMeiKj);
	toFullWidth(NameSeiKn);
	toFullWidth(NameSeiKn);
	toFullWidth(Address);
	toFullWidth(Building);
}
</script>
<style>
.input_error_message {
    color: red;
}
</style>
</head>
<body>
<div id="wrapper">
<?php
// 共通ページヘッダ
echo $this->render( 'oemmypage/page_header_sp.php' );

// システムメッセージ
echo $this->render( 'oemmypage/system_message_sp.php' );

?>
<!-- start contents -->
<div id="contents">
    <div style="clear: both;" id="my_title">会員登録情報変更</div>
    <?php if( !empty( $this->error ) ) { ?>
    <div id="errmsg">
        ※：入力に不備があります。登録内容を見直してください。
    </div>
    <?php } ?>
    <form name="form" method="post" action="edit/confirm">
        <table class="datatable" width="96%" cellpadding="1" cellspacing="1" border="0">
        <tbody>
            <tr>
                <td class="member_info">会員ID（メールアドレス）</td>
            <tr/>
            <tr>
                <td class="data"><input size="35" name="form[MailAddress]" type="hidden" id="MailAddress" value="<?php echo f_e( $fd['MailAddress'] ); ?>" />
                <?php echo f_e( $fd['MailAddress'] ); ?>
                </td>
            </tr>
            <tr>
                <td class="member_info">パスワード</td>
            <tr/>
            <tr>
                <td class="data">********　　<a href="edit/passchg" target="_blank">変更</a>
            </td>
            </tr>
            <tr>
                <td class="member_info2">名前<font color="red">　※必須</font>　　全角のみ</td>
            <tr/>
            <tr>
                <td class="data"><span class="f_bold">姓</span>　　<input  size="8" name="form[NameSeiKj]" type="text" id="NameSeiKj" value="<?php echo f_e( $fd['NameSeiKj'] ); ?>" onblur="toFullWidth(this)" />
                <span class="f_bold">名</span>　　<input  size="8" name="form[NameMeiKj]" type="text" id="NameMeiKj" value="<?php echo f_e( $fd['NameMeiKj'] ); ?>" onblur="toFullWidth(this)" />
                <?php show_error_message( $this->error['NameSeiKj'] );?>
                <?php show_error_message( $this->error['NameMeiKj'] );?></td>
            </tr>
            <tr>
                <td class="member_info2">フリガナ<font color="red">　※必須</font>　　全角のみ</td>
            <tr/>
            <tr>
                <td class="data"><span class="f_bold">セイ</span>　<input size="8" name="form[NameSeiKn]" type="text" id="NameSeiKn" value="<?php echo f_e( $fd['NameSeiKn'] ); ?>" onblur="toFullWidth(this)" />
                <span class="f_bold">メイ</span>　<input size="8" name="form[NameMeiKn]" type="text" id="NameMeiKn" value="<?php echo f_e( $fd['NameMeiKn'] ); ?>" onblur="toFullWidth(this)" />
                <?php show_error_message( $this->error['NameSeiKn'] );?>
                <?php show_error_message( $this->error['NameMeiKn'] );?></td>
            </tr>
            <tr>
                <td class="member_info2">性別<font color="red">　※必須</font></td>
            <tr/>
            <tr>
                <td class="data">男　<input name="form[Sex]" id="Sex" type="radio" value="1"<?php if( $fd['Sex'] == 1 ) { echo ' checked="checked"'; } ?> />
                女　<input name="form[Sex]" id="Sex" type="radio" value="2"<?php if( $fd['Sex'] == 2 ) { echo ' checked="checked"'; } ?> />
                <?php show_error_message( $this->error['Sex'] ); ?></td>
            </tr>
            <tr>
                <td class="member_info2">生年月日<font color="red">　※必須</font></td>
            <tr/>
            <tr>
                <td class="data"><span class="f_bold">西暦</span>　<select id="Birthday_y" name="form[Birthday_y]" value="<?php echo f_e( $fd['Birthday_y'] ); ?>">
                <?php for( $i = 1900; $i <= date('Y'); $i++ ) { ?>
                <?php $selected = $fd['Birthday_y'] == $i ? ' selected="selected"' : ''; ?>
                <option value="<?php echo f_e( $i ); ?>"<?php echo $selected; ?>><?php echo f_e( $i ) . "</option>\r\n"; } ?></select>　<span class="f_bold">年</span>
                <select id="Birthday_m" name="form[Birthday_m]" value="<?php echo sprintf( "%02d", $fd['Birthday_m'] ); ?>">
                <?php for( $i = 1; $i <= 12; $i++ ) { ?>
                <?php $selected = (int)$fd['Birthday_m'] == $i ? ' selected="selected"' : ''; ?>
                <option value="<?php echo sprintf( "%02d", $i ); ?>"<?php echo $selected; ?>><?php echo sprintf( "%02d", $i ) . "</option>\r\n"; } ?></select>　<span class="f_bold">月</span>
                <select id="Birthday_d" name="form[Birthday_d]" value="<?php echo sprintf( "%02d", $fd['Birthday_d'] ); ?>">
                <?php for( $i = 1; $i <= 31; $i++ ) { ?>
                <?php $selected = (int)$fd['Birthday_d'] == $i ? ' selected="selected"' : ''; ?>
                <option value="<?php echo sprintf( "%02d", $i ); ?>"<?php echo $selected; ?>><?php echo sprintf( "%02d", $i ) . "</option>\r\n"; } ?></select>　<span class="f_bold">日</span>
                <?php show_error_message( $this->error['Birthday'] ); ?></td>
            </tr>
            <tr>
                <td class="member_info2">郵便番号<font color="red">　※必須</font>　　半角数字のみ</td>
            <tr/>
            <tr>
                <td class="data"><input size="3" name="form[PostalCode_1]" type="tel" id="PostalCode_1" value="<?php echo f_e( $fd['PostalCode_1'] ); ?>" />
                　-　<input size="3" name="form[PostalCode_2]" type="tel" id="PostalCode_2" value="<?php echo f_e( $fd['PostalCode_2'] ); ?>" />
                <input type="button" value="住所検索" onClick="getAddress( $('PostalCode_1').value + $('PostalCode_2').value );" />　<a href="http://www.post.japanpost.jp/zipcode" target="_blank">郵便番号照会</a>
                <?php show_error_message( $this->error['PostalCode'] , 'PostErrordiv' ); ?>
                <?php if (empty($this->error['PostalCode'])) { ?>
                <div class="input_error_message" style="display: none;" id="PostErrordiv" name="PostErrordiv"></div>
                <?php } ?>
                </td>
            </tr>
            <tr>
                <td class="member_info2">都道府県<font color="red">　※必須</font></td>
            <tr/>
            <tr>
                <td class="data"><select id="PrefectureCode" name="form[PrefectureCode]" value="<?php echo f_e( $fd['PrefectureCode'] ); ?>">
                <?php foreach( $this->prefecture as $value => $caption ) { ?>
                <?php $selected = $fd['PrefectureCode'] == $value ? ' selected="selected"' : ''; ?>
                <option value="<?php echo f_e( $value ); ?>"<?php echo $selected; ?>><?php echo f_e( $caption ) . "</option>\r\n"; ?>
                <?php } ?></select>
                <?php show_error_message( $this->error['PrefectureCode'] ); ?></td>
            </tr>
            <tr>
                <td class="member_info2">住所<font color="red">　※必須</font>　　全角のみ</td>
            <tr/>
            <tr>
                <td class="data"><input size="35" name="form[Address]" type="text" id="Address" value="<?php echo f_e( $fd['Address'] ); ?>" onblur="toFullWidth(this)" />
                <?php show_error_message( $this->error['Address'] ); ?></td>
            </tr>
            <tr>
                <td class="member_info2">建物名・部屋番号　　全角のみ</td>
            <tr/>
            <tr>
                <td class="data"><input size="35" name="form[Building]" type="text" id="Building" value="<?php echo f_e( $fd['Building'] ); ?>" onblur="toFullWidth(this)" />
                <?php show_error_message( $this->error['Building'] ); ?></td>
            </tr>
            <tr>
                <td class="member_info2">電話番号<font color="red">　※いずれか必須</font>　　半角数字のみ</td>
            <tr/>
            <tr>
                <td class="data"><input size="3" name="form[Phone_1]" type="tel" id="Phone_1" value="<?php echo f_e( $fd['Phone_1'] ); ?>" />
                　-　<input size="3" name="form[Phone_2]" type="tel" id="Phone_2" value="<?php echo f_e( $fd['Phone_2'] ); ?>" />
                　-　<input size="3" name="form[Phone_3]" type="tel" id="Phone_3" value="<?php echo f_e( $fd['Phone_3'] ); ?>" />
                <?php show_error_message($this->error['Phone']); ?></td>
            </tr>
            <tr>
                <td class="member_info2">電話番号(携帯）<font color="red">　※いずれか必須</font>　　半角数字のみ</td>
            <tr/>
            <tr>
                <td class="data"><input size="3" name="form[MobilePhone_1]" type="tel" id="MobilePhone_1" value="<?php echo f_e( $fd['MobilePhone_1'] ); ?>" />
                　-　<input size="3" name="form[MobilePhone_2]" type="tel" id="MobilePhone_2" value="<?php echo f_e( $fd['MobilePhone_2'] ); ?>" />
                　-　<input size="3" name="form[MobilePhone_3]" type="tel" id="MobilePhone_3" value="<?php echo f_e( $fd['MobilePhone_3'] ); ?>" />
                <?php show_error_message( $this->error['MobilePhone'] ); ?></td>
            </tr>
            <tr class="data"><td colspan="2" align="center"><input id="red_btn" type="submit" value="変更" /></td></tr>
        </tbody>
        </table>
    </form>

    <?php
        echo $this->render( 'oemmypage/menu_sp.php' );
    ?>
</div>
<!-- end contents -->
<?php
// 共通ページフッタ
echo $this->render( 'oemmypage/page_footer_sp.php' );
?>

</div>
</body>
</html>
