<?php
$summary_templates = array(
        'UseAmount' => 0,
        'SettlementFee' => 0,
        'ClaimFee' => 0,
        'StampFee' => 0,
        'sagaku' => 0,
);
$summaries = array_merge(array(), $summary_templates);

// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/monthly/page_menu2.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">月次明細（お取引明細）</h3>
    <!--
    <div style="clear:both;">
      <div id="lbl1">
      </div>
      <div id="cmd1"></div>
    </div>
    -->
    <form name="form">
      <table width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
            <td class="l_data">
              <?php echo $this->dataInformation; ?>
            </td>
          </tr>
        </tbody>
      </table>
    </form>
    <!-- count関数対策 -->
<?php if(empty($this->list)) { ?>
	　　　明細はありません。
<?php } else { ?>
<?php
$item_count = 0;
foreach($this->list as $key => $value) {
  // count関数対策
  if (!empty($value)){	
    $item_count += count($value);	
  }	
};

$last_sitename = array_pop(array_keys($this->list));
$i = 0;
foreach($this->list as $sitename => $rows) {
	$_summaries = array_merge(array(), $summary_templates);
?>
      <table style="clear:both;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <thead>
          <tr>
            <th style="width: 30px">No</th>
            <th style="width: 80px">注文ID</th>
            <th style="width: 80px">任意注文番号</th>
            <th style="width: 100px">購入者</th>
            <th style="width: 70px">注文日</th>
            <th style="width: 70px">伝登日</th>
            <th style="width: 70px">立替締</th>
            <th style="width: 85px">請求額</th>
            <th style="width: 60px">決済<br />手数料</th>
            <th style="width: 60px">請求<br />手数料</th>
            <th style="width: 50px">印紙<br />代金</th>
            <th style="width: 85px">差引後<br />金額</th>
          </tr>
        </thead>
        <tbody>
<?php   foreach($rows as $row) { ?>
          <tr>
            <td class="seq_col c_data"><?php echo (++$i); ?></td>
            <td class="c_data"><?php echo f_e($row['OrderId']); ?></td>
            <td class="c_data"><?php echo f_e(nvl($row['Ent_OrderId'], '-')); ?></td>
            <td class="l_data"><?php echo f_e($row['NameKj']); ?></td>
            <td class="date_col c_data"><?php echo date('Y/m/d', strtotime($row['ReceiptOrderDate'])); ?></td>
            <td class="date_col c_data"><?php echo date('Y/m/d', strtotime($row['MaxDeliJournalIncDate'])); ?></td>
            <td class="date_col c_data"><?php echo date('Y/m/d', strtotime($row['FixedDate'])); ?></td>
            <td class="money_col r_data"><?php echo nvl(number_format($row['UseAmount']), '&nbsp;'); ?></td>
            <td class="money_col r_data"><?php echo nvl(number_format($row['SettlementFee']), '&nbsp;'); ?></td>
            <td class="money_col r_data"><?php echo nvl(number_format($row['ClaimFee']), '&nbsp;'); ?></td>
            <td class="money_col r_data"><?php echo nvl(number_format($row['StampFee']), '&nbsp;'); ?></td>
            <td class="money_col r_data"><?php echo nvl(number_format($row['sagaku']), '&nbsp;'); ?></td>
          </tr>
<?php
            foreach( array_keys( $summaries ) as $key ) {
                $summaries[$key] = ((int)$summaries[$key]) + ((int)$row[$key]);
                $_summaries[$key] = ((int)$_summaries[$key]) + ((int)$row[$key]);
            }
        }
        $style = $sitename == $last_sitename ? ' style="border-bottom-style: double; border-bottom-width: 3px;"' : '';
?>
          <tr class="summary">
            <td class="r_data" colspan="7"<?php echo $style; ?>>サイト計<?php echo '（' . $sitename . '）'; ?></td>
            <td class="money_col total_col r_data"<?php echo $style; ?>><?php echo f_nf((int)$_summaries['UseAmount'], '\ #,##0'); ?></td>
            <td class="money_col total_col r_data"<?php echo $style; ?>><?php echo f_nf((int)$_summaries['SettlementFee'], '\ #,##0'); ?></td>
            <td class="money_col total_col r_data"<?php echo $style; ?>><?php echo f_nf((int)$_summaries['ClaimFee'], '\ #,##0'); ?></td>
            <td class="money_col total_col r_data"<?php echo $style; ?>><?php echo f_nf((int)$_summaries['StampFee'], '\ #,##0'); ?></td>
            <td class="money_col total_col r_data"<?php echo $style; ?>><?php echo f_nf((int)$_summaries['sagaku'], '\ #,##0'); ?></td>
          </tr>

<?php   if( $sitename == $last_sitename ) { ?>
          <tr class="summary">
            <td class="seq_col r_data" colspan="7">お取引先計</td>
            <td class="money_col total_col r_data"><?php echo f_nf((int)$summaries['UseAmount'], '\ #,##0'); ?></td>
            <td class="money_col total_col r_data"><?php echo f_nf((int)$summaries['SettlementFee'], '\ #,##0'); ?></td>
            <td class="money_col total_col r_data"><?php echo f_nf((int)$summaries['ClaimFee'], '\ #,##0'); ?></td>
            <td class="money_col total_col r_data"><?php echo f_nf((int)$summaries['StampFee'], '\ #,##0'); ?></td>
            <td class="money_col total_col r_data"><?php echo f_nf((int)$summaries['sagaku'], '\ #,##0'); ?></td>
          </tr>
<?php   } ?>
        </tbody>
      </table>
<?php
    }
}
?>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
