    <table width="400" border="0" cellspacing="0" cellpadding="2">
      <tr>
        <td colspan="2" bgcolor="#FF99CC"><span class="style10">管理機能（管理者のみ使用可）</span></td>
      </tr>
      <tr>
        <td width="60" align="center" valign="middle"><img src="../images/icon_administration.gif"></td>
        <td align="left">■<a href="operator/chgpw">パスワード変更</a></td>
      </tr>
    </table>
    