<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>


      <table border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="138" rowspan="2"><img src="../images/Normal_operation_01.gif" alt="通常処理" width="138" height="27" /></td>
          <td colspan="5" valign="bottom">&nbsp;</td>
        </tr>
        <tr>
          <td height="1" colspan="5" valign="bottom"><img src="../images/spacer_blue.gif" alt="青線" width="255" height="1" /></td>
        </tr>
        <tr>
          <td height="1" colspan="6">
            <table border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td align="center" valign="middle">&nbsp;</td>
                <td height="10" align="center" valign="middle">&nbsp;</td>
              </tr>
              <tr>
                <td width="134" height="80" align="center" valign="middle" background="../images/Blue_Arrow_03.gif">
                  <p>伝票番号登録<br />
                  <span class="style3">（<?php echo $this->highlight['rw31count']; ?>件）</span>
                  </p>
                </td>
                <td width="134" height="80" align="center" valign="middle" background="../images/Blue_Arrow_03.gif">
                  <p>
                  着荷確認<br />
                  <span class="style3">（<?php echo $this->highlight['rwarvlcount']; ?>件）</span>
                  </p>
                </td>
                <td width="134" height="80" align="center" valign="middle" background="../images/Blue_Arrow_03.gif">
                  入金確認<br />
                  <span class="style3">（<?php echo $this->highlight['rw51count']; ?>件）</span>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>


    <table style="margin-top:30px;" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="27"><img src="../images/Hilight_01.gif" alt="ハイライト" height="27" /></td>
        <td valign="bottom"><img src="../images/spacer_gray.gif" width="390" height="1" /></td>
      </tr>
      <tr>
        <td colspan="2" valign="top">
          <table border="0" cellpadding="0" cellspacing="1">
            <tr>
              <td width="100"><div align="center"></div></td>
              <td width="80"><div align="center" class="style6">本日</div></td>
              <td width="80"><div align="center" class="style6">前日</div></td>
              <td width="10">&nbsp;</td>
              <td width="100" align="left">&nbsp;</td>
              <td width="150">&nbsp;</td>
            </tr>
            <tr>
              <td width="100" align="right" bgcolor="#FFFFFF"><div align="left"><span class="style6">注文登録数</span></div></td>
              <td width="80" align="right" bgcolor="#FFFFFF"><?php echo $this->highlight['OrderCountToday']; ?> 件 </td>
              <td width="80" align="right" bgcolor="#FFFFFF"><?php echo $this->highlight['OrderCountYesterday']; ?> 件</td>
              <td width="10" align="right" bgcolor="#FFFFFF">&nbsp;</td>
              <td width="100" align="left" bgcolor="#FFFFFF"><span class="style6">登録時業者数</span>:                </td>
              <td width="150" align="right" bgcolor="#FFFFFF"><strong><?php echo $this->highlight['EnterpriseCount']; ?></strong></td>
            </tr>
            <tr>
              <td width="100" align="right" bgcolor="#FFFFFF"><div align="left"><span class="style6">売上</span></div></td>
              <td width="80" align="right" bgcolor="#FFFFFF"><?php echo $this->valueFormat($this->highlight['UriageToday'], 'number', '#,##0'); ?> 円</td>
              <td width="80" align="right" bgcolor="#FFFFFF"><?php echo $this->valueFormat($this->highlight['UriageYesterday'], 'number', '#,##0'); ?> 円</td>
              <td width="10" align="right" bgcolor="#FFFFFF">&nbsp;</td>
              <td width="100" align="left" bgcolor="#FFFFFF"><span class="style6">未入金額：</span></td>
              <td width="150" align="right" bgcolor="#FFFFFF"><span class="style7"><?php echo $this->valueFormat($this->highlight['Unpayment'], 'number', '#,##0'); ?> 円</span></td>
            </tr>
            <tr>
              <td width="100" align="right" bgcolor="#FFFFFF"><div align="left"><span class="style6">自動与信件数</span></div></td>
              <td width="80" align="right" bgcolor="#FFFFFF"><?php echo $this->highlight['CreditCountToday']; ?> 件 </td>
              <td width="80" align="right" bgcolor="#FFFFFF"><?php echo $this->highlight['CreditCountYesterday']; ?> 件</td>
              <td width="10" align="right" bgcolor="#FFFFFF">&nbsp;</td>
              <td width="100" align="left" bgcolor="#FFFFFF">&nbsp;</td>
              <td width="150" bgcolor="#FFFFFF">&nbsp;</td>
            </tr>
          </table>
        </td>
      </tr>
    </table>


</body>
</html>
