<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">オペレーター認証エラー</h3>
    <p>
        <?php echo f_e($this->errMessage); ?>
    </p>
    <?php if (isset($this->isAccountLock)) { ?>
        <div style="padding-left: 40px; padding-right: 40px; padding-top: 10px; padding-bottom: 15px;">
        <?php
            echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
            echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。<br><br>";
            echo "サポートセンター電話番号： TEL: 0120-667-690（10:00 ～ 18:00）";
        ?>
        </div>
    <?php } ?>
    <p>
        <a href="index/index">トップページ</a>
    </p>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
