<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/credit/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">「<?php echo $this->categoryName; ?>」　与信条件文言設定</h3>
    <div id="message" align="center"><?php echo $this->message; ?></div>
    <form name="form" method="post" action="credit/up">
      <table width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
            <th>条件Seq</th>
            <th>条件文字列</th>
            <th>ポイント</th>
            <th>有効</th>
          </tr>
          <?php $i = 0; foreach ($this->list as $row) { ?>
          <tr class="data">
            <td class="r_data">
              <input type="hidden" name="Seq<?php echo $i; ?>" id="Seq<?php echo $i; ?>" value="<?php echo $row->Seq; ?>" />
              <?php echo $row->Seq; ?>
            </td>
            <td class="l_data">
              <input type="text" size="80" name="Cstring<?php echo $i; ?>" id="Cstring<?php echo $i; ?>" value="<?php echo $row->Cstring; ?>" />
            </td>
            <td class="l_data">
              <input type="text" size="10" name="Point<?php echo $i; ?>" id="Point<?php echo $i; ?>" value="<?php echo $row->Point; ?>" />
            </td>
            <td class="c_data">
              <input type="checkbox" name="ValidFlg<?php echo $i; ?>" id="ValidFlg<?php echo $i; ?>" <?php if($row->ValidFlg == 1) echo 'checked'; ?> />
            </td>
          </tr>
          <tr class="border">
            <td colspan="3">
              <img src="../images/spacer_gray.gif" height="1" width="1">
            </td>
          </tr>
          <?php $i++; } ?>
          <tr class="data">
            <td class="c_data">新規</td>
            <td class="l_data"><input type="text" size="80" name="Cstring" id="Cstring" /></td>
            <td class="l_data"><input type="text" size="10" name="Point" id="Point" /></td>
            <td class="c_data"><input type="checkbox" name="ValidFlg" id="ValidFlg" checked /></td>
          </tr>
          <tr class="border">
            <td colspan="4">
              <img src="../images/spacer_gray.gif" height="1" width="1">
            </td>
          </tr>
          <tr>
            <td colspan="4" class="c_data">
              <input type="submit" value="　この内容で更新　" />　　　
              <!-- <input type="button" value="　戻る　" onClick="javascript:location.href='credit';" />-->
              <a href="credit/pointform">戻　る</a>
            </td>
          </tr>
        </tbody>
      </table>
    </form>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
