<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/credit/page_menu.php'); ?>

  <!-- start contents -->
 <?php $data = $this->expressions; ?>
  <div id="contents">
    <?php if ( f_e($this->EnterpriseId) == -1 || f_e($this->EnterpriseId) == '' ) { ?>
      <h3 class="contents_title">与信条件検索</h3>
    <?php } else { ?>
      <h3 class="contents_title">「<?php echo f_e($this->LoginId); ?>_<?php echo f_e($this->EnterpriseNameKj); ?>」の与信条件検索</h3>
    <?php } ?>
    <div id="message" align="center"><?php echo $this->message; ?></div>
    <?php if ( f_e($this->EnterpriseId) == -1 || f_e($this->EnterpriseId) == '' ) { ?>
    <form name="form" method="post" action="credit/result">
    <?php } else { ?>
    <form name="form" method="post" action="credit/result/eid/<?php echo f_e($this->EnterpriseId); ?>">
    <?php } ?>
      <table width="860" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <thead>
            <tr>
                <th>有効/無効</th>
                <th>項目種別</th>
                <th>条件文字列</th>
                <th>コメント</th>
                <th>ポイント</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="l_data">
                    <select id="credit_category" name="expressions[ValidFlg]">
                        <?php foreach($this->validFlgName as $key => $value) { ?>
                        <option value="<?php echo f_e($key); ?>"<?php if(!is_null($data['ValidFlg']) && $key == $data['ValidFlg']) echo ' selected="selected"'; ?>><?php echo f_e($value); ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td class="l_data">
                    <select id="credit_category" name="expressions[Category]">
                        <?php foreach($this->categoryName as $key => $row) { ?>
                          <?php if ( f_e($this->EnterpriseId) == -1 || f_e($this->EnterpriseId) == '' ) { ?>
                            <?php if($row['Code'] != 6 && $row['Code'] != 7){?>
                            <option value="<?php echo f_e($row['Code']); ?>"<?php if($row['Code'] == $data['Category']) echo ' selected="selected"'; ?>><?php echo f_e($row['Caption']); ?></option>
                            <?php } ?>
                          <?php } else { ?>
                            <?php if($row['Code'] != 5 && $row['Code'] != 6 && $row['Code'] != 7){?>
                            <option value="<?php echo f_e($row['Code']); ?>"<?php if($row['Code'] == $data['Category']) echo ' selected="selected"'; ?>><?php echo f_e($row['Caption']); ?></option>
                            <?php } ?>
                          <?php } ?>
                        <?php } ?>
                    </select>
                </td>
                <td class="l_data">
                    <input id="credit_cstring" name="expressions[Cstring]" type="text" value="<?php echo f_e($data['Cstring']); ?>" maxlength="4000" />
                </td>
                <td class="l_data">
                    <input id="credit_comment" name="expressions[Comment]" type="text" maxlength="255"  value="<?php echo f_e($data['Comment']); ?>" />
                </td>
                <td class="l_data">
                    <input id="credit_score" name="expressions[Point]" type="number" min ="-10000000" max="10000000" value="<?php echo f_e($data['Point']); ?>"  />
                </td>
            </tr>
        </tbody>
      </table>
          <!--
              ボタン類
            -->
        <table class="datatable" width="860" cellpadding="1" cellspacing="1" border="0">
          <tr align="center">
            <td>
            <?php if ( f_e($this->EnterpriseId) == -1 || f_e($this->EnterpriseId) == '' ) { ?>
              <input type="submit" value="　検索　" />　　　
              <!-- <input type="button" value="　戻る　" onClick="javascript:location.href='.'; "/>-->
              <a href="credit/pointform">戻　る</a>
            <?php } else { ?>
              <input type="submit" value="　検索　" />　　　
            <?php } ?>
            </td>
          </tr>
        </table>
   </form>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
