<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">キャンセル処理（申請取消）</h3>
    <form name="form" method="post" action="rworder/cancelcanceldone">
      <?php if( $this->hash ) { ?>
      <input name="content_hash" value="<?php echo $this->hash; ?>" type="hidden" />
      <input name="idx" value="<?php echo $this->index_in_cache; ?>" type="hidden" />
      <?php } ?>
      <table style="clear:both; margin: 0px 0px 25px 25px;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
            <th>注文Seq</th>
            <th>注文ID</th>
            <th>注文日</th>
            <th>事業者名</th>
            <th>請求先氏名</th>
            <th>住所</th>
            <th>キャンセル</th>
          </tr>
          <tr>
            <td class="r_data">
              <input type="hidden" name="OrderSeq" id="OrderSeq" value="<?php echo f_e($this->list["OrderSeq"]); ?>" />
              <?php echo f_e($this->list["OrderSeq"]); ?>
            </td>
            <td class="l_data">
              <a target="_blank" href="rworder/detail/oseq/<?php echo $this->list["OrderSeq"]; ?>"><?php echo $this->list["OrderId"]; ?></a>
            </td>
            <td class="c_data"><?php echo f_e($this->list["ReceiptOrderDate"]); ?></td>
            <td class="l_data"><?php echo f_e($this->list["EnterpriseNameKj"]); ?></td>
            <td class="l_data">
              <a target="_blank" href="customerinquiry/detail/custid/<?php echo $this->list['CustomerId']; ?>"><?php echo $this->list["NameKj"]; ?></a>
            </td>
            <td class="l_data"><?php echo f_e($this->list["UnitingAddress"]); ?>...</td>
            <td class="c_data"><?php echo $this->list["CancelType"]; ?></td>
          </tr>

          <tr class="border">
            <td>
              <img src="../images/spacer_gray.gif" height="1" width="1">
            </td>
          </tr>

          <tr>
            <td colspan="10" class="c_data">
              <p>キャンセル理由：<?php echo $this->CancelReasonCodeValue; ?></p>
              <p><?php echo $this->CancelReason; ?></p>
              <?php if($this->list["CombinedClaimTargetStatus"] == 91 || $this->list["CombinedClaimTargetStatus"] == 92) { ?>
              <p style="color: red;">とりまとめのすべての商品がキャンセル取消されます</p>
              <?php } ?>
              <input style="margin: 8px; " type="submit" value="　　キャンセル処理（申請取消）実行　　" />
            </td>
          </tr>
        </tbody>
      </table>
    </form>
  </div>
  <!-- end contents -->
  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
