<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">臨時立替</h3>
    <h4>
      臨時立替日を更新しました。
      <div style="margin-top: 18px"><a href="<?php echo f_e($this->urlDetail); ?>">注文詳細へ</a></div>
    </h4>

  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
