<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
$map = $this->master_map;
$d = $this->data;

?>
<style>
    .NTTSmartTradeCss {
    margin: 10px 25px 10px;
    font-size: 18px;
    font-weight: bold;
    color: red;
    border : solid 1px silver;
    background-color : lavenderblush;
    padding: 5px;
  }
</style>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/enterprise/page_menu.php'); ?>

<!-- start contents -->
<div id="contents">
<h3>事業者登録内容確認</h3>
    <?php if($d['NTTSmartTradeFlg'] == 1){?>
        <div class="NTTSmartTradeCss" >
        <?php echo 'NTTスマートトレード加盟店として登録します。ご確認をお願いします。' ?>
        </div>
    <?php } ?>
<table class="datatable" width="860" cellpadding="1" cellspacing="1" border="0">

    <tr>
      <td colspan="2" class="data">【事業者情報－基本情報】</td>
    </tr>
    <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"]  != 0) { ?>
    <tr>
      <td class="label">OEM先名</td>
      <td class="data" ><?php echo f_e($this->data["OemNameKj"]); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">加盟店名</td>
      <td class="data"><?php echo f_e($this->data["EnterpriseNameKj"]); ?></td>
    </tr>
    <tr>
      <td class="label">加盟店カナ</td>
      <td class="data"><?php echo f_e($this->data["EnterpriseNameKn"]); ?></td>
    </tr>
    <tr>
      <td class="label">所在地</td>
      <td class="data">〒
        <?php echo f_e($this->data["PostalCode"]); ?><br />
        <?php echo f_e($this->data["PrefectureName"]); ?><?php echo f_e($this->data["City"]); ?><br />
        <?php echo f_e($this->data["Town"]); ?><br />
        <?php echo f_e($this->data["Building"]); ?>
      </td>
    </tr>
    <tr>
      <td class="label">代表者氏名</td>
      <td class="data"><?php echo f_e($this->data["RepNameKj"]); ?></td>
    </tr>
    <tr>
      <td class="label">代表者氏名カナ</td>
      <td class="data"><?php echo f_e($this->data["RepNameKn"]); ?></td>
    </tr>
    <tr>
      <td class="label">代表電話番号</td>
      <td class="data"><?php echo f_e($this->data["Phone"]); ?></td>
    </tr>
    <tr>
      <td class="label">代表FAX番号</td>
      <td class="data"><?php echo f_e($this->data["Fax"]); ?></td>
    </tr>
    <tr>
      <td class="label">推定月商</td>
      <td class="data"><?php $key = 'PreSales'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">業種</td>
      <td class="data"><?php $key = 'Industry'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">与信手段</td>
      <td class="data"><?php $key = 'AutoCreditJudgeMode'; echo f_e($map[$key][$d[$key]]); ?>
      (与信限度額)<?php echo f_e(f_nf(nvl($this->data["UseAmountLimitForCreditJudge"], 0), '#,##0')); ?>　円</td>
    </tr>
    <tr>
      <td class="label">与信保留要求</td>
      <td class="data"><?php if(!$this->data['CreditJudgePendingRequest']) { ?>
            無効
        <?php } else { ?>
            有効
        <?php } ?></td>
    </tr>
    <tr>
      <td class="label" >有効設定</td>
      <td class="data"><?php if(!$this->data['ValidFlg']) { ?>
            無効
        <?php } else { ?>
            有効
        <?php } ?></td>
    </tr>
    <tr>
      <td colspan="2" class="data">【事業者情報－ご連絡先】</td>
    </tr>
    <tr>
      <td class="label">担当者氏名</td>
      <td class="data"><?php echo f_e($this->data["CpNameKj"]); ?></td>
    </tr>
    <tr>
      <td class="label">担当者氏名カナ</td>
      <td class="data"><?php echo f_e($this->data["CpNameKn"]); ?></td>
    </tr>
    <tr>
      <td class="label">部署名</td>
      <td class="data"><?php echo f_e($this->data["DivisionName"]); ?></td>
    </tr>
    <tr>
      <td class="label">メールアドレス</td>
      <td class="data"><?php echo f_e($this->data["MailAddress"]); ?></td>
    </tr>
    <tr>
      <td class="label">連絡先電話番号</td>
      <td class="data"><?php echo f_e($this->data["ContactPhoneNumber"]); ?></td>
    </tr>
    <tr>
      <td class="label">連絡先FAX番号</td>
      <td class="data"><?php echo f_e($this->data["ContactFaxNumber"]); ?></td>
    </tr>
    <tr>
      <td colspan="2" class="data">【サービス内容】</td>
    </tr>
    <tr>
      <td class="label">申込日</td>
      <td class="data"><?php echo f_df($this->data["ApplicationDate"], 'Y-m-d'); ?></td>
    </tr>
    <tr>
      <td class="label">利用プラン</td>
      <td class="data"><?php $key = 'Plan'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->data["MonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">次回請求月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->data["N_MonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
<!-- 2015/09/18 Y.Suzuki Add 会計対応 Stt -->
    <tr>
      <td class="label">同梱月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["IncludeMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">次回請求同梱月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["N_IncludeMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">API月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["ApiMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">次回請求API月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["N_ApiMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">与信結果通知サービス<br>月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["CreditNoticeMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">次回請求与信結果通知サービス<br>月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["N_CreditNoticeMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">次回請求与信結果通知サービス<br>月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["NCreditNoticeMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">次回請求次回請求与信結果<br>通知サービス月額固定費(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["N_NCreditNoticeMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">月額固定費予備(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["ReserveMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
    <tr>
      <td class="label">次回請求月額固定費予備(税抜)</td>
      <td class="data"><?php echo f_nf(nvl($this->atedata["N_ReserveMonthlyFee"], 0), '#,##0'); ?>　円</td>
    </tr>
<!-- 2015/09/18 Y.Suzuki Add 会計対応 End -->
    <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"]  != 0) { ?>
        <tr>
          <td class="label">OEM月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->data["OemMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">次回請求OEM月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->data["N_OemMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
<!-- 2015/09/18 Y.Suzuki Add 会計対応 Stt -->
        <tr>
          <td class="label">OEM同梱月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["OemIncludeMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">次回請求OEM同梱月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["N_OemIncludeMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">OEMAPI月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["OemApiMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">次回請求OEMAPI月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["N_OemApiMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">OEM与信通知結果サービス<br>月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["OemCreditNoticeMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">次回請求OEM与信通知結果サービス<br>月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["N_OemCreditNoticeMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">OEM次回請求与信通知結果サービス<br>月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["OemNCreditNoticeMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">次回請求OEM次回請求与信<br>通知結果サービス月額固定費(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["N_OemNCreditNoticeMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">OEM月額固定費予備(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["OemReserveMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
        <tr>
          <td class="label">次回請求OEM月額固定費予備(税抜)</td>
          <td class="data" ><?php echo f_nf(nvl($this->atedata["N_OemReserveMonthlyFee"], 0), '#,##0'); ?>　円</td>
        </tr>
<!-- 2015/09/18 Y.Suzuki Add 会計対応 End -->
    <?php } ?>
    <tr>
      <td class="label">立替サイクル</td>
      <td class="data">
      <?php if($d['isNew'] == 1) { ?>
          <?php $key = 'PayingCycleId'; echo f_e($map[$key][$d[$key]]); ?>
      <?php } else { ?>
          現在の立替サイクル ： <?php echo f_e($this->master_map['PayingCycleId'][$d['PayingCycleId']]); ?><br>
          次回立替確定時の変更予定 ： <?php echo f_e($this->master_map['PayingCycleId'][$d['N_PayingCycleId']]); ?><br>
      <?php } ?>
      </td>
    </tr>
    <tr>
      <td class="label">営業担当</td>
      <td class="data"><?php echo f_e($this->data["Salesman"]); ?></td>
    </tr>
    <tr>
      <td class="label">加盟店請求</td>
      <td class="data"><?php $key = 'ClaimClass'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td colspan="2" class="data">【入金口座】</td>
    </tr>
    <tr>
      <td class="label">金融機関</td>
      <td class="data">
        銀行名：<?php echo f_e($this->data["FfName"]); ?>　銀行番号：<?php echo f_e($this->data["FfCode"]); ?><br />
        支店名：<?php echo f_e($this->data["FfBranchName"]); ?>　支店番号：<?php echo f_e($this->data["FfBranchCode"]); ?><br />
        口座種別：<?php $key = 'FfAccountClass'; echo f_e($map[$key][$d[$key]]); ?><br />
        口座番号：<?php echo f_e($this->data["FfAccountNumber"]); ?><br />
        口座名義：<?php echo f_e($this->data["FfAccountName"]); ?>
      </td>
    </tr>
    <tr>
      <td class="label">振込手数料</td>
      <td class="data"><?php $key = 'TcClass'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td colspan="2" class="data">【その他】</td>
    </tr>
    <tr>
      <td class="label">備考：事業者対応内容</td>

      <td class="data"><?php echo f_e($this->data["Note"]); ?></td>
    </tr>
    <tr>
      <td colspan="2" class="data">【オプション機能】</td>
    </tr>
    <tr>
      <td class="label">税区分</td>
      <td class="data"><?php $key = 'TaxClass'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">審査システム自動与信</td>
      <td class="data"><?php $key = 'JudgeSystemFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">社内自動与信</td>
      <td class="data"><?php $key = 'AutoJudgeFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">ジンテック与信</td>
      <td class="data"><?php $key = 'JintecFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">手動与信</td>
      <td class="data"><?php $key = 'ManualJudgeFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">保留ボックス機能</td>
      <td class="data"><?php $key = 'HoldBoxFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">与信スレッドNo</td>
      <td class="data"><?php $key = 'CreditThreadNo'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">与信NG表示期間</td>
      <td class="data"><?php echo f_e($this->data["CreditNgDispDays"]); ?></td>
    </tr>
    <tr>
      <td class="label">与信有効期間</td>
      <td class="data"><?php echo f_e($this->data["CreditJudgeValidDays"]); ?></td>
    </tr>
    <tr>
      <td class="label">CSV一括登録</td>
      <td class="data"><?php $key = 'CsvRegistClass'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">一括登録エラー修正機能区分</td>
      <td class="data"><?php $key = 'CsvRegistErrorClass'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">入金ステータス検索条件区分</td>
      <td class="data"><?php $key = 'ReceiptStatusSearchClass'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">自動無保証対象フラグ</td>
      <td class="data"><?php $key = 'AutoNoGuaranteeFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">表示用小数点桁数</td>
      <td class="data"><?php $key = 'DispDecimalPoint'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">利用額端数計算設定</td>
      <td class="data"><?php $key = 'UseAmountFractionClass'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">請求とりまとめ店舗手数料フラグ</td>
      <td class="data"><?php $key = 'CombinedClaimChargeFeeFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">請求書コメント</td>
      <td class="data"><?php echo f_e($this->data["PrintEntComment"]); ?></td>
    </tr>
    <tr>
      <td class="label">任意注文番号の印刷（請求書）</td>
      <td class="data"><?php $key = 'PrintEntOrderIdOnClaimFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">請求書の加盟店顧客番号の印字名</td>
      <td class="data"><?php echo f_e($this->data["ClaimEntCustIdDisplayName"]); ?></td>
    </tr>
    <tr>
      <td class="r_label">請求書の注文日の印字形式</td>
      <td class="l_data"><?php echo f_e($this->data['ClaimOrderDateFormat'] ? 'YYYY/MM で印字する' : 'YYYY/MM で印字しない'); ?></td>
    </tr>
    <tr>
      <td class="label">請求書個別出力</td>
      <td class="data"><?php $key = 'ClaimIndividualOutputFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="r_label">「与信NG復活」機能</td>
      <td class="l_data"><?php echo f_e($this->data['OrderRevivalDisabled'] ? '利用を禁止' : '利用可能'); ?></td>
    </tr>
    <tr>
      <td class="label">立替完了メール</td>
      <td class="data"><?php $key = 'PayingMail'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr style="display:none">
      <td class="label">間違い伝番修正依頼メール</td>
      <td class="data"><?php $key = 'SendMailRequestModifyJournalFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">精算停止区分</td>
      <td class="data"><?php $key = 'ExecStopFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">LINE Pay利用(SMBC店舗用)</td>
      <td class="data"><?php $key = 'LinePayUseFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">注文登録APIタイムアウト利用</td>
      <td class="data"><?php $key = 'ApiOrderRestTimeOutFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">NTTスマートトレード加盟店</td>
      <td class="data"><?php $key = 'NTTSmartTradeFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">請求代行プラン</td>
      <td class="data"><?php $key = 'BillingAgentFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
      <td class="label">審査システム連携</td>
      <td class="data"><?php $key = 'IluCooperationFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
        <td colspan="2" class="data">【オプション機能（口座振替）】</td>
    </tr>
    <tr>
        <td class="label">口座振替利用</td>
        <td class="data"><?php $key = 'CreditTransferFlg'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
        <td class="label">申込用紙発行条件</td>
        <td class="data"><?php $key = 'AppFormIssueCond'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
        <td class="label">案内用紙の封入</td>
        <td class="data"><?php $key = 'ClaimPamphletPut'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
        <td class="label" >強制解約日</td>
        <td class="data"><?php if(!$this->data['ForceCancelDatePrintFlg']) { ?>
                注文の備考欄に入力された強制解約日を請求書に印字しない
            <?php } else { ?>
                注文の備考欄に入力された強制解約日を請求書に印字する
            <?php } ?></td>
    </tr>
    <tr>
        <td class="label">強制解約通知請求書</td>
        <td class="data"><?php $key = 'ForceCancelClaimPattern'; echo f_e($map[$key][$d[$key]]); ?></td>
    </tr>
    <tr>
        <td class="label" >請求書発行停止</td>
        <td class="data"><?php if(!$this->data['ClaimIssueStopFlg']) { ?>
                強制解約通知の請求書を発行後に請求ストップしない
            <?php } else { ?>
                強制解約通知の請求書を発行後に請求ストップする
            <?php } ?></td>
    </tr>
    <tr>
        <td class="label" >初回請求書発行制御</td>
        <td class="data"><?php if(!$this->data['FirstClaimIssueCtlFlg']) { ?>
                初回請求書支払期限日が過ぎた後は、初回請求書の発行をできなくしない
            <?php } else { ?>
                初回請求書支払期限日が過ぎた後は、初回請求書の発行をできなく字する
            <?php } ?></td>
    </tr>
    <tr>
        <td class="label" >再請求書発行制御</td>
        <td class="data"><?php if(!$this->data['ReClaimIssueCtlFlg']) { ?>
                手動再請求時に強制解約通知請求書しか発行できなくしない
            <?php } else { ?>
                手動再請求時に強制解約通知請求書しか発行できなくする
            <?php } ?></td>
    </tr>
    <tr>
        <td class="label" >初回再発行の支払期限</td>
        <td class="data"><?php if(!$this->data['FirstReClaimLmitDateFlg']) { ?>
                初回請求書と同じ支払期限日で発行しない
            <?php } else { ?>
                初回請求書と同じ支払期限日で発行する
            <?php } ?></td>
    </tr>
    <tr>
        <td class="label">通帳表示名</td>
        <td class="data"><?php echo f_e($this->data["MhfCreditTransferDisplayName"]); ?></td>
    </tr>
    <tr>
    <td colspan="2" align="center">
      <form id="saveForm" action="enterprise/save" method="post">
        <input name="hash" value="<?php echo f_e($this->encoded_data); ?>" type="hidden" />
<!-- 2015/09/18 Y.Suzuki Add 会計対応 Stt -->
        <input name="hash_atedata" value="<?php echo f_e($this->encoded_atedata); ?>" type="hidden" />
<!-- 2015/09/18 Y.Suzuki Add 会計対応 End -->
        <a id="doSave" href="javascript:void(0)">確　認</a>　　　　　<a id="cancelSave" href="javascript:void(0)">戻　る</a>
      </form>
    </td>
  </tr>
</table>
</div>
  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
<script>
Event.observe(window, "load", function() {
  Event.observe($("doSave"), "click", function() {
    $("saveForm").submit();
    return false;
  });
  Event.observe($("cancelSave"), "click", function() {
    $("saveForm").action = $("saveForm").action.replace(/\/save$/, "/back");
    $("saveForm").submit();
    return false;
  });
});
</script>
</body>
</html>
