<?php
use cbadmin\Application;

// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
if( ! isset($this->error) || ! is_array($this->error) ) $this->error = array();

function show_error_message($messages) {
  if( empty($messages) ) return;
  if( ! is_array($messages) ) $messages = array($messages);
  $list = array();
  foreach($messages as $msg) $list[] = f_e($msg);
  echo '<div class="input_error_message">';
  echo join('<br />', $list);
  echo '</div>';
}

$map = $this->master_map;
?>
  <style type="text/css">
  #contents table {
    margin: 0px;
    padding: 0px;
  }

  table.ddtable {
    background-color: #dddddd;
    font-size: 11px;
    margin: 0px;
    padding: 0px;
  }

  td.l_label {
    text-align: left;
    padding: 0px 0px 0px 5px;
    background-color: #eeeeee;
  }

  td.r_label {
    text-align: right;
    padding: 0px 5px 0px 0px;
    background-color: #eeeeee;
    width: 180px;
    white-space: nowrap;
  }

  td.c_label {
    text-align: center;
    /*padding: 2px 10px 2px 0px;*/
    background-color: #eeeeee;
  }

  td.l_data {
    text-align: left;
    padding: 0px 0px 0px 5px;
    background-color: #ffffff;
  }

  td.l_data span.wrap_container {
    width: 320px;
    overflow: hidden;
    float: left;
  }

  td.r_data {
    text-align: right;
    padding: 0px 5px 0px 0px;
    background-color: #ffffff;
  }

  td.c_data {
    text-align: center;
    padding: 2px 0px 2px 0px;
    background-color: #ffffff;
  }

  div {
    margin: 0px;
    padding: 0px;
    font-size: 12px;
    font-family: "ＭＳ Ｐゴシック", Osaka, "ヒラギノ角ゴ Pro W3";
  }

  #div01 {
    float: left;
    margin: 0px 60px 5px 25px;
  }

  #div03,
  #div06,
  #div07 {
    clear: both;
    margin: 0px 0px 5px 25px;
  }

  #div04 {
    float: left;
    margin: 0px 10px 10px 25px;
  }
  tr.valid td {
  }
  tr.valid td a {
  }
  tr.invalid td {
    color: gray !important;
    /*text-decoration: line-through !important;*/
  }
  tr.invalid td a {
    color: steelblue;
  }

  .input_error_message {
    color: red;
  }
    div.error-message-batchLock {
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 5px;
	padding: 4px 8px;
    border: 1px solid gray;
    width: 842px;
    background-color: mistyrose;
    font-weight: bold;
    color: red;
  }
  </style>
  <script type="text/javascript">
    function send(eid)
    {
      if (confirm('審査結果メールを送信します。'))
      {
        var url = '<?php echo $this->urlSendExam; ?>';
        url = '<?php echo $this->baseUrl; ?>' + url + '/eid/' + eid;

        var ajax = new Ajax.Request(
          url,
          {
            method: 'get',
            asynchronous: false
          });

        var res = eval('(' + ajax.transport.responseText + ')');
        if  (res['status'] == 1)
        {
          alert('審査結果メールを送信しました。\n\nパスワードリセットを実行して事業者様へパスワードを通知してください');
        }
        else
        {
          alert('審査結果メールの送信に失敗しました。 Err=' + res['status']);
        }
      }
    }

    function sendTest(eid)
    {
      if (confirm('送達確認用メールを送信します。'))
      {
        var url = '<?php echo $this->urlSendTest; ?>';
        url = '<?php echo $this->baseUrl; ?>' + url + '/eid/' + eid;

        var ajax = new Ajax.Request(
          url,
          {
            method: 'get',
            asynchronous: false
          });

        var res = eval('(' + ajax.transport.responseText + ')');
        if  (res['status'] == 1)
        {
          alert('送達確認用メールを送信しました。');
        }
        else
        {
          alert('送達確認用メールの送信に失敗しました。 Err=' + res['status']);
        }
      }
    }
  </script>
</head>
<body>
  <div id="wrapper">
    <?php echo $this->render('cbadmin/page_header.php'); ?>
    <?php echo $this->render('cbadmin/enterprise/page_menu.php'); ?>

    <!-- start contents -->
    <div id="contents">
      <h3>事業者詳細情報</h3>
      <?php
      if(isset($this->message)){ ?>
          <div class = "error-message-batchLock" >
             <?php echo $this->message ?>
          </div>
      <?php } ?>
      <div style="margin: 0 25px"><?php show_error_message($this->error['EnterpriseId']); ?></div>
      <div id="div01">
        <table class="datatable" width="500" cellpadding="1" cellspacing="1" border="0">
          <tr>
            <td colspan="2" class="l_data">【事業者情報－基本情報】　　　<a href="enterprise/edit/eid/<?php echo f_e($this->data["EnterpriseId"]); ?>">編集</a></td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td width="100" class="r_label oem">OEM先名</td>
            <td class="l_data">
            <?php if(!empty($this->data['OemId'])) { ?>
              <a href="oem/detail/oid/<?php echo f_e($this->data['OemId']); ?>"><?php echo f_e($this->data["OemName"]); ?></a>
            <?php } else { ?>
              &nbsp;
            <?php } ?>
            </td>
          </tr>
        <?php } ?>
          <tr>
            <td width="100" class="r_label">事業者ID</td>
            <td class="l_data"><?php echo f_e($this->data["EnterpriseId"]); ?></td>
          </tr>
          <tr>
            <td width="100" class="r_label">サービス開始日</td>
            <td class="l_data"><?php echo f_e($this->data["ServiceInDate"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">ログインID</td>
            <td class="l_data"><?php echo f_e($this->data["LoginId"]); ?><a style="margin-left: 30px" href="enterpriseoperator/form/eid/<?php echo f_e($this->data['EnterpriseId']); ?>" target="_blank">追加ログイン情報</a></td>
          </tr>
          <tr>
            <td class="r_label">ログインPW</td>
            <td class="l_data">
            <?php if($this->data['Hashed']) { ?>
              (暗号化済み)
              <a style="margin-left: 40px" onclick="return confirm('パスワードリセットを実行しますか？')" href="enterprise/resetpsw/eid/<?php echo f_e($this->data['EnterpriseId']); ?>">パスワードリセット</a>
            <?php } else { ?>
              <?php echo f_e($this->data["LoginPasswd"]); ?>
            <?php } ?>
            </td>
          </tr>
          <tr>
            <td class="r_label">加盟店名</td>
            <td class="l_data"><?php echo f_e($this->data["EnterpriseNameKj"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">加盟店カナ</td>
            <td class="l_data"><?php echo f_e($this->data["EnterpriseNameKn"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">所在地</td>
            <td class="l_data">〒<?php echo f_e($this->data["PostalCode"]); ?><br />
              <?php echo f_e($this->data["PrefectureName"]); ?><?php echo f_e($this->data["City"]); ?>
              <?php echo f_e($this->data["Town"]); ?>
              <?php echo f_e($this->data["Building"]); ?>
            </td>
          </tr>
          <tr>
            <td class="r_label">代表者氏名</td>
            <td class="l_data"><?php echo f_e($this->data["RepNameKj"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">代表者氏名カナ</td>
            <td class="l_data"><?php echo f_e($this->data["RepNameKn"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">代表電話番号</td>
            <td class="l_data"><?php echo f_e($this->data["Phone"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">代表FAX番号</td>
            <td class="l_data"><?php echo f_e($this->data["Fax"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">推定月商</td>
            <td class="l_data"><?php echo f_e($this->data["PreSales"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">業種</td>
            <td class="l_data"><?php echo f_e($this->data["Industry"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">与信手段</td>
            <td class="l_data"><?php echo f_e($this->data["AutoCreditJudgeMode"]); ?>
            (与信限度額)<?php echo f_nf($this->data["UseAmountLimitForCreditJudge"], '#,##0'); ?>　円
            </td>
          </tr>
          <tr>
            <td class="r_label">与信保留要求</td>
            <td class="l_data"><?php if(!$this->data['CreditJudgePendingRequest']) { echo '無効'; } else { echo '有効'; } ?></td>
          </tr>
          <tr>
            <td class="r_label">有効設定</td>
            <td class="l_data"><?php if(!$this->data['ValidFlg']) { echo '無効'; } else { echo '有効'; } ?></td>
          </tr>
          <tr>
            <td colspan="2" class="l_data">【事業者情報－ご連絡先】</td>
          </tr>
          <tr>
            <td class="r_label">担当者氏名</td>
            <td class="l_data"><?php echo f_e($this->data["CpNameKj"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">担当者氏名カナ</td>
            <td class="l_data"><?php echo f_e($this->data["CpNameKn"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">部署名</td>
            <td class="l_data"><?php echo f_e($this->data["DivisionName"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">メールアドレス</td>
            <td class="l_data">
              <span class="wrap_container">
                <?php echo f_e($this->data["MailAddress"]); ?>
                <form><input type="button" value="送達確認用メール送信" onClick="javascript:sendTest('<?php echo f_e($this->data["EnterpriseId"]); ?>');" /></form>
              </span>
            </td>
          </tr>
          <tr>
            <td class="r_label">連絡先電話番号</td>
            <td class="l_data"><?php echo f_e($this->data["ContactPhoneNumber"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">連絡先FAX番号</td>
            <td class="l_data"><?php echo f_e($this->data["ContactFaxNumber"]); ?></td>
          </tr>
          <tr>
            <td colspan="2" class="l_data">【オプション機能】</td>
          </tr>
          <tr>
            <td class="r_label">新旧システム版設定</td>
            <td class="l_data"><?php echo ($this->data['SystemClass'] == 1) ? '新システム' : '旧システム'; ?></td>
          </tr>
          <tr>
            <td class="label">税区分</td>
            <td class="data"><?php $key = 'TaxClass'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">審査システム自動与信</td>
            <td class="data"><?php $key = 'JudgeSystemFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">社内自動与信</td>
            <td class="data"><?php $key = 'AutoJudgeFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">ジンテック与信</td>
            <td class="data"><?php $key = 'JintecFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">手動与信</td>
            <td class="data"><?php $key = 'ManualJudgeFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">保留ボックス機能</td>
            <td class="data"><?php $key = 'HoldBoxFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">与信スレッドNo</td>
            <td class="data"><?php $key = 'CreditThreadNo'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">与信NG表示期間</td>
            <td class="data"><?php echo f_e($this->data["CreditNgDispDays"]); ?></td>
          </tr>
          <tr>
            <td class="label">与信有効期間</td>
            <td class="data"><?php echo f_e($this->data["CreditJudgeValidDays"]); ?></td>
          </tr>
          <tr>
            <td class="label">CSV一括登録</td>
            <td class="data"><?php $key = 'CsvRegistClass'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">一括登録エラー修正機能区分</td>
            <td class="data"><?php $key = 'CsvRegistErrorClass'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">入金ステータス検索条件区分</td>
            <td class="data"><?php $key = 'ReceiptStatusSearchClass'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">自動無保証対象</td>
            <td class="data"><?php $key = 'AutoNoGuaranteeFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">表示用小数点桁数</td>
            <td class="data"><?php $key = 'DispDecimalPoint'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">利用額端数計算設定</td>
            <td class="data"><?php $key = 'UseAmountFractionClass'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">請求とりまとめ店舗手数料</td>
            <td class="data"><?php $key = 'CombinedClaimChargeFeeFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">請求書コメント</td>
            <td class="data">
            <textarea style="font-size: 12px;" name="Note" cols="40" rows="8" readonly><?php echo f_e($this->data["PrintEntComment"]); ?></textarea>
            </td>
          </tr>
          <tr>
            <td class="r_label">任意注文番号の印刷（請求書）</td>
            <td class="l_data">
              <?php echo nvl($this->data['PrintEntOrderIdOnClaimFlg'], 0) ? '印刷する' : '印刷しない'; ?>
            </td>
          </tr>
          <tr>
            <td class="label">請求書の加盟店顧客番号の印字名</td>
            <td class="data"><?php echo f_e($this->data["ClaimEntCustIdDisplayName"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">請求書の注文日の印字形式</td>
            <td class="l_data"><?php echo f_e($this->data['ClaimOrderDateFormat'] ? 'YYYY/MM で印字する' : 'YYYY/MM で印字しない'); ?></td>
          </tr>
          <tr>
            <td class="r_label">請求書個別出力</td>
            <td class="l_data">
              <?php echo ($this->data['ClaimIndividualOutputFlg'] == 1) ? '個別出力する' : '個別出力しない'; ?>
            </td>
          </tr>
          <tr>
            <td class="r_label">「与信NG復活」機能</td>
            <td class="l_data"><?php echo f_e($this->data['OrderRevivalDisabled'] ? '利用を禁止' : '利用可能'); ?></td>
          </tr>
          <tr>
            <td class="label">立替完了メール</td>
            <td class="data"><?php $key = 'PayingMail'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr style="display:none">
            <td class="r_label">間違い伝番修正依頼メール</td>
            <td class="data"><?php $key = 'SendMailRequestModifyJournalFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="r_label">精算停止区分</td>
            <td class="data"><?php $key = 'ExecStopFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="r_label">LINE Pay利用(SMBC店舗用)</td>
            <td class="data"><?php $key = 'LinePayUseFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="r_label">注文登録APIタイムアウト利用</td>
            <td class="data"><?php $key = 'ApiOrderRestTimeOutFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="r_label">NTTスマートトレード加盟店</td>
            <td class="data"><?php $key = 'NTTSmartTradeFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="r_label">請求代行プラン</td>
            <td class="data"><?php $key = 'BillingAgentFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="r_label">審査システム連携</td>
            <td class="data"><?php $key = 'IluCooperationFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="label">社内与信条件</td>
            <td class="data"><a href="credit/search/eid/<?php echo f_e($this->data["EnterpriseId"]); ?>" target="_blank">社内与信条件編集</a></td>
          </tr>
          <tr>
            <td colspan="2" class="l_data">【オプション機能（口座振替）】</td>
          </tr>
          <tr>
            <td class="r_label">口座振替利用</td>
            <td class="data"><?php $key = 'CreditTransferFlg'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="r_label">申込用紙発行条件</td>
            <td class="data"><?php $key = 'AppFormIssueCond'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="r_label">案内用紙の封入</td>
            <td class="data"><?php $key = 'ClaimPamphletPut'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
          <tr>
            <td class="r_label">強制解約日</td>
            <td class="l_data"><?php if(!$this->data['ForceCancelDatePrintFlg']) { echo '注文の備考欄に入力された強制解約日を請求書に印字しない'; } else { echo '注文の備考欄に入力された強制解約日を請求書に印字する'; } ?></td>
          </tr>
          <tr>
            <td class="r_label">強制解約通知請求書</td>
            <td class="data"><?php $key = 'ForceCancelClaimPattern'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
            <tr>
                <td class="r_label">請求書発行停止</td>
                <td class="l_data"><?php if(!$this->data['ClaimIssueStopFlg']) { echo '強制解約通知の請求書を発行後に請求ストップしない'; } else { echo '強制解約通知の請求書を発行後に請求ストップする'; } ?></td>
            </tr>
            <tr>
                <td class="r_label">初回請求書発行制御</td>
                <td class="l_data"><?php if(!$this->data['FirstClaimIssueCtlFlg']) { echo '初回請求書支払期限日が過ぎた後は、初回請求書の発行をできなくしない'; } else { echo '初回請求書支払期限日が過ぎた後は、初回請求書の発行をできなくする'; } ?></td>
            </tr>
            <tr>
                <td class="r_label">再請求書発行制御</td>
                <td class="l_data"><?php if(!$this->data['ReClaimIssueCtlFlg']) { echo '手動再請求時に強制解約通知請求書しか発行できなくしない'; } else { echo '手動再請求時に強制解約通知請求書しか発行できなくする'; } ?></td>
            </tr>
            <tr>
                <td class="r_label">初回再発行の支払期限</td>
                <td class="l_data"><?php if(!$this->data['FirstReClaimLmitDateFlg']) { echo '初回請求書と同じ支払期限日で発行しない'; } else { echo '初回請求書と同じ支払期限日で発行する'; } ?></td>
            </tr>
            <tr>
                <td class="r_label">通帳表示名</td>
                <td class="data"><?php $key = 'MhfCreditTransferDisplayName'; echo f_e($this->data[$key]); ?></td>
            </tr>
        </table>
      </div>
      <form name="form" method="post" action="enterprise/up">
        <div id="div02">
          <table class="datatable" width="310" cellpadding="1" cellspacing="1" border="0">
            <tr>
              <td colspan="4" class="l_data">【不払率】　　　<a href="enterprise/sitenplist/eid/<?php echo f_e($this->data["EnterpriseId"]); ?>" target="_blank">サイト別不払率</a></td>
            </tr>
            <?php
                $row = $this->sitenplist;
                $npRate1 = ($row['type1']['cnt'] == 0) ? 0 : sprintf('%.3f', $row['type1']['cnt'] / $row['type1']['cntall'] * 100);
                $npRate2 = ($row['type2']['cnt'] == 0) ? 0 : sprintf('%.3f', $row['type2']['cnt'] / $row['type2']['cntall'] * 100);
                $npRate3 = ($row['type3']['cnt'] == 0) ? 0 : sprintf('%.3f', $row['type3']['cnt'] / $row['type3']['cntall'] * 100);
                $npRate4 = ($row['type4']['cnt'] == 0) ? 0 : sprintf('%.3f', $row['type4']['cnt'] / $row['type4']['cntall'] * 100);
                $npRate5 = ($row['type5']['cnt'] == 0) ? 0 : sprintf('%.3f', $row['type5']['cnt'] / $row['type5']['cntall'] * 100);
                $npRate6 = ($row['type6']['cnt'] == 0) ? 0 : sprintf('%.3f', $row['type6']['cnt'] / $row['type6']['cntall'] * 100);
                $npRateSum1 = ($row['type1']['sum'] == 0) ? 0 : sprintf('%.3f', $row['type1']['sum'] / $row['type1']['sumall'] * 100);
                $npRateSum2 = ($row['type2']['sum'] == 0) ? 0 : sprintf('%.3f', $row['type2']['sum'] / $row['type2']['sumall'] * 100);
                $npRateSum3 = ($row['type3']['sum'] == 0) ? 0 : sprintf('%.3f', $row['type3']['sum'] / $row['type3']['sumall'] * 100);
                $npRateSum4 = ($row['type4']['sum'] == 0) ? 0 : sprintf('%.3f', $row['type4']['sum'] / $row['type4']['sumall'] * 100);
                $npRateSum5 = ($row['type5']['sum'] == 0) ? 0 : sprintf('%.3f', $row['type5']['sum'] / $row['type5']['sumall'] * 100);
                $npRateSum6 = ($row['type6']['sum'] == 0) ? 0 : sprintf('%.3f', $row['type6']['sum'] / $row['type6']['sumall'] * 100);
            ?>
            <tr>
              <td class="r_label" rowspan="4" style="font-size: 11px;">不払率(件数)</td>
              <td class="c_label" style="width: 80px;" style="font-size: 11px;">一週間</td>
              <td class="c_label" style="width: 80px;" style="font-size: 11px;">一ヶ月</td>
              <td class="c_label" style="width: 80px;" style="font-size: 11px;">三ヶ月</td>
            </tr>
            <tr>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRate1) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRate1); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRate2) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRate2); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRate3) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRate3); ?> ％</td>
            </tr>
            <tr>
              <td class="c_label" style="font-size: 11px;">六ヶ月</td>
              <td class="c_label" style="font-size: 11px;">一年</td>
              <td class="c_label" style="font-size: 11px;">全体</td>
            </tr>
            <tr>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRate4) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRate4); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRate5) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRate5); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRate6) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRate6); ?> ％</td>
            </tr>
            <tr>
              <td class="r_label" rowspan="4" style="font-size: 11px;">不払率(金額)</td>
              <td class="c_label" style="font-size: 11px;">１５日</td>
              <td class="c_label" style="font-size: 11px;">６０日</td>
              <td class="c_label" style="font-size: 11px;">１２０日</td>
            </tr>
            <tr>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRateSum1) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRateSum1); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRateSum2) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRateSum2); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRateSum3) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRateSum3); ?> ％</td>
            </tr>
            <tr>
              <td class="c_label" style="font-size: 11px;">２１０日</td>
              <td class="c_label" style="font-size: 11px;">３９０日</td>
              <td class="c_label" style="font-size: 11px;">全体</td>
            </tr>
            <tr>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRateSum4) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRateSum4); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRateSum5) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRateSum5); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if (floor($npRateSum6) >= $this->npRateColorThreshold) { ?> background-color: mistyrose;<?php } ?>"><?php echo f_e($npRateSum6); ?> ％</td>
            </tr>
            <tr>
              <td class="r_label" style="font-size: 11px;" rowspan="2">事業者収益<br />(過去３ヶ月)</td>
              <td class="c_label" style="font-size: 11px;">手数料率</td>
              <td class="c_label" style="font-size: 11px;">収益率</td>
              <td class="c_label" style="font-size: 11px;">損益額</td>
            </tr>
            <tr>
              <td class="r_data" style="font-size: 11px;"><?php echo ($row['settlementfeerate'] == '-') ? '-' : f_e(sprintf('%.5f', $row['settlementfeerate'])); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if ($row['profitrate'] < 0) { ?> color: red;<?php } ?>"><?php echo ($row['profitrate'] == 0) ? 0 : f_e(sprintf('%.3f', $row['profitrate'])); ?> ％</td>
              <td class="r_data" style="font-size: 11px;<?php if ($row['profitrate'] < 0) { ?> color: red;<?php } ?>"><?php echo f_nf($row['profitandloss'], '#,##0'); ?> 円</td>
            </tr>
            <tr>
              <td colspan="4" class="l_data">【審査状況】</td>
            </tr>
            <tr>
              <td width="100" class="r_label">お申込日</td>
              <td class="l_data" colspan="3"><?php echo f_e($this->data["ApplicationDate"]); ?></td>
            </tr>
            <tr>
              <td class="r_label">書類回収</td>
              <td class="l_data" colspan="3">
                <?php echo $this->docCollectSelectTag; ?>
                <?php show_error_message($this->error['DocCollect']); ?></td>
              </td>
            </tr>
            <tr>
              <td class="r_label">審査結果</td>
              <td class="l_data" colspan="3">
                <?php echo $this->examinationResultSelectTag; ?>
                <?php show_error_message($this->error['ExaminationResult']); ?></td>
              </td>
            </tr>
            <tr>
              <td class="r_label">審査結果メール</td>
              <td class="l_data" colspan="3">
                <input type="button" value="審査結果メール送信" onClick="javascript:send('<?php echo f_e($this->data["EnterpriseId"]); ?>');" /><br />
                <span style="color: red; ">要部長決裁！</span>
              </td>
            </tr>
            <tr>
              <td class="r_label">掲載確認日</td>
              <td class="l_data" colspan="3">
                <input type="text" name="PublishingConfirmDate" id="PublishingConfirmDate" value="<?php echo f_e($this->data["PublishingConfirmDate"]); ?>" />
                <?php show_error_message($this->error['PublishingConfirmDate']); ?>
              </td>
            </tr>
            <tr>
              <td colspan="4" class="l_data">【備考：事業者対応内容】</td>
            </tr>
            <tr>
              <td colspan="4" class="c_data">
                <textarea style="font-size: 12px;" name="Note" cols="40" rows="8"><?php echo f_e($this->data["Note"]); ?></textarea>
                <div style="text-align: left">
                  <label for="sp_flg" style="margin-left: 18px;">
                    <input id="sp_flg" name="Special01Flg" type="checkbox" value="1" <?php if($this->data['Special01Flg']) echo 'checked="checked" '; ?>/>
                    「特殊店舗」としてマーク
                  </label>
                </div>
                <?php show_error_message($this->error['Note']); ?>
                <?php show_error_message($this->error['Special01Flg']); ?>
              </td>
            </tr>
            <tr>
              <td colspan="4" class="l_data">【与信備考：手動与信時の注意/ルール】</td>
            </tr>
            <tr>
              <td colspan="4" class="c_data">
                <textarea style="font-size: 12px;" name="Memo" cols="40" rows="5"><?php echo f_e($this->data["Memo"]); ?></textarea>
                <?php show_error_message($this->error['Memo']); ?>
              </td>
            </tr>
            <tr>
              <td colspan="4" class="l_data">【電話対応欄：電話やメール応対の際の注意/ルール】</td>
            </tr>
            <tr>
              <td colspan="4" class="c_data">
                <textarea style="font-size: 12px;" name="Notice" cols="40" rows="4"><?php echo f_e($this->data["Notice"]); ?></textarea>
                <?php show_error_message($this->error['Notice']); ?>
              </td>
            </tr>
            <tr>
              <td colspan="4" class="c_data">
                <input type="hidden" name="eid" value="<?php echo f_e($this->data["EnterpriseId"]); ?>" />
                <input type="submit" value="　更　新　" />
              </td>
            </tr>
          </table>
        </div>
      </form>
      <div id="div03">
        <?php $allowFcSetting = Application::getInstance()->allowFirstClaimLayoutSetting(); ?>
        <table class="datatable" width="860" cellpadding="1" cellspacing="1" border="0">
          <tr>
            <td colspan="<?php echo $allowFcSetting ? 6 : 5; ?>" class="l_data">【サイト情報】　　　<a href="site/list/eid/<?php echo f_e($this->data["EnterpriseId"]); ?>">サイト情報編集</a></td>
          </tr>
          <tr>
            <th style="width: 45px">ID</th>
            <th>サイト名</th>
            <th>URL</th>
            <th style="width: <?php echo $allowFcSetting ? 60 : 90; ?>px">メアド</th>
            <th style="width: <?php echo $allowFcSetting ? 60 : 90; ?>px">サイト形態</th>
          <?php if($allowFcSetting) { ?>
            <th style="width: 60px">初回封書</th>
          <?php } ?>
          </tr>
        <?php foreach($this->sites as $i => $site) { ?>
          <tr>
            <td class="r_data"><?php echo f_e($site["SiteId"]); ?></td>
            <td class="l_data"><?php echo f_e($site["SiteNameKj"]); ?></td>
            <td class="l_data"><a target="_blank" href="<?php echo f_e($site["Url"]); ?>"><?php echo f_e($site["Url"]); ?></a></td>
            <td class="c_data"><?php echo f_e($site["ReqMailAddrFlg"]); ?></td>
            <td class="c_data"><?php echo f_e($site["SiteForm"]); ?></td>
          <?php if($allowFcSetting) { ?>
            <td class="c_data"><?php echo $site['FirstClaimLayoutMode'] ? '使用' : '&nbsp;'; ?></td>
          <?php } ?>
          </tr>
        <?php } ?>
        </table>
      </div>
      <div id="div03">
        <table class="datatable" width="860" cellpadding="1" cellspacing="1" border="0">
          <tr>
            <td colspan="5" class="l_data">【配送方法情報】　　　<a target="_blank" href="enterprisedeliv/edit/eid/<?php echo f_e($this->data["EnterpriseId"]);?>">配送方法情報編集</a></td>
          </tr>
          <tr>
            <th style="width: 70px">配送方法ID</th>
            <th style="width: 70px">表示順</th>
            <th>配送方法名称</th>
          </tr>
        <?php foreach($this->delivs as $i => $row) { ?>
          <tr>
            <td class="r_data"><?php echo f_e($row["DeliMethodId"]); ?></td>
            <td class="c_data"><?php echo f_e($row["ListNumber"]); ?></td>
            <td class="l_data"><?php echo f_e($row["DeliMethodName"]); ?></td>
          </tr>
        <?php } ?>
        </table>
      </div>
      <div id="div06">
        <table class="datatable" width="860" cellpadding="1" cellspacing="1" border="0">
          <tr>
            <td colspan="5" class="l_data">【請求取りまとめモード】　　　<a href="combinedclaim/edit/eid/<?php echo f_e($this->data["EnterpriseId"]); ?>">請求取りまとめモード編集</a></td>
          </tr>
          <tr>
            <td width="100" class="r_label">請求取りまとめモード</td>
            <td class="l_data">
            <?php
              if($this->data['CombinedClaimMode'] == 1) {
                  echo '事業者毎';
              } else if($this->data['CombinedClaimMode'] == 2) {
                  echo 'サイト毎('.$this->combinedclaimnum.')';
              } else {
                  echo 'なし';
              }
            ?>
          </td>
          </tr>
        </table>
      </div>
      <?php if($this->sbsettings['enable_settings']) { ?>
      <?php /* 同梱ツール関係設定：config.iniで有効になっていない場合は表示しない */ ?>
      <div id="div07">
        <table class="datatable" width="860" cellpadding="1" cellspacing="1" border="0">
          <tr>
            <td colspan="5" class="l_data">【請求書同梱ツール設定】　　　<a href="enterprise/sbsetting/eid/<?php echo f_e($this->data["EnterpriseId"]); ?>">設定変更</a></td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">同梱ツールの利用</td>
            <td class="l_data" colspan="2">
            <?php
              if($this->data['SelfBillingMode'] >= 1) {
                  echo '利用する';
              } else if($this->data['SelfBillingMode'] == -1) {
                  echo '（一時保留中）';
              } else {
                  echo '利用しない';
              }
            ?>
            </td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">請求書発行後の伝票番号更新機能</td>
            <td class="l_data" colspan="2"><?php if($this->data['SelfBillingMode'] > 10) { echo '更新を許可する'; } else { echo '更新を許可しない'; } ?></td>
          </tr>
        <?php if(!$this->data['SelfBillingMode'] > 0) {?>
          <tr>
            <td class="r_label" style="width: 200px">CSV出力機能の利用</td>
            <td class="l_data" colspan="2">（未設定）</td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">別送機能の制限</td>
            <td class="l_data" colspan="2">（未設定）</td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">払込負担区分</td>
            <td class="l_data" colspan="2">（未設定）</td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">リスト取得上限件数</td>
            <td class="l_data" colspan="2">（未設定）</td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">注文マイページの利用</td>
            <td class="l_data" colspan="2">（未設定）</td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">自動印刷済み更新</td>
            <td class="l_data" colspan="2">（未設定）</td>
          </tr>
          <?php } else { ?>
          <tr>
            <td class="r_label" style="width: 200px">CSV出力機能の利用</td>
            <td class="l_data" colspan="2"><?php echo $this->data['SelfBillingExportAllow'] ? '利用可能' : '利用不可'; ?></td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">別送機能の制限</td>
            <td class="l_data" colspan="2">
              <?php $tmpl = $this->data['SelfBillingMode'] == -1 ? '(%s)' : '%s'; ?>
              <?php echo sprintf($tmpl, $this->data['HideToCbButton'] ? '同梱ツールに別送ボタンを表示しない' : '制限なし'); ?>
            </td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">払込負担区分</td>
            <td class="l_data" colspan="2">
              <?php echo sprintf($this->data['ChargeClass'] == 1 ? '払込人負担' : '加入者負担'); ?>
            </td>
          </tr>
          <tr>
          <td class="r_label" style="width: 200px">リスト取得上限件数</td>
            <td class="l_data" colspan="2">
              <?php echo sprintf($this->data['TargetListLimit'] == null ? '（未設定）' : $this->data['TargetListLimit'] . " 件"); ?>
            </td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">注文マイページの利用</td>
            <td class="l_data" colspan="2">
              <?php echo sprintf($this->data['OrderpageUseFlg'] == 1 ? '利用する' : '利用しない'); ?>
            </td>
          </tr>
          <tr>
            <td class="r_label" style="width: 200px">自動印刷済み更新</td>
            <td class="l_data" colspan="2">
              <?php echo sprintf($this->data['SelfBillingPrintedAutoUpdateFlg'] == 1 ? '利用する' : '利用しない'); ?>
            </td>
          </tr>
          <?php } ?>
        </table>
      </div>
      <?php } ?>
      <div id="div04">
        <table class="datatable" width="450" cellpadding="1" cellspacing="1" border="0">
          <tr>
            <td colspan="2" class="l_data">【サービス内容】</td>
          </tr>
          <tr>
            <td width="100" class="r_label">利用プラン</td>
            <td class="l_data"><?php echo f_e($this->data["Plan"]); ?></td>
          </tr>
          <tr>
            <td class="r_label">月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->data["MonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">OEM月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->data["OemMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
<!-- 2015/09/18 Y.Suzuki Add 会計対応 Stt -->
          <tr>
            <td class="r_label">同梱月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["IncludeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">OEM同梱月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["OemIncludeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
          <tr>
            <td class="r_label">API月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["ApiMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">OEMAPI月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["OemApiMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
          <tr>
            <td class="r_label">与信結果通知サービス月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["CreditNoticeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">OEM与信結果通知サービス月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["OemCreditNoticeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
          <tr>
            <td class="r_label">次回請求与信結果通知サービス月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["NCreditNoticeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">OEM次回請求与信結果通知サービス月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["OemNCreditNoticeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
          <tr>
            <td class="r_label">月額固定費予備(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["ReserveMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">OEM月額固定費予備(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["OemReserveMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
<!-- 2015/09/18 Y.Suzuki Add 会計対応 End -->
          <tr>
            <td class="r_label">次回請求月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->data["N_MonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">次回請求OEM月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->data["N_OemMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
<!-- 2015/09/18 Y.Suzuki Add 会計対応 Stt -->
        <tr>
            <td class="r_label">次回請求同梱月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_IncludeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">次回請求月額OEM同梱固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_OemIncludeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
        <tr>
            <td class="r_label">次回請求API月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_ApiMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">次回請求OEMAPI月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_OemApiMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
        <tr>
            <td class="r_label">次回請求与信結果通知サービス月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_CreditNoticeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">次回請求OEM与信結果通知サービス月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_OemCreditNoticeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
        <tr>
            <td class="r_label">次回請求次回請求与信結果通知サービス月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_NCreditNoticeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">次回請求OEM次回請求与信結果通知サービス月額固定費(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_OemNCreditNoticeMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
        <tr>
            <td class="r_label">次回請求月額固定費予備(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_ReserveMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php if(!is_null($this->data["OemId"]) && $this->data["OemId"] != 0) { ?>
          <tr>
            <td class="r_label">次回OEM請求月額固定費予備(税抜)</td>
            <td class="l_data"><?php echo f_nf($this->atedata["N_OemReserveMonthlyFee"], '#,##0'); ?>　円</td>
          </tr>
        <?php }?>
<!-- 2015/09/18 Y.Suzuki Add 会計対応 End -->
          <tr>
            <td class="label">立替サイクル</td>
            <td class="data"><?php echo f_e($map['PayingCycleId'][$this->data['PayingCycleId']]); ?></td>
          </tr>
          <tr>
            <td class="r_label">営業担当</td>
            <td class="l_data"><?php echo f_e($this->data["Salesman"]); ?></td>
          </tr>
          <tr>
            <td class="label">加盟店請求</td>
            <td class="data"><?php $key = 'ClaimClass'; echo f_e($map[$key][$this->data[$key]]); ?></td>
          </tr>
        </table>
      </div>
      <div id="div05">
        <table class="datatable" width="400" cellpadding="1" cellspacing="1" border="0">
          <tr>
            <td colspan="2" class="l_data">【入金口座】</td>
          </tr>
          <tr>
            <td width="100" class="r_label">金融機関</td>
            <td class="l_data">
              銀行名：<?php echo f_e($this->data["FfName"]); ?>　銀行番号：<?php echo f_e($this->data["FfCode"]); ?><br />
              支店名：<?php echo f_e($this->data["FfBranchName"]); ?>　支店番号：<?php echo f_e($this->data["FfBranchCode"]); ?><br />
              口座種別：<?php echo f_e($this->data["FfAccountClass"]); ?><br />
              口座番号：<?php echo f_e($this->data["FfAccountNumber"]); ?><br />
              口座名義：<?php echo f_e($this->data["FfAccountName"]); ?>
            </td>
          </tr>
          <tr>
            <td class="r_label">振込手数料</td>
            <td class="l_data"><?php echo f_e($this->data["TcClass"]); ?></td>
          </tr>
        </table>
      </div>
      <!-- count関数対策 -->
      <?php if (!empty($this->campaign)) { ?>
      <div id="div03">
        <table class="datatable" width="500" cellpadding="1" cellspacing="1" border="0">
          <tr>
            <td colspan="4" class="l_data">【キャンペーン設定】</td>
          </tr>
          <tr>
            <th>プラン名</th>
            <th>期間FROM</th>
            <th>期間TO</th>
            <th>月額固定費</th>
          </tr>
          <?php foreach ($this->campaign as $value) { ?>
          <tr>
            <td class="l_data"><?php echo f_e($value['PricePlanName']); ?></td>
            <td class="c_data"><?php echo f_df($value['DateFrom'], 'Y-m-d'); ?></td>
            <td class="c_data"><?php echo f_df($value['DateTo'], 'Y-m-d'); ?></td>
            <td class="r_data"><?php echo f_nf(nvl($value['MonthlyFee'], 0), '#,##0'); ?></td>
          </tr>
          <?php } ?>
        </table>
      </div>
      <?php } ?>
      <div id="div06">
      <?php $ent = $this->enterpriseTotal; ?>
        <table style="width: 450px;" class="datatable" cellpadding="1" cellspacing="1" border="0">
          <tr>
            <td colspan="6" class="l_data">【不払い情報】</td>
          </tr>
          <tr>
            <td class="c_label" style="width: 78px">3ヶ月未払い<br />(保証/無保証)</td>
            <td class="c_label" style="width: 68px">3ヶ月請求数</td>
            <td class="c_label" style="width: 78px">3ヶ月不払率<br />(保証/無保証)</td>
            <td class="c_label" style="width: 78px">全体未払い<br />(保証/無保証)</td>
            <td class="c_label" style="width: 64px">全体請求数</td>
            <td class="c_label" style="width: 78px">全体不払率<br />(保証/無保証)</td>
          </tr>
          <tr>
            <?php /* ■3ヶ月未払い */ ?>
            <td class="c_data">
              <?php echo f_br($ent['NpMolecule3']); ?>　件<br />
              <?php echo f_e(sprintf('(%s / %s)', $ent['NpGuaranteeMolecule3'], $ent['NpNoGuaranteeMolecule3'])); ?>
            </td>
            <?php /* ■3ヶ月請求数 */ ?>
            <td class="c_data">
              <?php echo f_br($ent['NpDenominator3']); ?>　件
            </td>
            <?php /* ■3ヶ月不払率 */ ?>
            <?php if(floor($ent['NpRate3']) >= 3) { ?>
              <td class="c_data denominator_backcolor">
            <?php } else { ?>
              <td class="c_data">
            <?php } ?>
            <?php if(($ent['NpRate3']) < 100) {
                  echo f_e(doubleval($ent['NpRate3'])); ?>　％
              <?php } else {
                  echo 100 ?>　％
              <?php    }?><br />
            <?php echo f_e(sprintf('(%s / %s)', doubleval($ent['NpGuaranteeRate3']), doubleval($ent['NpNoGuaranteeRate3']))); ?>
            </td>
            <?php /* ■全体未払い */ ?>
            <td class="c_data">
              <?php echo f_br($ent['NpMoleculeAll']); ?>　件<br />
              <?php echo f_e(sprintf('(%s / %s)', $ent['NpGuaranteeMoleculeAll'], $ent['NpNoGuaranteeMoleculeAll'])); ?>
            </td>
            <?php /* ■全体請求数 */ ?>
            <td class="c_data">
              <?php echo f_br($ent['NpDenominatorAll']); ?>　件
            </td>
            <?php /* ■全体不払率 */ ?>
            <?php if(floor($ent['NpRateAll']) >= 3) { ?>
              <td class="c_data denominator_backcolor">
            <?php } else { ?>
              <td class="c_data">
            <?php } ?>
              <?php if(($ent['NpRateAll']) < 100) {
                  echo f_e(doubleval($ent['NpRateAll'])); ?>　％
              <?php } else {
                  echo 100 ?>　％
              <?php    }?><br />
              <?php echo f_e(sprintf('(%s / %s)', doubleval($ent['NpGuaranteeRateAll']), doubleval($ent['NpNoGuaranteeRateAll']))); ?>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <?php echo $this->render('cbadmin/page_footer.php'); ?>
  </div>
</body>
</html>
