<?php

// HTMLヘッダ
echo $this->render( 'oemmember/document_header.php' );

?>
<style>
.timetable {
	font-size: 12pt;
}

.timetable th {
	background-color: white;
	color: navy;
	font-size: 14pt;
}

.timetable td {
	text-align: center;
	background-color: lightskyblue;
}

</style>
</head>
<body>
<?php
// 共通ページヘッダ
echo $this->render( 'oemmember/page_header.php' );
// ヘッダのメニュー
echo $this->render( 'oemmember/header_menu.php' );

// システムメッセージ
echo $this->render( 'oemmember/system_message.php' );

// ページタイトル
echo $this->render( 'oemmember/page_title.php' );
?>

<center>
	<p>
		注文登録を受け付けました。
	</p>
	<p>
		ご登録いただいたご注文は自動的に与信審査にかけられ、<br />
		営業時間内にご登録いただいたご注文は２時間以内に<br />
		営業時間外にご登録いただいたご注文は通常翌日11時までに<br />
		結果報告のメールをお送りさせていただきます。<br />
		<br />
		営業時間：営業時間：9:00～18:00　年中無休（年末・年始のぞく）
	</p>
	<p>
		与信中のお取引に関しては、検索対象になるまで時間差が生じる場合がございますのであらかじめご了承ください。
	</p>
	<p/>
	<p>
		<a href="index/index">＞＞＞ トップへ戻る</a>
	</p>
</center>

<?php
// フッタメニュー
echo $this->render( 'oemmember/footer_menu.php' );

// 共通ページフッタ
echo $this->render( 'oemmember/page_footer.php' );
?>
</body>
</html>

