<?php
use Coral\Base\BaseHtmlUtils;
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/payingcycle/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">サイクル立替</h3>
    <div id="message" align="center"><?php echo $this->message; ?></div>
      <table width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
            <th>サイクル名称</th>
            <th>締めP</th>
            <th>サイクル種別</th>
            <th>毎週</th>
            <th>日付指定</th>
            <th>立替日種別</th>
            <th>翌週</th>
            <th>翌月</th>
            <th>無効</th>
            <th>　　</th>
          </tr>
          <?php $i = 0; foreach ($this->list as $row) { ?>
          <tr class="data">
            <td  class="l_data">
                <?php echo $row['PayingCycleName']; ?>
            </td>
            <td class="l_data">
                <?php echo $this->code->getMasterCaption(2, $row['FixPattern']);?>
            </td>
            <td class="l_data">
                <?php if($row['PayingDecisionClass'] == 0){echo "毎週";}elseif($row['PayingDecisionClass'] == 1){echo "日付指定";}; ?>
            </td>
            <td class="l_data">
                <?php if($row['PayingDecisionDay'] == NULL){echo "--"; ?>
                <?php }else{ echo $this->code->getMasterCaption(53, $row['PayingDecisionDay']);};?>
            </td>
            <td class="l_data">
                <?php if($row['PayingDecisionDate1']==0){
                        echo "--";
                      }else{
                        echo $this->code->getMasterCaption(76, $row['PayingDecisionDate1']);}
                        echo " / ";
                ?>
                <?php if($row['PayingDecisionDate2']==0){
                        echo "--";
                      }else{
                        echo $this->code->getMasterCaption(76, $row['PayingDecisionDate2']);}
                        echo " / ";
                ?>
                <?php if($row['PayingDecisionDate3']==0){
                        echo "--";
                      }else{
                        echo $this->code->getMasterCaption(76, $row['PayingDecisionDate3']);}
                        echo " / ";
                ?>
                <?php if($row['PayingDecisionDate4']==0){
                        echo "--";
                      }else{
                        echo $this->code->getMasterCaption(76, $row['PayingDecisionDate4']);}
                ?>
            </td>
            <td class="l_data">
                <?php if($row['PayingClass'] == 0){echo "翌週";}; ?>
                <?php if($row['PayingClass'] == 1){echo "翌月";}; ?>
                <?php if($row['PayingClass'] == 2){echo "翌々月";}; ?>
            </td>
            <td class="l_data">
                <?php if($row['PayingDay'] == NULL){echo "--"; ?>
                <?php }else{ echo $this->code->getMasterCaption(53, $row['PayingDay']);};?>
            </td>
            <td class="l_data">
                <?php if($row['PayingMonth']==0){
                        echo "--";
                      }else{
                        echo $this->code->getMasterCaption(77, $row['PayingMonth']);}
                ?>
            </td>
            <td class="l_data">
                <?php if($row['ValidFlg'] == 0){echo "無効";}elseif($row['ValidFlg'] == 1){echo "";}; ?>
            </td>
            <td class="l_data">
                <a href="payingcycle/edit/id/<?php echo $row['PayingCycleId']; ?>">編集</a>
            </td>
          </tr>

          <?php $i++; } ?>
        </tbody>
      </table>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
