<?php
use member\Application;
use Coral\Coral\Validate;
use Coral\Coral\View\CoralViewCommandBar;
use Coral\Coral\View\CommandBar\CoralViewCommandBarButton;
use Coral\Coral\Validate\CoralValidateUtility;
use Coral\Coral\View\Helper\CoralViewHelperValueFormat;
use Zend\Validator;

// HTMLヘッダ
echo $this->render( 'member/document_header.php' );

// アプリケーション名割り当て
$this->applicationTitle = '後払い決済管理システム';

?>
</head>
<body>
<?php
// 共通ページヘッダ
echo $this->render( 'member/page_header.php' );
// ヘッダのメニュー
echo $this->render( 'member/header_menu.php' );

// システムメッセージ
echo $this->render( 'member/system_message.php' );

// ページタイトル
echo $this->render( 'member/page_title.php' );

$formatter = new CoralViewHelperValueFormat();
?>
<?php
// コマンドバー使用
$commandBar = new CoralViewCommandBar(
	// title
	'今日は ' . $this->genzai . ' です。'
);
// コマンドバーのレンダリング
echo $commandBar->render();
?>
<div class="layout_container">
	<div class="summary_title">【ご請求内容】</div>
	<table class="claim_result charge_list_table summary_table" border="1" cellpadding="0" cellspacing="0">
		<tbody>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">立替締め日</td>
				<td class="date_col total_col summary_value_col"><?php echo $this->list['FixedDate']; ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">立替予定日</td>
				<td class="date_col total_col summary_value_col"><?php echo $this->list['ExecScheduleDate']; ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">お取引件数</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['ChargeCount'], '#,##0 件'), '0 件'); ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">立替予想額</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['ChargeAmount'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">決済手数料合計</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['SettlementFee'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">請求手数料合計</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['ClaimFee'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">印紙代合計</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['StampFeeTotal'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">月額固定費</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['MonthlyFee'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">前回持越し分</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['CarryOver'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">キャンセル返金分</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['CalcelAmount'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">口座振込手数料</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['TransferCommission'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">精算調整額</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['AdjustmentAmount'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
<?php if (false) { ?>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">立替精算戻し分</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['PayBackAmount'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
<?php } ?>
			<tr class="summary">
				<td class="seq_col label_col summary_label_col">お振込予定総額</td>
				<td class="money_col total_col summary_value_col"><?php echo nvl(f_nf($this->list['DecisionPayment'], '\ #,##0'), '\ 0'); ?></td>
			</tr>
		</tbody>
	</table>
</div>
<div style="font-size: 9pt; margin: 0px 8px; float: none; clear: both; width: 870px">
	※「印紙代合計」とは、購入者様のコンビニ決済によるお支払金額が2014年4月1日から2019年9月30日までに発行された請求書は税込で\54,000以上、2019年10月1日以降に発行された請求書は税抜で\50,000以上の場合に発生する印紙代金の合計金額です。
</div>
<div class="note">
	<ul>
		<li>
			表示金額はすべて税込金額となっております。
		</li>
		<li>
			決済手数料の1円未満の端数は切捨てとなっております。
		</li>
	</ul>
</div>


<?php
// フッタメニュー
echo $this->render( 'member/footer_menu.php' );

// 共通ページフッタ
echo $this->render( 'member/page_footer.php' );
?>
</body>
<?php echo $this->render('member/tab_support.php'); ?>
<script>
<?php
$app_global = Application::getInstance()->appGlobalConfig;
if( isset( $app_global->page_title_prefix ) ) {
	$page_title_prefix = $app_global->page_title_prefix . ( ( isset( $app_global->page_title_separaotor )) ?
		$app_global->page_title_separator : ' : ' );
} else {
	$page_title_prefix = '';
}
?>
</script>
</html>
