<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/searchf/page_menu.php'); ?>

<!-- start contents -->
<div id="contents">
<h3>オートコールCSVインポート　エラー</h3>
<h4><font color="red"><?php echo $this->error; ?></font></h4>
<table class="datatable" width="860" cellpadding="1" cellspacing="1" border="0">
  <thead>
  </thead>
  <tbody>
  <tr>
    <td colspan="8" class="c_data"><input type="button" value="ファイル取り込みへ戻る" onclick="location.href='searchf/import'" /></td>
  </tr>
  </tbody>
</table>
</div>
  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
