<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<style type="text/css">
<!--
#formdiv {
	margin-left: 25px;
	text-align: center;
}
-->
</style>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/rwsprcpt/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">返金口座情報登録</h3>
    <?php echo $this->errormessage; ?>
    <form name="form" enctype="multipart/form-data" method="post" action="rwsprcpt/lack">
      <div id="formdiv">
      口座情報ファイル　
        <input type="file" name="cres" size="80" />
        <p><button type="submit">　　インポート　　</button></p>
      </div>
    </form>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>