<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/operator/page_menu2.php'); ?>

<!-- start contents -->
<div id="contents">
<h3>パスワード変更</h3>
<h4><div align="center">変更しました。</div></h4>
</div>
  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
