<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<style type="text/css">
td.l_data,
td.r_data,
td.c_data {
  padding-top: 0;
  padding-bottom: 0;
  line-height: 1.5;
}
td.l_data *,
td.r_data *,
td.c_data * {
  line-height: 1.5;
}
td.act-col a {
  display: block;
  width: 80px;
  margin: 1px;
}
td.act-col a:hover {
  background-color: azure;
}
tr.my-account td.id-col {
  background-color: #ffee00;
}
table.datatable tr.disabled,
table.datatable tr.disabled td {
background-color: silver;
}
</style>
<script type="text/javascript">
var myId = <?php echo f_e($this->userInfo->OpId); ?>;
function resetpsw(opId) {
  if(opId == myId) {
    window.location.href = '{0}/operator/chgpw'.format(
      (document.getElementsByTagName('base')[0] || { href : '' }).href.replace(/\/*$/, '')
    );
    return;
  }
  if(confirm('パスワードリセットを実行しますか？')) {
    var url = '{0}/operator/resetpsw/opid/{1}'.format(
      (document.getElementsByTagName('base')[0] || { href : '' }).href.replace(/\/*$/, ''),
      opId);
    window.location.href = url;
  }
  return false;
}
</script>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/operator/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">オペレーター一覧</h3>
      <table width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <thead>
          <tr>
            <th style="width: 30px" rowspan="2">ID</th>
            <th style="width: 280px" rowspan="2">ログインID</th>
            <th style="width: 180px">氏名</th>
            <th style="width: 120px" rowspan="2">所属</th>
            <th style="width: 90px" rowspan="2">権限</th>
            <th style="width: 70px" rowspan="2">PSW更新</th>
            <th style="width: 83px" rowspan="2">操作</th>
          </tr>
          <tr>
            <th>氏名カナ</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->list as $row) { ?>
          <?php     $is_invalid = ($row['ValidFlg']) ? false : true; ?>
          <tr class="data<?php if($row['OpId'] == $this->userInfo->OpId) echo ' my-account'; ?><?php if($is_invalid) echo ' disabled'; ?>">
            <td class="r_data id-col" rowspan="2"><?php echo f_e($row['OpId']); ?></td>
            <td class="l_data" rowspan="2"><?php echo f_e($row['LoginId']); ?></td>
            <td class="l_data"><?php echo f_e($row['NameKj']); ?></td>
            <td class="l_data" rowspan="2"><?php echo f_e($row['Division']); ?></td>
            <td class="l_data" rowspan="2"><?php echo f_e($this->codeMaster->getRoleCodeCaption($row['RoleCode'])); ?></td>
            <td class="c_data" rowspan="2"><?php echo $row['LastPasswordChanged'] ? f_df($row['LastPasswordChanged'], 'y/m/d') : '-'; ?></td>
            <td class="c_data act-col">
              <a href="operator/edit/opid/<?php echo $row['OpId']; ?>">編集</a>
            </td>
          </tr>
          <tr class="data<?php if($row['OpId'] == $this->userInfo->OpId) echo ' my-account'; ?><?php if($is_invalid) echo ' disabled'; ?>">
            <td class="l_data"><?php echo $row['NameKn'] ? f_e($row['NameKn']) : '&nbsp;'; ?></td>
            <td class="c_data act-col">
            <?php if($row['OpId'] == $this->userInfo->OpId) { ?>
              <a href="operator/chgpw">PSW 変更</a>
            <?php } else { ?>
              <a href="javascript:void(0)" onclick="return resetpsw(<?php echo f_e($row['OpId']); ?>)">PSW リセット</a>
            <?php } ?>
            </td>
          </tr>
          <tr class="border">
            <td colspan="8">
              <img src="../images/spacer_gray.gif" height="1" width="1">
            </td>
          </tr>
        <?php } ?>
        </tbody>
      </table>
    </div>
    <!-- end contents -->

    <?php echo $this->render('cbadmin/page_footer.php'); ?>
  </div>
</body>
</html>
