<?php
// HTMLヘッダ
echo $this->render( 'oemmypage/document_header_sp.php' );

// アプリケーション名割り当て
$this->applicationTitle = '顧客マイページ';
?>
</head>
<body>
<div id="wrapper">
<?php
// 共通ページヘッダ
echo $this->render( 'oemmypage/page_header_sp.php' );

// システムメッセージ
echo $this->render( 'oemmypage/system_message_sp.php' );

?>
<!-- start contents -->
    <div id="contents">
        <div style="clear: both;" id="my_title">アップロード完了</div>
        <div id="d_01">身分証明証のアップロードが完了致しました。<br />
            身分証明証の確認には数営業日かかります。
        </div>
        <div style="width: 96%;margin-left: 15px"><input id="green_btn" type="submit" value="トップへ" onclick="location.href='<?php echo $this->baseUrl; ?>/index/index'" /></div>
    </div>
<!-- end contents -->
<?php
// 共通メニュー
echo $this->render( 'oemmypage/menu_sp.php' );

// 共通ページフッタ
echo $this->render( 'oemmypage/page_footer_sp.php' );
?>

</div>
</body>
</html>
