CREATE TABLE `AW_AccountsDue_DailyAccount2` (
  `Seq` BIGINT NOT NULL AUTO_INCREMENT,
  `ReceiptDate` DATE NULL,
  `DepositDate` DATE NULL,
  `ReceiptMonth` DATE NULL,
  `CheckingUseAmount` BIGINT NOT NULL DEFAULT 0,
  `CheckingDamageInterestAmount` BIGINT NOT NULL DEFAULT 0,
  `CheckingClaimFee` BIGINT NOT NULL DEFAULT 0,
  `ReceiptAgentId` BIGINT NULL,
  `BranchBankId` BIGINT NULL,
  `AccountNumber` BIGINT NULL,
  `ClassDetails` INT NULL,
  `ReceiptClass` INT NULL,
  `DailySummaryFlg` TINYINT NOT NULL DEFAULT 0,
  `ValidFlg` INT NOT NULL DEFAULT 1,
  `OemId` BIGINT NULL,
  `EnterpriseId` BIGINT NULL,
  `OrderSeq` BIGINT NULL,
  `OrderId` VARCHAR(50) NULL,
  `ReceiptSeq` BIGINT NULL,
  `ReceiptSeq2` BIGINT NULL,
  `Rct_CancelFlg` INT NULL,
  `TargetFlg` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Seq`));


CREATE TABLE `AW_SuspensePayments_DailyAccount2` (
  `Seq` BIGINT NOT NULL AUTO_INCREMENT,
  `ReceiptDate` DATE NULL,
  `DepositDate` DATE NULL,
  `ReceiptMonth` DATE NULL,
  `CheckingUseAmount` BIGINT NOT NULL DEFAULT 0,
  `CheckingDamageInterestAmount` BIGINT NOT NULL DEFAULT 0,
  `CheckingClaimFee` BIGINT NOT NULL DEFAULT 0,
  `ReceiptAgentId` BIGINT NULL,
  `BranchBankId` BIGINT NULL,
  `AccountNumber` BIGINT NULL,
  `ClassDetails` INT NULL,
  `ReceiptClass` INT NULL,
  `DailySummaryFlg` TINYINT NOT NULL DEFAULT 0,
  `ValidFlg` INT NOT NULL DEFAULT 1,
  `OemId` BIGINT NULL,
  `EnterpriseId` BIGINT NULL,
  `OrderSeq` BIGINT NULL,
  `OrderId` VARCHAR(50) NULL,
  `ReceiptSeq` BIGINT NULL,
  `ReceiptSeq2` BIGINT NULL,
  `Rct_CancelFlg` INT NULL,
  `TargetFlg` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Seq`));


CREATE TABLE `AW_MishukinHikeiMonth` (
  `Seq` bigint(20) NOT NULL AUTO_INCREMENT,
  `ProcessingDate` date DEFAULT NULL,
  `ReceiptDate` date DEFAULT NULL,
  `DepositDate` date DEFAULT NULL,
  `PaymentAccountTitle` varchar(30) DEFAULT NULL,
  `PaymentTargetAccountTitle` varchar(30) DEFAULT NULL,
  `Amount` bigint(20) DEFAULT NULL,
  `OemId` varchar(30) DEFAULT NULL,
  `SUMType` int(11) DEFAULT NULL,
  `EnterpriseId` bigint(20) DEFAULT NULL,
  `OutType` int(11) DEFAULT NULL,
  `OrderSeq` bigint(20) DEFAULT NULL,
  `TargetFlg` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Seq`),
  KEY `Idx_AW_MishukinHikeiMonth` (`OrderSeq`)
);

CREATE TABLE `AW_KaribaraikinHikeiMonth` (
  `Seq` bigint(20) NOT NULL AUTO_INCREMENT,
  `ProcessingDate` date DEFAULT NULL,
  `ReceiptDate` date DEFAULT NULL,
  `DepositDate` date DEFAULT NULL,
  `PaymentAccountTitle` varchar(30) DEFAULT NULL,
  `PaymentTargetAccountTitle` varchar(30) DEFAULT NULL,
  `Amount` bigint(20) DEFAULT NULL,
  `OemId` varchar(30) DEFAULT NULL,
  `SUMType` int(11) DEFAULT NULL,
  `EnterpriseId` bigint(20) DEFAULT NULL,
  `OutType` int(11) DEFAULT NULL,
  `OrderSeq` bigint(20) DEFAULT NULL,
  `TargetFlg` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Seq`),
  KEY `Idx_AW_KaribaraikinHikeiMonth` (`OrderSeq`)
);
