CREATE TABLE `AT_PayOff_DailyAccount2` (
  `Seq` bigint(20) NOT NULL AUTO_INCREMENT,
  `DailyMonthlyFlg` int(11) DEFAULT NULL,
  `ProcessingDate` date DEFAULT NULL,
  `OemId` bigint(20) DEFAULT NULL,
  `OemNameKj` varchar(160) DEFAULT NULL,
  `EnterpriseId` bigint(20) DEFAULT NULL,
  `EnterpriseNameKj` varchar(160) DEFAULT NULL,
  `MerchantNumber` bigint(20) DEFAULT NULL,
  `AdvancesDate` date DEFAULT NULL,
  `AdvancesAmount` bigint(20) DEFAULT NULL,
  `EnterpriseAccountsDue` bigint(20) DEFAULT NULL,
  `AccountsPayablePending` bigint(20) DEFAULT NULL,
  `ClaimAndObligationsDecision` bigint(20) DEFAULT NULL,
  `UseAmount` bigint(20) DEFAULT NULL,
  `CancelAmount` bigint(20) DEFAULT NULL,
  `UseSettlementBackOffse` bigint(20) DEFAULT NULL,
  `AccountsPayableTotal` bigint(20) DEFAULT NULL,
  `SettlementFee` bigint(20) DEFAULT NULL,
  `ClaimFee` bigint(20) DEFAULT NULL,
  `MonthlyFee` bigint(20) DEFAULT NULL,
  `IncludeMonthlyFee` bigint(20) DEFAULT NULL,
  `ApiMonthlyFee` bigint(20) DEFAULT NULL,
  `CreditNoticeMonthlyFee` bigint(20) DEFAULT NULL,
  `NextClaimCreditNoticeMonthlyFee` bigint(20) DEFAULT NULL,
  `AccountsReceivableTotal` bigint(20) DEFAULT NULL,
  `StampFeeCount` bigint(20) DEFAULT NULL,
  `StampFee` bigint(20) DEFAULT NULL,
  `TransferCommissionCount` bigint(20) DEFAULT NULL,
  `TransferCommission` bigint(20) DEFAULT NULL,
  `AdjustmentAmountCount` bigint(20) DEFAULT NULL,
  `AdjustmentAmount` bigint(20) DEFAULT NULL,
  `EnterpriseRefundCount` bigint(20) DEFAULT NULL,
  `EnterpriseRefund` bigint(20) DEFAULT NULL,
  `AccountsDueOffsetAmount` bigint(20) DEFAULT NULL,
  `AccountsPayablePendingAmount` bigint(20) DEFAULT NULL,
  `AdvancesFixedDate` date DEFAULT NULL,
  `RegistDate` datetime DEFAULT NULL,
  `RegistId` int(11) DEFAULT NULL,
  `UpdateDate` datetime DEFAULT NULL,
  `UpdateId` int(11) DEFAULT NULL,
  `ValidFlg` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Seq`),
  KEY `Idx_AT_PayOff_DailyAccount01` (`ProcessingDate`),
  KEY `Idx_AT_PayOff_DailyAccount02` (`EnterpriseId`)
);
