--------------------------------------------------------------------------------
-- 以下、本体側スキーマへ登録
--------------------------------------------------------------------------------
-- マイページ側スキーマを本体スキーマのビューへ(※事前に[マイページ側スキーマへ登録]実施のこと)
DROP VIEW IF EXISTS `MPV_MypageCustomer`;
CREATE VIEW `MPV_MypageCustomer` AS SELECT * FROM coraldb_mypage01.T_MypageCustomer;

INSERT INTO `T_MailTemplate` (`Class`,`ClassName`,`FromTitle`,`FromTitleMime`,`FromAddress`,`ToTitle`,`ToTitleMime`,`ToAddress`,`Subject`,`SubjectMime`,`Body`,`OemId`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) VALUES (92,'マイページパスワード再発行メール（PC）','後払いドットコム','=?UTF-8?B?GyRCOGVKJyQkJUklQyVIJTMlYBsoQg==?=','customer@ato-barai.com',NULL,NULL,NULL,'【後払いドットコム】パスワード再発行のご案内','=?UTF-8?B?5b6M5omV44GE44OJ44OD44OI44Kz44Og?=','この度は後払いドットコムをご利用いただき\r\nまことにありがとうございます。\r\n\r\n下記のURLをクリックして後払いドットコムでの\r\nパスワード再設定を進めてください。\r\n\r\n{MypagePasswordResetUrl}\r\n\r\n\r\n＜ご注意事項＞\r\n・本メールをお受け取り後、２４時間以内にパスワード再設定を\r\n完了していただきますようお願いいたします。\r\n・２４時間以内にパスワード再設定が完了されない場合はお手続きが無効と\r\nなりますのであらかじめご了承願います。\r\n・２４時間を過ぎてしまった場合は、恐れ入りますが再度再発行のお手続きを\r\nお願いいたします。\r\n\r\n\r\n------------------------------------\r\n再設定の手順について\r\n------------------------------------\r\n\r\n１.上記URLにアクセスし、画面にしたがって必要事項をご入力ください。\r\n\r\n２.ご入力内容をご確認のうえ、新しいパスワードを登録してください。\r\n\r\n以上でパスワード再設定完了となります。\r\n\r\n\r\n------------------------------------\r\n再設定がうまくいかない場合は、\r\n大変恐れ入りますがcustomer@ato-barai.comまで\r\nお問い合わせをお願いいたします。\r\n\r\n※営業時間外のお問い合わせにつきましては\r\nご返信にお時間をいただく場合がございます。\r\n\r\n\r\nこの度はご利用ありがとうございました。\r\n\r\n\r\n--------------------------------------------------------------\r\n後払い請求代行サービス【後払いドットコム】\r\n\r\n  お問合せ先：03-5909-3490\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: customer@ato-barai.com\r\n  \r\n　運営会社：株式会社キャッチボール\r\n　住所：〒160-0023 東京都新宿区西新宿6-14-1 新宿グリーンタワービル14F\r\n--------------------------------------------------------------',0,'2017-03-02 16:00:00',1,'2017-03-02 16:17:24',83,1);
INSERT INTO `T_MailTemplate` (`Class`,`ClassName`,`FromTitle`,`FromTitleMime`,`FromAddress`,`ToTitle`,`ToTitleMime`,`ToAddress`,`Subject`,`SubjectMime`,`Body`,`OemId`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) VALUES (93,'マイページパスワード再発行メール（CEL）','後払いドットコム','=?UTF-8?B?GyRCOGVKJyQkJUklQyVIJTMlYBsoQg==?=','customer@ato-barai.com',NULL,NULL,NULL,'【後払いドットコム】パスワード再発行のご案内','=?UTF-8?B?5b6M5omV44GE44OJ44OD44OI44Kz44Og?=','この度は後払いドットコムをご利用いただき\r\nまことにありがとうございます。\r\n\r\n下記のURLをクリックして後払いドットコムでの\r\nパスワード再設定を進めてください。\r\n\r\n{MypagePasswordResetUrl}\r\n\r\n\r\n＜ご注意事項＞\r\n・本メールをお受け取り後、２４時間以内にパスワード再設定を\r\n完了していただきますようお願いいたします。\r\n・２４時間以内にパスワード再設定が完了されない場合はお手続きが無効と\r\nなりますのであらかじめご了承願います。\r\n・２４時間を過ぎてしまった場合は、恐れ入りますが再度再発行のお手続きを\r\nお願いいたします。\r\n\r\n\r\n------------------------------------\r\n再設定の手順について\r\n------------------------------------\r\n\r\n１.上記URLにアクセスし、画面にしたがって必要事項をご入力ください。\r\n\r\n２.ご入力内容をご確認のうえ、新しいパスワードを登録してください。\r\n\r\n以上でパスワード再設定完了となります。\r\n\r\n\r\n------------------------------------\r\n再設定がうまくいかない場合は、\r\n大変恐れ入りますがcustomer@ato-barai.comまで\r\nお問い合わせをお願いいたします。\r\n\r\n※営業時間外のお問い合わせにつきましては\r\nご返信にお時間をいただく場合がございます。\r\n\r\n\r\nこの度はご利用ありがとうございました。\r\n\r\n\r\n--------------------------------------------------------------\r\n後払い請求代行サービス【後払いドットコム】\r\n\r\n  お問合せ先：03-5909-3490\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: customer@ato-barai.com\r\n  \r\n　運営会社：株式会社キャッチボール\r\n　住所：〒160-0023 東京都新宿区西新宿6-14-1 新宿グリーンタワービル14F\r\n--------------------------------------------------------------',0,'2017-03-02 16:00:00',1,'2017-03-02 16:17:41',83,1);
INSERT INTO `T_MailTemplate` (`Class`,`ClassName`,`FromTitle`,`FromTitleMime`,`FromAddress`,`ToTitle`,`ToTitleMime`,`ToAddress`,`Subject`,`SubjectMime`,`Body`,`OemId`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) VALUES (92,'マイページパスワード再発行メール（PC）','後払い決済サービス','=?UTF-8?B?GyRCOGVKJyQkN2g6USU1ITwlUyU5GyhC?=','sfc-atobarai@seino.co.jp',NULL,NULL,NULL,'【後払い決済マイページ】パスワード再発行のご案内','=?UTF-8?B?5b6M5omV44GE5rG65riI44K144O844OT44K5?=','この度は【後払い決済マイページ】をご利用いただき\r\nまことにありがとうございます。\r\n\r\n下記のURLをクリックして【後払い決済マイページ】での\r\nパスワード再設定を進めてください。\r\n\r\n{MypagePasswordResetUrl}\r\n\r\n\r\n＜ご注意事項＞\r\n・本メールをお受け取り後、２４時間以内にパスワード再設定を\r\n完了していただきますようお願いいたします。\r\n・２４時間以内にパスワード再設定が完了されない場合はお手続きが無効と\r\nなりますのであらかじめご了承願います。\r\n・２４時間を過ぎてしまった場合は、恐れ入りますが再度再発行のお手続きを\r\nお願いいたします。\r\n\r\n\r\n------------------------------------\r\n再設定の手順について\r\n------------------------------------\r\n\r\n１.上記URLにアクセスし、画面にしたがって必要事項をご入力ください。\r\n\r\n２.ご入力内容をご確認のうえ、新しいパスワードを登録してください。\r\n\r\n以上でパスワード再設定完了となります。\r\n\r\n\r\n------------------------------------\r\n再設定がうまくいかない場合は、\r\n大変恐れ入りますがsfc-atobarai@seino.co.jpまで\r\nお問い合わせをお願いいたします。\r\n\r\n※営業時間外のお問い合わせにつきましては\r\nご返信にお時間をいただく場合がございます。\r\n\r\n\r\nこの度はご利用ありがとうございました。\r\n\r\n\r\n--------------------------------------------------------------\r\n\r\n【後払い決済サービス】\r\n  お問合せ先：03-5909-4500\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: sfc-atobarai@seino.co.jp\r\n\r\n  運営会社：セイノーフィナンシャル株式会社\r\n　住所：〒503-8501 岐阜県大垣市田口町１番地\r\n\r\n--------------------------------------------------------------',3,'2017-03-06 10:50:00',1,'2017-03-06 10:57:58',83,1);
INSERT INTO `T_MailTemplate` (`Class`,`ClassName`,`FromTitle`,`FromTitleMime`,`FromAddress`,`ToTitle`,`ToTitleMime`,`ToAddress`,`Subject`,`SubjectMime`,`Body`,`OemId`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) VALUES (93,'マイページパスワード再発行メール（CEL）','後払い決済サービス','=?UTF-8?B?GyRCOGVKJyQkN2g6USU1ITwlUyU5GyhC?=','sfc-atobarai@seino.co.jp',NULL,NULL,NULL,'【後払い決済マイページ】パスワード再発行のご案内','=?UTF-8?B?5b6M5omV44GE5rG65riI44K144O844OT44K5?=','この度は【後払い決済マイページ】をご利用いただき\r\nまことにありがとうございます。\r\n\r\n下記のURLをクリックして【後払い決済マイページ】での\r\nパスワード再設定を進めてください。\r\n\r\n{MypagePasswordResetUrl}\r\n\r\n\r\n＜ご注意事項＞\r\n・本メールをお受け取り後、２４時間以内にパスワード再設定を\r\n完了していただきますようお願いいたします。\r\n・２４時間以内にパスワード再設定が完了されない場合はお手続きが無効と\r\nなりますのであらかじめご了承願います。\r\n・２４時間を過ぎてしまった場合は、恐れ入りますが再度再発行のお手続きを\r\nお願いいたします。\r\n\r\n\r\n------------------------------------\r\n再設定の手順について\r\n------------------------------------\r\n\r\n１.上記URLにアクセスし、画面にしたがって必要事項をご入力ください。\r\n\r\n２.ご入力内容をご確認のうえ、新しいパスワードを登録してください。\r\n\r\n以上でパスワード再設定完了となります。\r\n\r\n\r\n------------------------------------\r\n再設定がうまくいかない場合は、\r\n大変恐れ入りますがsfc-atobarai@seino.co.jpまで\r\nお問い合わせをお願いいたします。\r\n\r\n※営業時間外のお問い合わせにつきましては\r\nご返信にお時間をいただく場合がございます。\r\n\r\n\r\nこの度はご利用ありがとうございました。\r\n\r\n\r\n--------------------------------------------------------------\r\n\r\n【後払い決済サービス】\r\n  お問合せ先：03-5909-4500\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: sfc-atobarai@seino.co.jp\r\n\r\n  運営会社：セイノーフィナンシャル株式会社\r\n　住所：〒503-8501 岐阜県大垣市田口町１番地\r\n\r\n--------------------------------------------------------------',3,'2017-03-06 10:50:00',1,'2017-03-06 10:58:20',83,1);

-- 会員IDを忘れた方用URL
INSERT INTO T_SystemProperty(Module, Category, Name, PropValue, Description, RegistDate, RegistId, UpdateDate, UpdateId, ValidFlg
) VALUES( 'mypage','application_global', 'faq_link', 'https://atobarai-user.jp/faq/atobarai/193/', '会員IDを忘れた方用URL', NOW(), 9, NOW(), 9, '1');


--------------------------------------------------------------------------------
-- 以下、マイページ側スキーマへ登録
--------------------------------------------------------------------------------
ALTER TABLE `T_MypageCustomer` 
ADD COLUMN `AccessKey` VARCHAR(100) NULL AFTER `NgAccessReferenceDate`,
ADD COLUMN `AccessKeyValidToDate` DATETIME NULL AFTER `AccessKey`,
ADD COLUMN `Reserve` TEXT NULL DEFAULT NULL AFTER `AccessKeyValidToDate`;

ALTER TABLE `T_MypageCustomer` ADD INDEX `idx_02` (`AccessKey` ASC);

UPDATE T_MypageCustomer t
SET t.ManCustId = (SELECT MAX(ManCustId) FROM MV_ManagementCustomer WHERE MailAddress = t.MailAddress AND RegNameKj = t.RegNameKj AND RegUnitingAddress = t.RegUnitingAddress AND RegPhone IN (t.RegPhone, t.RegMobilePhone))
WHERE t.ManCustId IS NULL;
