/* 与信結果ログに不払い日数関連項目の追加 */
ALTER TABLE `T_CreditLog`
ADD COLUMN `Def_CpId206_Point` int(11) DEFAULT NULL AFTER `Def_CpId203_Point`;

ALTER TABLE `T_CreditLog`
ADD COLUMN `Org_CpId206_Point` int(11) DEFAULT NULL AFTER `Org_CpId203_Point`;

ALTER TABLE `T_CreditLog`
ADD COLUMN `Jud_NonPaymentDaysScore` int(11) DEFAULT NULL AFTER `Jud_SaikenCancelYN`;

ALTER TABLE `T_CreditLog`
ADD COLUMN `Jud_NonPaymentDaysYN` tinyint(4) DEFAULT NULL AFTER `Jud_NonPaymentDaysScore`;

/* 社内与信ポイントマスタに不払い日数（CB標準）を追加 */
INSERT INTO M_CreditPoint VALUES ( 0 , 206, '不払い日数', 10, NULL, 'NGとする不払い日数（0はチェック対象外とする）', 8, NULL, NULL, 'CB標準', 1.0, NOW(), 9, NOW(), 9, 1);

/* テンプレートフィールド：主キーの繰り下げ */
UPDATE M_TemplateField SET ListNumber = 171 WHERE TemplateSeq = 47 AND  PhysicalName = 'ManualJudge-JintecManualJudgeSns';
UPDATE M_TemplateField SET ListNumber = 170 WHERE TemplateSeq = 47 AND  PhysicalName = 'ManualJudge-NonPaymentFlg';
UPDATE M_TemplateField SET ListNumber = 169 WHERE TemplateSeq = 47 AND  PhysicalName = 'ManualJudge-UnpaidFlg';
UPDATE M_TemplateField SET ListNumber = 168 WHERE TemplateSeq = 47 AND  PhysicalName = 'NonPaymentCount_OtherSite';
UPDATE M_TemplateField SET ListNumber = 167 WHERE TemplateSeq = 47 AND  PhysicalName = 'NonPaymentCount_Site';
UPDATE M_TemplateField SET ListNumber = 166 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_70';
UPDATE M_TemplateField SET ListNumber = 165 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_70';
UPDATE M_TemplateField SET ListNumber = 164 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_69';
UPDATE M_TemplateField SET ListNumber = 163 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_69';
UPDATE M_TemplateField SET ListNumber = 162 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_68';
UPDATE M_TemplateField SET ListNumber = 161 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_68';
UPDATE M_TemplateField SET ListNumber = 160 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_67';
UPDATE M_TemplateField SET ListNumber = 159 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_67';
UPDATE M_TemplateField SET ListNumber = 158 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_66';
UPDATE M_TemplateField SET ListNumber = 157 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_66';
UPDATE M_TemplateField SET ListNumber = 156 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_65';
UPDATE M_TemplateField SET ListNumber = 155 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_65';
UPDATE M_TemplateField SET ListNumber = 154 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_64';
UPDATE M_TemplateField SET ListNumber = 153 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_64';
UPDATE M_TemplateField SET ListNumber = 152 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_63';
UPDATE M_TemplateField SET ListNumber = 151 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_63';
UPDATE M_TemplateField SET ListNumber = 150 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_62';
UPDATE M_TemplateField SET ListNumber = 149 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_62';
UPDATE M_TemplateField SET ListNumber = 148 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_61';
UPDATE M_TemplateField SET ListNumber = 147 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_61';
UPDATE M_TemplateField SET ListNumber = 146 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_60';
UPDATE M_TemplateField SET ListNumber = 145 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_60';
UPDATE M_TemplateField SET ListNumber = 144 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_59';
UPDATE M_TemplateField SET ListNumber = 143 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_59';
UPDATE M_TemplateField SET ListNumber = 142 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_58';
UPDATE M_TemplateField SET ListNumber = 141 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_58';
UPDATE M_TemplateField SET ListNumber = 140 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_57';
UPDATE M_TemplateField SET ListNumber = 139 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_57';
UPDATE M_TemplateField SET ListNumber = 138 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_56';
UPDATE M_TemplateField SET ListNumber = 137 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_56';
UPDATE M_TemplateField SET ListNumber = 136 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_55';
UPDATE M_TemplateField SET ListNumber = 135 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_55';
UPDATE M_TemplateField SET ListNumber = 134 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_54';
UPDATE M_TemplateField SET ListNumber = 133 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_54';
UPDATE M_TemplateField SET ListNumber = 132 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_53';
UPDATE M_TemplateField SET ListNumber = 131 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_53';
UPDATE M_TemplateField SET ListNumber = 130 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_52';
UPDATE M_TemplateField SET ListNumber = 129 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_52';
UPDATE M_TemplateField SET ListNumber = 128 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_51';
UPDATE M_TemplateField SET ListNumber = 127 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_51';
UPDATE M_TemplateField SET ListNumber = 126 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_50';
UPDATE M_TemplateField SET ListNumber = 125 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_50';
UPDATE M_TemplateField SET ListNumber = 124 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_49';
UPDATE M_TemplateField SET ListNumber = 123 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_49';
UPDATE M_TemplateField SET ListNumber = 122 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_48';
UPDATE M_TemplateField SET ListNumber = 121 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_48';
UPDATE M_TemplateField SET ListNumber = 120 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_47';
UPDATE M_TemplateField SET ListNumber = 119 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_47';
UPDATE M_TemplateField SET ListNumber = 118 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_46';
UPDATE M_TemplateField SET ListNumber = 117 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_46';
UPDATE M_TemplateField SET ListNumber = 116 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_45';
UPDATE M_TemplateField SET ListNumber = 115 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_45';
UPDATE M_TemplateField SET ListNumber = 114 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_44';
UPDATE M_TemplateField SET ListNumber = 113 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_44';
UPDATE M_TemplateField SET ListNumber = 112 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_43';
UPDATE M_TemplateField SET ListNumber = 111 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_43';
UPDATE M_TemplateField SET ListNumber = 110 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_42';
UPDATE M_TemplateField SET ListNumber = 109 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_42';
UPDATE M_TemplateField SET ListNumber = 108 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_41';
UPDATE M_TemplateField SET ListNumber = 107 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_41';
UPDATE M_TemplateField SET ListNumber = 106 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_40';
UPDATE M_TemplateField SET ListNumber = 105 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_40';
UPDATE M_TemplateField SET ListNumber = 104 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_39';
UPDATE M_TemplateField SET ListNumber = 103 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_39';
UPDATE M_TemplateField SET ListNumber = 102 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_38';
UPDATE M_TemplateField SET ListNumber = 101 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_38';
UPDATE M_TemplateField SET ListNumber = 100 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_37';
UPDATE M_TemplateField SET ListNumber = 99 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_37';
UPDATE M_TemplateField SET ListNumber = 98 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_36';
UPDATE M_TemplateField SET ListNumber = 97 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_36';
UPDATE M_TemplateField SET ListNumber = 96 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_35';
UPDATE M_TemplateField SET ListNumber = 95 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_35';
UPDATE M_TemplateField SET ListNumber = 94 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_34';
UPDATE M_TemplateField SET ListNumber = 93 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_34';
UPDATE M_TemplateField SET ListNumber = 92 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_33';
UPDATE M_TemplateField SET ListNumber = 91 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_33';
UPDATE M_TemplateField SET ListNumber = 90 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_32';
UPDATE M_TemplateField SET ListNumber = 89 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_32';
UPDATE M_TemplateField SET ListNumber = 88 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_31';
UPDATE M_TemplateField SET ListNumber = 87 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_31';
UPDATE M_TemplateField SET ListNumber = 86 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_30';
UPDATE M_TemplateField SET ListNumber = 85 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_30';
UPDATE M_TemplateField SET ListNumber = 84 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_29';
UPDATE M_TemplateField SET ListNumber = 83 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_29';
UPDATE M_TemplateField SET ListNumber = 82 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_28';
UPDATE M_TemplateField SET ListNumber = 81 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_28';
UPDATE M_TemplateField SET ListNumber = 80 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_27';
UPDATE M_TemplateField SET ListNumber = 79 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_27';
UPDATE M_TemplateField SET ListNumber = 78 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_26';
UPDATE M_TemplateField SET ListNumber = 77 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_26';
UPDATE M_TemplateField SET ListNumber = 76 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_25';
UPDATE M_TemplateField SET ListNumber = 75 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_25';
UPDATE M_TemplateField SET ListNumber = 74 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_24';
UPDATE M_TemplateField SET ListNumber = 73 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_24';
UPDATE M_TemplateField SET ListNumber = 72 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_23';
UPDATE M_TemplateField SET ListNumber = 71 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_23';
UPDATE M_TemplateField SET ListNumber = 70 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_22';
UPDATE M_TemplateField SET ListNumber = 69 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_22';
UPDATE M_TemplateField SET ListNumber = 68 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_21';
UPDATE M_TemplateField SET ListNumber = 67 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_21';
UPDATE M_TemplateField SET ListNumber = 66 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_20';
UPDATE M_TemplateField SET ListNumber = 65 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_20';
UPDATE M_TemplateField SET ListNumber = 64 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_19';
UPDATE M_TemplateField SET ListNumber = 63 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_19';
UPDATE M_TemplateField SET ListNumber = 62 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_18';
UPDATE M_TemplateField SET ListNumber = 61 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_18';
UPDATE M_TemplateField SET ListNumber = 60 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_17';
UPDATE M_TemplateField SET ListNumber = 59 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_17';
UPDATE M_TemplateField SET ListNumber = 58 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_16';
UPDATE M_TemplateField SET ListNumber = 57 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_16';
UPDATE M_TemplateField SET ListNumber = 56 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_15';
UPDATE M_TemplateField SET ListNumber = 55 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_15';
UPDATE M_TemplateField SET ListNumber = 54 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_14';
UPDATE M_TemplateField SET ListNumber = 53 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_14';
UPDATE M_TemplateField SET ListNumber = 52 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_13';
UPDATE M_TemplateField SET ListNumber = 51 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_13';
UPDATE M_TemplateField SET ListNumber = 50 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_12';
UPDATE M_TemplateField SET ListNumber = 49 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_12';
UPDATE M_TemplateField SET ListNumber = 48 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_11';
UPDATE M_TemplateField SET ListNumber = 47 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_11';
UPDATE M_TemplateField SET ListNumber = 46 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_10';
UPDATE M_TemplateField SET ListNumber = 45 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_10';
UPDATE M_TemplateField SET ListNumber = 44 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_9';
UPDATE M_TemplateField SET ListNumber = 43 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_9';
UPDATE M_TemplateField SET ListNumber = 42 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_8';
UPDATE M_TemplateField SET ListNumber = 41 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_8';
UPDATE M_TemplateField SET ListNumber = 40 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_7';
UPDATE M_TemplateField SET ListNumber = 39 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_7';
UPDATE M_TemplateField SET ListNumber = 38 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_6';
UPDATE M_TemplateField SET ListNumber = 37 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_6';
UPDATE M_TemplateField SET ListNumber = 36 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_5';
UPDATE M_TemplateField SET ListNumber = 35 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_5';
UPDATE M_TemplateField SET ListNumber = 34 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_4';
UPDATE M_TemplateField SET ListNumber = 33 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_4';
UPDATE M_TemplateField SET ListNumber = 32 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_3';
UPDATE M_TemplateField SET ListNumber = 31 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_3';
UPDATE M_TemplateField SET ListNumber = 30 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_2';
UPDATE M_TemplateField SET ListNumber = 29 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_2';
UPDATE M_TemplateField SET ListNumber = 28 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-ScoreRate_1';
UPDATE M_TemplateField SET ListNumber = 27 WHERE TemplateSeq = 47 AND  PhysicalName = 'Judge-DetectionPatternID_1';
UPDATE M_TemplateField SET ListNumber = 26 WHERE TemplateSeq = 47 AND  PhysicalName = 'Core-Delivery-ScoreRate';
UPDATE M_TemplateField SET ListNumber = 25 WHERE TemplateSeq = 47 AND  PhysicalName = 'Core-OrderItem-ScoreRate';
UPDATE M_TemplateField SET ListNumber = 24 WHERE TemplateSeq = 47 AND  PhysicalName = 'Core-Customer-ScoreRate';
UPDATE M_TemplateField SET ListNumber = 23 WHERE TemplateSeq = 47 AND  PhysicalName = 'CoreSystemHoldMIN';
UPDATE M_TemplateField SET ListNumber = 22 WHERE TemplateSeq = 47 AND  PhysicalName = 'CoreSystemHoldMAX';
UPDATE M_TemplateField SET ListNumber = 21 WHERE TemplateSeq = 47 AND  PhysicalName = 'JudgeSystemHoldMIN';
UPDATE M_TemplateField SET ListNumber = 20 WHERE TemplateSeq = 47 AND  PhysicalName = 'JudgeSystemHoldMAX';
UPDATE M_TemplateField SET ListNumber = 19 WHERE TemplateSeq = 47 AND  PhysicalName = 'NonPaymentTotal-Score';
UPDATE M_TemplateField SET ListNumber = 18 WHERE TemplateSeq = 47 AND  PhysicalName = 'NonPaymentTotal-Condition';
UPDATE M_TemplateField SET ListNumber = 17 WHERE TemplateSeq = 47 AND  PhysicalName = 'UnpaidTotal-Score';
UPDATE M_TemplateField SET ListNumber = 16 WHERE TemplateSeq = 47 AND  PhysicalName = 'UnpaidTotal-Condition';
UPDATE M_TemplateField SET ListNumber = 15 WHERE TemplateSeq = 47 AND  PhysicalName = 'ClaimTotal_2-Score';
UPDATE M_TemplateField SET ListNumber = 14 WHERE TemplateSeq = 47 AND  PhysicalName = 'ClaimTotal_2-Condition';
UPDATE M_TemplateField SET ListNumber = 13 WHERE TemplateSeq = 47 AND  PhysicalName = 'ClaimTotal_1-Score';
UPDATE M_TemplateField SET ListNumber = 12 WHERE TemplateSeq = 47 AND  PhysicalName = 'ClaimTotal_1-Condition';
UPDATE M_TemplateField SET ListNumber = 11 WHERE TemplateSeq = 47 AND  PhysicalName = 'Cnl_ReturnSaikenCount';

/* テンプレートフィールド登録（不払い日数） */
INSERT INTO M_TemplateField VALUES ( 47 , 10, 'NonPaymentDays', '不払い日数', 'INT', '1', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);