/* ÉTÉCÉg */
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge` INT NOT NULL DEFAULT 0 AFTER `EtcAutoArrivalNumber`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge0` INT NOT NULL DEFAULT 0 AFTER `JintecJudge`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge1` INT NOT NULL DEFAULT 0 AFTER `JintecJudge0`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge2` INT NOT NULL DEFAULT 0 AFTER `JintecJudge1`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge3` INT NOT NULL DEFAULT 0 AFTER `JintecJudge2`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge4` INT NOT NULL DEFAULT 0 AFTER `JintecJudge3`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge5` INT NOT NULL DEFAULT 0 AFTER `JintecJudge4`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge6` INT NOT NULL DEFAULT 0 AFTER `JintecJudge5`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge7` INT NOT NULL DEFAULT 0 AFTER `JintecJudge6`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge8` INT NOT NULL DEFAULT 0 AFTER `JintecJudge7`;
ALTER TABLE `T_Site`
ADD COLUMN `JintecJudge9` INT NOT NULL DEFAULT 0 AFTER `JintecJudge8`;
