/* サイトマスタ */
ALTER TABLE `T_Site`
ADD COLUMN `RemindStopClass` INT NOT NULL DEFAULT 0 AFTER `KisanbiDelayDays`;

/* テンプレートヘッダ登録 */
INSERT INTO M_TemplateHeader VALUES( 96 , 'CKI04046_1', 0, 0, 0, '再請求書印刷データCSV（個別）', 1, ',', '\"' ,'*' ,0,'KI04043', NULL, NOW(), 9, NOW(), 9,1);

/* テンプレートフィールド登録 */
INSERT INTO M_TemplateField VALUES ( 96 , 1, 'PostalCode', '顧客郵便番号', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 2, 'UnitingAddress', '顧客住所', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 3, 'NameKj', '顧客氏名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 4, 'OrderId', '注文ＩＤ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 5, 'ReceiptOrderDate', '注文日', 'DATE', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 6, 'SiteNameKj', '購入店名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 7, 'Url', '購入店URL', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 8, 'ContactPhoneNumber', '購入店電話番号', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 9, 'ClaimAmount', '請求金額', 'BIGINT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 10, 'CarriageFee', '送料', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 11, 'ChargeFee', '決済手数料', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 12, 'ReIssueCount', '請求回数', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 13, 'LimitDate', '支払期限日', 'DATE', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 14, 'Cv_BarcodeData2', 'バーコードデータ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 15, 'ItemNameKj_1', '商品名１', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 16, 'ItemNum_1', '数量１', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 17, 'UnitPrice_1', '単価１', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 18, 'ItemNameKj_2', '商品名２', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 19, 'ItemNum_2', '数量２', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 20, 'UnitPrice_2', '単価２', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 21, 'ItemNameKj_3', '商品名３', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 22, 'ItemNum_3', '数量３', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 23, 'UnitPrice_3', '単価３', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 24, 'ItemNameKj_4', '商品名４', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 25, 'ItemNum_4', '数量４', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 26, 'UnitPrice_4', '単価４', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 27, 'ItemNameKj_5', '商品名５', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 28, 'ItemNum_5', '数量５', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 29, 'UnitPrice_5', '単価５', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 30, 'ItemNameKj_6', '商品名６', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 31, 'ItemNum_6', '数量６', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 32, 'UnitPrice_6', '単価６', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 33, 'ItemNameKj_7', '商品名７', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 34, 'ItemNum_7', '数量７', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 35, 'UnitPrice_7', '単価７', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 36, 'ItemNameKj_8', '商品名８', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 37, 'ItemNum_8', '数量８', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 38, 'UnitPrice_8', '単価８', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 39, 'ItemNameKj_9', '商品名９', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 40, 'ItemNum_9', '数量９', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 41, 'UnitPrice_9', '単価９', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 42, 'ItemNameKj_10', '商品名１０', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 43, 'ItemNum_10', '数量１０', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 44, 'UnitPrice_10', '単価１０', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 45, 'ItemNameKj_11', '商品名１１', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 46, 'ItemNum_11', '数量１１', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 47, 'UnitPrice_11', '単価１１', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 48, 'ItemNameKj_12', '商品名１２', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 49, 'ItemNum_12', '数量１２', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 50, 'UnitPrice_12', '単価１２', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 51, 'ItemNameKj_13', '商品名１３', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 52, 'ItemNum_13', '数量１３', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 53, 'UnitPrice_13', '単価１３', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 54, 'ItemNameKj_14', '商品名１４', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 55, 'ItemNum_14', '数量１４', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 56, 'UnitPrice_14', '単価１４', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 57, 'ItemNameKj_15', '商品名１５', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 58, 'ItemNum_15', '数量１５', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 59, 'UnitPrice_15', '単価１５', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 60, 'ItemNameKj_16', '商品名１６', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 61, 'ItemNum_16', '数量１６', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 62, 'UnitPrice_16', '単価１６', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 63, 'ItemNameKj_17', '商品名１７', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 64, 'ItemNum_17', '数量１７', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 65, 'UnitPrice_17', '単価１７', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 66, 'ItemNameKj_18', '商品名１８', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 67, 'ItemNum_18', '数量１８', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 68, 'UnitPrice_18', '単価１８', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 69, 'ItemNameKj_19', '商品名１９', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 70, 'ItemNum_19', '数量１９', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 71, 'UnitPrice_19', '単価１９', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 72, 'ClaimFee', '再請求発行手数料', 'BIGINT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 73, 'DamageInterestAmount', '遅延損害金', 'BIGINT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 74, 'TotalItemPrice', '小計', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 75, 'Ent_OrderId', '任意注文番号', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 76, 'TaxAmount', '消費税額', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 77, 'Cv_ReceiptAgentName', 'CVS収納代行会社名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 78, 'Cv_SubscriberName', 'CVS収納代行加入者名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 79, 'Cv_BarcodeData', 'バーコードデータ(CD付)', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 80, 'Cv_BarcodeString1', 'バーコード文字1', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 81, 'Cv_BarcodeString2', 'バーコード文字2', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 82, 'Bk_BankCode', '銀行口座 - 銀行コード', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 83, 'Bk_BranchCode', '銀行口座 - 支店コード', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 84, 'Bk_BankName', '銀行口座 - 銀行名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 85, 'Bk_BranchName', '銀行口座 - 支店名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 86, 'Bk_DepositClass', '銀行口座 - 口座種別', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 87, 'Bk_AccountNumber', '銀行口座 - 口座番号', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 88, 'Bk_AccountHolder', '銀行口座 - 口座名義', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 89, 'Bk_AccountHolderKn', '銀行口座 - 口座名義カナ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 90, 'Yu_SubscriberName', 'ゆうちょ口座 - 加入者名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 91, 'Yu_AccountNumber', 'ゆうちょ口座 - 口座番号', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 92, 'Yu_ChargeClass', 'ゆうちょ口座 - 払込負担区分', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 93, 'Yu_MtOcrCode1', 'ゆうちょ口座 - MT用OCRコード1', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 94, 'Yu_MtOcrCode2', 'ゆうちょ口座 - MT用OCRコード2', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 95, 'MypageToken', 'マイページログインパスワード', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 96, 'ItemsCount', '商品合計数', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 97, 'TaxClass', '消費税区分', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 98, 'CorporateName', '法人名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 99, 'DivisionName', '部署名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 100, 'CpNameKj', '担当者名', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 101, 'FreeColumn1' ,'自由項目１' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 102, 'FreeColumn2' ,'自由項目２' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 103, 'FreeColumn3' ,'自由項目３' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 104, 'FreeColumn4' ,'自由項目４' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 105, 'FreeColumn5' ,'自由項目５' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 106, 'FreeColumn6' ,'自由項目６' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 107, 'FreeColumn7' ,'自由項目７' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 108, 'FreeColumn8' ,'自由項目８' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 109, 'FreeColumn9' ,'自由項目９' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);
INSERT INTO M_TemplateField VALUES ( 96 , 110, 'FreeColumn10' ,'自由項目１０' ,'VARCHAR' ,0 ,NULL ,0,NULL ,NULL ,NULL , NOW(), 9, NOW(), 9, 1);