/* 加盟店顧客 */
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `FfName` VARCHAR(160)  NULL AFTER `BtoBCreditLimitAmount`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `FfCode` INT  NULL AFTER `FfName`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `FfBranchName` VARCHAR(160)  NULL AFTER `FfCode`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `FfBranchCode` INT  NULL AFTER `FfBranchName`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `FfAccountClass` INT  NULL AFTER `FfBranchCode`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `FfAccountNumber` VARCHAR(80)  NULL AFTER `FfAccountClass`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `FfAccountName` VARCHAR(255)  NULL AFTER `FfAccountNumber`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `RequestCompScheduleDate` DATE  NULL AFTER `FfAccountName`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `RequestStatus` INT  NULL AFTER `RequestCompScheduleDate`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `FfNote` TEXT  NULL AFTER `RequestStatus`;
ALTER TABLE T_EnterpriseCustomer ADD COLUMN `ClaimFeeFlg` INT  NULL AFTER `FfNote`;

/* コードマスタ */
INSERT INTO M_CodeManagement VALUES(196 ,'口座振替申込ステータス' ,NULL ,'申込ステータス' ,1 ,'ステータス' ,0,NULL,0,NULL, NOW(),1,NOW(),1,1);
INSERT INTO M_Code VALUES(196,1 ,'申請中',NULL ,NULL , NULL ,NULL ,0, NOW(), 1, NOW(), 1, 1);
INSERT INTO M_Code VALUES(196,2 ,'完了',NULL ,NULL , NULL ,NULL ,0, NOW(), 1, NOW(), 1, 1);
INSERT INTO M_Code VALUES(196,3 ,'不備',NULL ,NULL , NULL ,NULL ,0, NOW(), 1, NOW(), 1, 1);
INSERT INTO M_Code VALUES(196,9 ,'中止',NULL ,NULL , NULL ,NULL ,0, NOW(), 1, NOW(), 1, 1);

/* T_ImportedAccountTransferFile登録 */
DROP TABLE IF EXISTS `T_ImportedAccountTransferFile`;
CREATE TABLE `T_ImportedAccountTransferFile` (
  `Seq` bigint(20) NOT NULL AUTO_INCREMENT,
  `FileName` varchar(255) DEFAULT NULL,
  `Status` int(11) NOT NULL DEFAULT 0,
  `ReceiptResult` text,
  `RegistDate` datetime DEFAULT NULL,
  `RegistId` int(11) DEFAULT NULL,
  `UpdateDate` datetime DEFAULT NULL,
  `UpdateId` int(11) DEFAULT NULL,
  `ValidFlg` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Seq`),
  UNIQUE KEY `AccountTransferFileName` (`FileName`),
  KEY `Idx_T_ImportedAccountTransferFile01` (`FileName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* T_ClaimAccountTransferFile登録 */
DROP TABLE IF EXISTS `T_ClaimAccountTransferFile`;
CREATE TABLE `T_ClaimAccountTransferFile` (
  `Seq` bigint(20) NOT NULL AUTO_INCREMENT,
  `FileName` varchar(255) DEFAULT NULL,
  `Status` int(11) NOT NULL DEFAULT 0,
  `ClaimFile` longblob,
  `RegistDate` datetime DEFAULT NULL,
  `RegistId` int(11) DEFAULT NULL,
  `UpdateDate` datetime DEFAULT NULL,
  `UpdateId` int(11) DEFAULT NULL,
  `ValidFlg` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Seq`),
  UNIQUE KEY `ClaimAccountTransferFileName` (`FileName`),
  KEY `Idx_T_ClaimAccountTransferFile01` (`FileName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* T_Menu/MenuAuthority登録(振替結果関連) */
INSERT INTO T_Menu VALUES (186, 'cbadmin', 'keiriMenus', 'impacctrns', NULL, '***', '振替結果インポート', '振替結果インポート', '', '', '', NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (186, 1, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (186, 11, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (186, 101, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_Menu VALUES (187, 'cbadmin', 'keiriMenus', 'acctrnslist', NULL, '***', '振替結果一覧', '振替結果一覧', '', '', '', NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (187, 1, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (187, 11, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (187, 101, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_Menu VALUES (188, 'cbadmin', 'keiriMenus', 'creacctrns', NULL, '***', '振替請求データ作成', '振替請求データ作成', '', '', '', NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (188, 1, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (188, 11, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (188, 101, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_Menu VALUES (189, 'cbadmin', 'keiriMenus', 'dlacctrns', NULL, '***', '振替請求データダウンロード', '振替請求データダウンロード', '', '', '', NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (189, 1, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (189, 11, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (189, 101, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_Menu VALUES (190, 'cbadmin', 'enterpriseMenus', 'impaccountinformationform', NULL, '***', '口座情報取込', '口座情報取込', '', '', '', NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (190, 1, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (190, 11, NOW(), 9, NOW(), 9, 1);
INSERT INTO T_MenuAuthority VALUES (190, 101, NOW(), 9, NOW(), 9, 1);

/* T_SystemProperty登録(値に対しては桁数考慮あり) */
INSERT INTO T_SystemProperty(Module, Category, Name, PropValue, Description, RegistDate, RegistId, UpdateDate, UpdateId, ValidFlg) VALUES( '[DEFAULT]', 'systeminfo', 'CATSConsignorCode', '09999999', '委託者コード(口座振替用)', NOW(), 9, NOW(), 9, '1');
INSERT INTO T_SystemProperty(Module, Category, Name, PropValue, Description, RegistDate, RegistId, UpdateDate, UpdateId, ValidFlg) VALUES( '[DEFAULT]', 'systeminfo', 'CATSConsignorName', 'ｷﾔﾂﾁﾎﾞ-ﾙ                                ', '委託者名(口座振替用)', NOW(), 9, NOW(), 9, '1');
INSERT INTO T_SystemProperty(Module, Category, Name, PropValue, Description, RegistDate, RegistId, UpdateDate, UpdateId, ValidFlg) VALUES( '[DEFAULT]', 'systeminfo', 'CATSSyunoCoCode', '12345678', '収納企業コード(口座振替用)', NOW(), 9, NOW(), 9, '1');
INSERT INTO T_SystemProperty(Module, Category, Name, PropValue, Description, RegistDate, RegistId, UpdateDate, UpdateId, ValidFlg) VALUES( '[DEFAULT]', 'systeminfo', 'CATSShopCode', '87654321', '契約コード(口座振替用)', NOW(), 9, NOW(), 9, '1');
INSERT INTO T_SystemProperty(Module, Category, Name, PropValue, Description, RegistDate, RegistId, UpdateDate, UpdateId, ValidFlg) VALUES( '[DEFAULT]', 'systeminfo', 'CATSShopPassword', '00000000', 'ショップパスワード(口座振替用)', NOW(), 9, NOW(), 9, '1');
INSERT INTO T_SystemProperty(Module, Category, Name, PropValue, Description, RegistDate, RegistId, UpdateDate, UpdateId, ValidFlg) VALUES( '[DEFAULT]', 'systeminfo', 'CATSShopUrl', 'https://www.paymentstation.jp/customer/sf/at/kokkzmoshikomi/begin.do', 'ショップURL(口座振替用)', NOW(), 9, NOW(), 9, '1');


/* 一括注文登録（CSV使用） */
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
SELECT TemplateSeq, MAX(ListNumber)+1, 'CreditTransferRequestFlg', '口座振替申込区分', 'INT', 0, null, 0, 'AT_Order', '/^[0-2]$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;

/* 一括注文修正（CSV使用） */
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
SELECT TemplateSeq, MAX(ListNumber)+1, 'CreditTransferRequestFlg', '口座振替申込区分', 'INT', 0, null, 0, 'AT_Order', '/^[0-2]$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;

/* 請求履歴 */
ALTER TABLE T_ClaimHistory ADD COLUMN `CreditTransferMailFlg` INT  NULL AFTER `MailFlg`;
ALTER TABLE T_ClaimHistory ADD COLUMN `ClaimFileOutputClass` INT  NULL AFTER `CreditTransferMailFlg`;
ALTER TABLE T_ClaimHistory ADD COLUMN `CreditMailRetryCount` TINYINT  DEFAULT 0 AFTER `MailRetryCount`;

/* 口振請求書発行案内メール */
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('100', '口振請求書発行案内メール（PC）', '後払いドットコム', '=?UTF-8?B?GyRCOGVKJyQkJUklQyVIJTMlYBsoQg==?=', 'customer@ato-barai.com', '【後払い.com】口振請求書発行案内　（ハガキで届きます）ご注文ID:{OrderId}', '=?UTF-8?B?5b6M5omV44GE44OJ44OD44OI44Kz44Og?=', '──────────────────────────────────\r\n◇お問い合わせいただく際、下記メール文面を残したままご返信ください\r\n\r\n◇請求状態・明細の確認や各種お手続きは下記ウェブページでも\r\n行う事ができます。\r\n注文情報確認ページ　https://www.atobarai.jp/orderpage\r\n※ログインにはご注文時のお電話番号と、請求書に記載されている\r\nパスワードをご利用ください\r\n\r\n◇１週間ほどして請求書が届かない、請求書の紛失などによる\r\n【請求書再発行依頼】は、以下のURLからいつでも受け付けています。\r\n{OrderPageAccessUrl}\r\n\r\n────────────────────────────────── \r\n\r\n{CustomerNameKj}様\r\n\r\n先日は {SiteNameKj}様でのお買い物に後払いドットコムをご利用\r\nいただきまして、まことにありがとうございます。\r\n\r\nご請求書（圧着ハガキもしくは封筒）を本日発行いたしました。\r\n{LimitDate}までにお支払いいただきますよう、お願い申し上げます。\r\n\r\n普通郵便での発送となりますため、お届けまでに平均3日程度いただいて\r\nおります。商品の発送状況により、商品よりも先に請求書が届く可能性が\r\nございます。その場合は商品が到着してからお支払いいただければと存じます。\r\n\r\n※一週間ほどお待ちいただいても請求書が届かない場合は大変お手数ですが、\r\nこのメールの末尾に記載されている後払いドットコムカスタマーセンターまで\r\nご一報ください。\r\n\r\n\r\n【ご注文内容】\r\nご注文番号：{OrderId}\r\nご注文日：{OrderDate}\r\nご注文店舗：{SiteNameKj}\r\n商品名（1品目のみ表示）：{OneOrderItem}\r\nご請求金額：{UseAmount}\r\n\r\n※商品の返品・未着など商品に関するお問い合わせは、大変お手数ですが\r\n直接購入店にお問い合わせ下さい。\r\n購入店舗：{SiteNameKj}　\r\n電話：{Phone}\r\n\r\n<よくある質問集>\r\nQ1.支払い期限を過ぎてしまいましたが、どうしたらよいですか？\r\nA1:請求書がお手元にある場合は至急お手元の請求書でお支払いください。\r\n請求書がお手元にない場合、ご状況のご確認をさせていただきますので\r\n至急弊社（03-5909-3490）までご連絡をお願いいたします。\r\n\r\nQ2.注文情報を確認する方法を教えてください。\r\nA2.注文情報は、請求書に記載されています。より詳しい情報は、\r\n下記ウェブページでも行う事ができます。ログイン方法は請求書に\r\n記載されています。\r\n注文情報確認ページ　https://www.atobarai.jp/orderpage\r\n\r\nQ3.商品を交換、返品したいです。\r\nA3.商品の交換や返品をご希望の場合には、購入店に直接お問い合わせを\r\nお願いいたします。\r\n購入店舗：{SiteNameKj}　\r\n電話：{Phone}\r\n\r\nQ4.どこで支払いができますか？\r\nA4.コンビニ、銀行、郵便局のいずれかでお支払いいただけます。\r\n\r\nQ5.請求書が届きません。\r\nA5.請求書は通常、商品の到着前後か1週間以内に届きます。1週間以上\r\n経っても届かない場合は、お手数ですが弊社（03-5909-3490）まで、\r\nご連絡をお願いいたします。\r\n\r\nQ6.もう一度商品を注文したいです。\r\nA6.お手数ですが、ご購入された店舗様で再度注文をお願いいたします。\r\n\r\nその他、下記ページにても「よくある質問集（ＦＡＱ）」をご確認いただく\r\nことができます。\r\nhttps://atobarai-user.jp/\r\n\r\n\r\n--------------------------------------------------------------\r\n後払い請求代行サービス【後払いドットコム】\r\n\r\n  お問合せ先（カスタマーセンター）：03－5909－3490\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: customer@ato-barai.com\r\n  \r\n　運営会社：株式会社キャッチボール\r\n　住所：〒160-0023 東京都新宿区西新宿6-14-1 新宿グリーンタワービル14F\r\n', now(), '9', now(), '9', '1');
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('101', '口振請求書発行案内メール（CEL）', '後払いドットコム', '=?UTF-8?B?GyRCOGVKJyQkJUklQyVIJTMlYBsoQg==?=', 'customer@ato-barai.com', '【後払い.com】口振請求書発行案内　ご注文番号：{OrderId}', '=?UTF-8?B?5b6M5omV44GE44OJ44OD44OI44Kz44Og?=', '──────────────────────────────────\r\n◇お問い合わせいただく際、下記メール文面を残したままご返信ください\r\n\r\n◇請求状態・明細の確認や各種お手続きは下記ウェブページでも\r\n行う事ができます。\r\n注文情報確認ページ　https://www.atobarai.jp/orderpage\r\n※ログインにはご注文時のお電話番号と、請求書に記載されている\r\nパスワードをご利用ください\r\n\r\n◇１週間ほどして請求書が届かない、請求書の紛失などによる\r\n【請求書再発行依頼】は、以下のURLからいつでも受け付けています。\r\n{OrderPageAccessUrl}\r\n────────────────────────────────── \r\n\r\n{CustomerNameKj}様\r\n\r\n先日は {SiteNameKj}様でのお買い物に 後払いドットコムをご利用\r\nいただきまして、まことにありがとうございます。\r\n\r\nご請求書（圧着ハガキもしくは封筒）を本日発行いたしました。\r\n{LimitDate}までにお支払いいただきますよう、お願い申し上げます。\r\n\r\n普通郵便での発送となりますため、お届けまでに平均3日程度いただいて\r\nおります。商品の発送状況により、商品よりも先に請求書が届く可能性が\r\nございます。その場合は商品が到着してからお支払いいただければと存じます。\r\n\r\n※一週間ほどお待ちいただいても請求書が届かない場合は大変お手数ですが、\r\nこのメールの末尾に記載されている後払いドットコムカスタマーセンターまで\r\nご一報ください。\r\n\r\n\r\n【ご注文内容】\r\nご注文番号：{OrderId}\r\nご注文日：{OrderDate}\r\nご注文店舗：{SiteNameKj}\r\n商品名（1品目のみ表示）：{OneOrderItem}\r\nご請求金額：{UseAmount}\r\n\r\n※商品の返品・未着など商品に関するお問い合わせは、大変お手数ですが\r\n直接購入店にお問い合わせ下さい。\r\n購入店舗：{SiteNameKj}　\r\n電話：{Phone}\r\n\r\n<よくある質問集>\r\nQ1.支払い期限を過ぎてしまいましたが、どうしたらよいですか？\r\nA1:請求書がお手元にある場合は至急お手元の請求書でお支払いください。\r\n請求書がお手元にない場合、ご状況のご確認をさせていただきますので\r\n至急弊社（03-5909-3490）までご連絡をお願いいたします。\r\n\r\nQ2.注文情報を確認する方法を教えてください。\r\nA2.注文情報は、請求書に記載されています。より詳しい情報は、\r\n下記ウェブページでも行う事ができます。ログイン方法は請求書に\r\n記載されています。\r\n注文情報確認ページ　https://www.atobarai.jp/orderpage\r\n\r\nQ3.商品を交換、返品したいです。\r\nA3.商品の交換や返品をご希望の場合には、購入店に直接お問い合わせを\r\nお願いいたします。\r\n購入店舗：{SiteNameKj}　\r\n電話：{Phone}\r\n\r\nQ4.どこで支払いができますか？\r\nA4.コンビニ、銀行、郵便局のいずれかでお支払いいただけます。\r\n\r\nQ5.請求書が届きません。\r\nA5.請求書は通常、商品の到着前後か1週間以内に届きます。1週間以上\r\n経っても届かない場合は、お手数ですが弊社（03-5909-3490）まで、\r\nご連絡をお願いいたします。\r\n\r\nQ6.もう一度商品を注文したいです。\r\nA6.お手数ですが、ご購入された店舗様で再度注文をお願いいたします。\r\n\r\nその他、下記ページにても「よくある質問集（ＦＡＱ）」をご確認いただく\r\nことができます。\r\nhttps://atobarai-user.jp/\r\n\r\n\r\n--------------------------------------------------------------\r\n後払い請求代行サービス【後払いドットコム】\r\n\r\n  お問合せ先（カスタマーセンター）：03－5909－3490\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: customer@ato-barai.com\r\n  \r\n　運営会社：株式会社キャッチボール\r\n　住所：〒160-0023 東京都新宿区西新宿6-14-1 新宿グリーンタワービル14F\r\n\r\n', now(), '9', now(), '9', '1');
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `OemId`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('100', '口振請求書発行案内メール（PC）', '株式会社Ｅストアー（後払い窓口）', '=?UTF-8?B?GyRCM3Q8MDJxPFIjRSU5JUglIiE8IUo4ZUonJCRBazh9IUsbKEI=?=', 'ato-barai.sp@estore.co.jp', '【ご連絡】口振請求書を発行しました　（ハガキで届きます）', '=?UTF-8?B?5qCq5byP5Lya56S+77yl44K544OI44Ki44O877yI5b6M5omV44GE56qT5Y+j?=\r\n =?UTF-8?B?77yJ?=', '─────────────────────────────────────\r\n◇お願い：お問い合わせ頂く際、下記メール文面を残したままご返信ください◇\r\n─────────────────────────────────────\r\n\r\n{CustomerNameKj}様\r\n\r\n\r\n先日はご注文いただきまして、誠にありがとうございます。\r\n\r\n\r\n下記のショッピングのご請求書を本日発行いたしますので、請求書到着後、\r\n請求書に記載されているお支払期限日までにお支払いいただきますよう、\r\nお願い申し上げます。\r\n\r\n\r\n【ご注文内容】\r\n\r\nお支払者：{CustomerNameKj}　様\r\n\r\nご購入店舗名：{SiteNameKj}　\r\n\r\nご購入日：{OrderDate}\r\n\r\nお支払金額：{UseAmount}\r\n\r\nご購入商品明細：商品名／個数／購入品目計\r\n\r\n{OrderItems}\r\n\r\n決済手数料                              \\{SettlementFee}\r\n\r\n送料                                    \\{DeliveryFee}\r\n\r\n\r\n※郵送事故などにより、請求書が届かないことがございます。\r\n一週間ほどお待ちいただいても請求書が届かない場合には、大変お手数ですが、\r\n下記連絡先へご一報くださいますよう、お願い申し上げます。\r\n\r\n\r\n※商品につきましても、メール便などの配送方法の場合には、配送事故などにより\r\n届かない場合がございます。\r\n万が一、商品が届いていない場合には大変お手数ではございますが、ご注文された\r\n店舗様まで直接お問合せくださいませ。\r\n\r\n\r\n※請求書並びに本メールが、商品よりも早く到着してしまうことがございますが、\r\n何卒ご容赦下さいますようお願い申し上げます。\r\nまた、請求書内に明細が含まれておりますのでご確認くださいませ。\r\n\r\n\r\n※メールにてお問合せをいただく場合は、必ずご注文時のお名前（フルネーム）を\r\n本文に入れてお問合せください。\r\n\r\n\r\n※キャンセル（解約申請）されている場合でも、行き違いにて当メールが\r\n配信されてしまう場合がございます。その際は大変お手数ですが、下記\r\n購入店舗様に直接お問合せください。\r\n\r\n\r\n\r\n■商品・返品・配送に関するお問い合わせは：\r\n\r\n　直接購入店舗様にお問い合わせください。\r\n　購入店舗：{SiteNameKj}　電話：{Phone}\r\n\r\n\r\n\r\n■お支払いに関するお問い合わせは：\r\n\r\n  お問合せ先：03-6908-5100\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: ato-barai.sp@estore.co.jp\r\n  運営会社：株式会社Ｅストアー　後払い窓口 \r\n　住所：〒105-0003 東京都港区西新橋1-10-2　住友生命西新橋ビル9F\r\n', '1', now(), '9', now(), '9', '1');
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `OemId`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('101', '口振請求書発行案内メール（CEL）', '株式会社Ｅストアー（後払い窓口）', '=?UTF-8?B?GyRCM3Q8MDJxPFIjRSU5JUglIiE8IUo4ZUonJCRBazh9IUsbKEI=?=', 'ato-barai.sp@estore.co.jp', '【ご連絡】口振請求書（ハガキ）を発行しました', '=?UTF-8?B?5qCq5byP5Lya56S+77yl44K544OI44Ki44O877yI5b6M5omV44GE56qT5Y+j?=\r\n =?UTF-8?B?77yJ?=', '\r\n◇お願い：お問い合わせ頂く際、下記メール文面を残したままご返信ください◇\r\n\r\n\r\n{CustomerNameKj}様\r\n\r\n\r\n先日はご注文いただきまして、誠にありがとうございます。\r\n\r\n下記のショッピングのご請求書を本日発行いたしますので、請求書到着後、\r\n請求書に記載されているお支払期限日までにお支払いいただきますよう、\r\nお願い申し上げます。\r\n\r\n【ご注文内容】\r\nお支払者：{CustomerNameKj}　様\r\nご購入店舗名：{SiteNameKj}　\r\nご購入日：{OrderDate}\r\nお支払金額：{UseAmount}\r\nご購入商品明細：商品名／個数／購入品目計\r\n{OrderItems}\r\n決済手数料  \\{SettlementFee}\r\n送料 \\{DeliveryFee}\r\n\r\n※郵送事故などにより、請求書が届かないことがございます。\r\n一週間ほどお待ちいただいても請求書が届かない場合には、大変お手数ですが、\r\n下記連絡先へご一報くださいますよう、お願い申し上げます。\r\n\r\n※商品につきましても、メール便などの配送方法の場合には、配送事故などにより\r\n届かない場合がございます。\r\n万が一、商品が届いていない場合には大変お手数ではございますが、ご注文された\r\n店舗様まで直接お問合せくださいませ。\r\n\r\n※請求書並びに本メール、商品よりも早く到着してしまうことがございますが、\r\n何卒ご容赦下さいますようお願い申し上げます。\r\nまた、請求書内に明細が含まれておりますのでご確認くださいませ。\r\n\r\n※メールにてお問合せをいただく場合は、必ずご注文時のお名前（フルネーム）を\r\n本文に入れてお問合せください。\r\n\r\n※キャンセル（解約申請）されている場合でも、行き違いにて当メールが\r\n配信されてしまう場合がございます。その際は大変お手数ですが、下記\r\n購入店舗様に直接お問合せください。\r\n\r\n■商品・返品・配送に関するお問い合わせは：\r\n直接購入店舗様にお問い合わせください。\r\n購入店舗：{SiteNameKj}　電話：{Phone}\r\n\r\n■お支払いに関するお問い合わせは：\r\n03-6908-5100\r\n 営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n ato-barai.sp@estore.co.jp\r\n 運営会社：株式会社Ｅストアー　後払い窓口\r\n〒105-0003 東京都港区西新橋1-10-2　住友生命西新橋ビル9F', '1', now(), '9', now(), '9', '1');
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `OemId`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('100', '口振請求書発行案内メール（PC）', '後払いドットコム', '=?UTF-8?B?GyRCOGVKJyQkJUklQyVIJTMlYBsoQg==?=', 'customer@ato-barai.com', '【後払い.com】口振請求書発行案内　（ハガキで届きます）', '=?UTF-8?B?5b6M5omV44GE44OJ44OD44OI44Kz44Og?=', '──────────────────────────────────\r\n◇お願い：お問い合わせ頂く際、下記メール文面を残したままご返信ください◇\r\n────────────────────────────────── \r\n\r\n{CustomerNameKj}様\r\n\r\n先日は {SiteNameKj}様でのお買い物に\r\n【後払いドットコム】をご利用いただきまして、\r\nまことにありがとうございます。\r\n\r\n下記のショッピングのご請求書を本日発行いたしますので、請求書到着後、\r\n請求書に記載されているお支払期限日までにお支払いいただきますよう、\r\nお願い申し上げます。\r\n\r\n{OrderPageAccessUrl}\r\n\r\n【ご注文内容】\r\nお支払者：{CustomerNameKj}　様\r\nご購入店舗名：{SiteNameKj}　\r\nご購入日：{OrderDate}\r\nお支払金額：{UseAmount}\r\nご購入商品明細：商品名／個数／購入品目計\r\n{OrderItems}\r\n決済手数料                              \\{SettlementFee}\r\n送料                                    \\{DeliveryFee}\r\n\r\n※郵送事故などにより、請求書が届かないことがございます。\r\n　一週間ほどお待ちいただいても請求書が届かない場合には、大変お手数ですが、\r\n　下記連絡先へご一報くださいますよう、お願い申し上げます。\r\n\r\n※商品につきましても、メール便などの配送方法の場合には、配送事故などにより\r\n　届かない場合がございます。\r\n　万が一、商品が届いていない場合には大変お手数ではございますが、ご注文された\r\n　店舗様まで直接お問合せくださいませ。\r\n\r\n※請求書並びに本メールが、商品よりも早く到着してしまうことがございますが、\r\n何卒ご容赦下さいますようお願い申し上げます。\r\nまた、請求書内に明細が含まれておりますのでご確認くださいませ。\r\n\r\n※キャンセル（解約申請）されている場合でも、行き違いにて当メールが\r\n　配信されてしまう場合がございます。その際は大変お手数ですが、下記\r\n　購入店舗様に直接お問合せください。\r\n\r\n※※※その他ご不明な点は下記ＵＲＬをご確認ください。※※※\r\n\r\n　　　  http://www.ato-barai.com/guidance/faq.html\r\n\r\n■商品・返品・配送に関するお問い合わせは：\r\n直接購入店舗様にお問い合わせ下さい。\r\n購入店舗：{SiteNameKj}　電話：{Phone}\r\n\r\n■お支払いに関するお問い合わせは：\r\n株式会社キャッチボール　後払いドットコム事業部\r\nTEL:03-5332-3490(平日土日9:00～18:00)\r\nMail: customer@ato-barai.com\r\n\r\n--------------------------------------------------------------\r\n\r\n【後払いドットコム】～最も消費者に愛される決済サービス～\r\n\r\n  お問合せ先：03-5332-3490\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: customer@ato-barai.com\r\n\r\n  運営会社：株式会社キャッチボール\r\n　住所：〒160-0023 東京都新宿区西新宿7-7-30 小田急柏木ビル 8F\r\n\r\n--------------------------------------------------------------', '2', now(), '9', now(), '9', '1');
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `OemId`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('101', '口振請求書発行案内メール（CEL）', '後払いドットコム', '=?UTF-8?B?GyRCOGVKJyQkJUklQyVIJTMlYBsoQg==?=', 'customer@ato-barai.com', '【後払い.com】口振請求書発行案内　（ハガキで届きます）', '=?UTF-8?B?5b6M5omV44GE44OJ44OD44OI44Kz44Og?=', '──────────────────────────────────\r\n◇お願い：お問い合わせ頂く際、下記メール文面を残したままご返信ください◇\r\n────────────────────────────────── \r\n\r\n{CustomerNameKj}様\r\n\r\n先日は {SiteNameKj}様でのお買い物に\r\n【後払いドットコム】をご利用いただきまして、\r\nまことにありがとうございます。\r\n\r\n下記のショッピングのご請求書を本日発行いたしますので、請求書到着後、\r\n請求書に記載されているお支払期限日までにお支払いいただきますよう、\r\nお願い申し上げます。\r\n\r\n【ご注文内容】\r\nお支払者：{CustomerNameKj}　様\r\nご購入店舗名：{SiteNameKj}　\r\nご購入日：{OrderDate}\r\nお支払金額：{UseAmount}\r\nご購入商品明細：商品名／個数／購入品目計\r\n{OrderItems}\r\n決済手数料  \\{SettlementFee}\r\n送料 \\{DeliveryFee}\r\n\r\n※郵送事故などにより、請求書が届かないことがございます。\r\n　一週間ほどお待ちいただいても請求書が届かない場合には、大変お手数ですが、\r\n　下記連絡先へご一報くださいますよう、お願い申し上げます。\r\n\r\n※商品につきましても、メール便などの配送方法の場合には、配送事故などにより\r\n　届かない場合がございます。\r\n　万が一、商品が届いていない場合には大変お手数ではございますが、ご注文された\r\n　店舗様まで直接お問合せくださいませ。\r\n\r\n※請求書並びに本メール、商品よりも早く到着してしまうことがございますが、\r\n何卒ご容赦下さいますようお願い申し上げます。\r\nまた、請求書内に明細が含まれておりますのでご確認くださいませ。\r\n\r\n※キャンセル（解約申請）されている場合でも、行き違いにて当メールが\r\n　配信されてしまう場合がございます。その際は大変お手数ですが、下記\r\n　購入店舗様に直接お問合せください。\r\n\r\n※※※その他ご不明な点は下記ＵＲＬをご確認ください。※※※\r\n\r\n　　　  http://www.ato-barai.com/guidance/faq.html\r\n\r\n\r\n■商品・返品・配送に関するお問い合わせは：\r\n直接購入店舗様にお問い合わせ下さい。\r\n購入店舗：{SiteNameKj}　\r\n電話：{Phone}\r\n\r\n■お支払いに関するお問い合わせは：\r\n株式会社キャッチボール　後払いドットコム事業部\r\n住所：〒160-0023 東京都新宿区西新宿7-8-2 福八ビル 4F\r\nTEL:03-5332-3490(平日土日9:00～18:00)\r\nMail: customer@ato-barai.com\r\nURL: http://www.ato-barai.com（パソコン専用）\r\n\r\n--------------------------------------------------------------\r\n\r\n【後払いドットコム】～最も消費者に愛される決済サービス～\r\n\r\n  お問合せ先：03-5332-3490\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail:customer@ato-barai.com\r\n\r\n  運営会社：株式会社キャッチボール\r\n　住所：〒160-0023 東京都新宿区西新宿7-7-30 小田急柏木ビル 8F\r\n\r\n--------------------------------------------------------------', '2', now(), '9', now(), '9', '1');
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `OemId`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('100', '口振請求書発行案内メール（PC）', '後払い決済サービス', '=?UTF-8?B?GyRCOGVKJyQkN2g6USU1ITwlUyU5GyhC?=', 'sfc-atobarai@seino.co.jp', '【後払い決済サービス】口振請求書発行案内　（ハガキで届きます）', '=?UTF-8?B?5b6M5omV44GE5rG65riI44K144O844OT44K5?=', '─────────────────────────────────────\r\n◇お願い：お問い合わせ頂く際、下記メール文面を残したままご返信ください◇\r\n─────────────────────────────────────\r\n\r\n{CustomerNameKj}様\r\n\r\n先日は {SiteNameKj}様でのお買い物に\r\n【後払い決済サービス】をご利用いただきまして、\r\nまことにありがとうございます。\r\n\r\n下記のショッピングのご請求書を本日発行いたしますので、請求書到着後、\r\n請求書に記載されているお支払期限日までにお支払いいただきますよう、\r\nお願い申し上げます。\r\n\r\n{OrderPageAccessUrl}\r\n\r\n【ご注文内容】\r\nお支払者：{CustomerNameKj}　様\r\nご購入店舗名：{SiteNameKj}　\r\nご購入日：{OrderDate}\r\nお支払金額：{UseAmount}\r\nご購入商品明細：商品名／個数／購入品目計\r\n{OrderItems}\r\n決済手数料                              \\{SettlementFee}\r\n送料                                    \\{DeliveryFee}\r\n\r\n※郵送事故などにより、請求書が届かないことがございます。\r\n　一週間ほどお待ちいただいても請求書が届かない場合には、大変お手数ですが、\r\n　下記連絡先へご一報くださいますよう、お願い申し上げます。\r\n\r\n※商品につきましても、メール便などの配送方法の場合には、配送事故などにより\r\n　届かない場合がございます。\r\n　万が一、商品が届いていない場合には大変お手数ではございますが、ご注文された\r\n　店舗様まで直接お問合せくださいませ。\r\n\r\n※請求書並びに本メールが、商品よりも早く到着してしまうことがございますが、\r\n何卒ご容赦下さいますようお願い申し上げます。\r\nまた、請求書内に明細が含まれておりますのでご確認くださいませ。\r\n\r\n詳しくは下記パソコン用URLをご覧下さい。\r\n\r\nhttp://www.seino.co.jp/financial/atobarai/guidance/\r\n\r\nご不明な点などございましたら、お気軽に下記までお問合せ下さい。\r\n\r\n※メールにてお問合せをいただく場合は、必ずご注文時のお名前（フルネーム）を\r\n　本文に入れてお問合せください。\r\n\r\n※キャンセル（解約申請）されている場合でも、行き違いにて当メールが\r\n　配信されてしまう場合がございます。その際は大変お手数ですが、下記\r\n　購入店舗様に直接お問合せください。\r\n\r\n■商品・返品・配送に関するお問い合わせは：\r\n直接購入店舗様にお問い合わせ下さい。\r\n購入店舗：{SiteNameKj}　電話：{Phone}\r\n\r\n■お支払いに関するお問い合わせは：\r\nセイノーフィナンシャル株式会社　後払い決済サービス担当\r\nTEL:03-6908-7888 9:00～18:00　年中無休（年末・年始のぞく）\r\nMail: sfc-atobarai@seino.co.jp\r\n\r\n--------------------------------------------------------------\r\n\r\n【後払い決済サービス】～最も消費者に愛される決済サービス～\r\n\r\n  お問合せ先：03-6908-7888\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: sfc-atobarai@seino.co.jp\r\n\r\n  運営会社：セイノーフィナンシャル株式会社\r\n　住所：〒503-8501 岐阜県大垣市田口町１番地\r\n\r\n--------------------------------------------------------------', '3', now(), '9', now(), '9', '1');
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `OemId`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('101', '口振請求書発行案内メール（CEL）', '後払い決済サービス', '=?UTF-8?B?GyRCOGVKJyQkN2g6USU1ITwlUyU5GyhC?=', 'sfc-atobarai@seino.co.jp', '【後払い決済サービス】口振請求書発行案内　（ハガキで届きます）', '=?UTF-8?B?5b6M5omV44GE5rG65riI44K144O844OT44K5?=', '\r\n◇お願い：お問い合わせ頂く際、下記メール文面を残したままご返信ください◇\r\n\r\n\r\n{CustomerNameKj}様\r\n\r\n先日は {SiteNameKj}様でのお買い物に\r\n【後払い決済サービス】をご利用いただきまして、\r\nまことにありがとうございます。\r\n\r\n下記のショッピングのご請求書を本日発行いたしますので、請求書到着後、\r\n請求書に記載されているお支払期限日までにお支払いいただきますよう、\r\nお願い申し上げます。\r\n\r\n【ご注文内容】\r\nお支払者：{CustomerNameKj}　様\r\nご購入店舗名：{SiteNameKj}　\r\nご購入日：{OrderDate}\r\nお支払金額：{UseAmount}\r\nご購入商品明細：商品名／個数／購入品目計\r\n{OrderItems}\r\n決済手数料  \\{SettlementFee}\r\n送料 \\{DeliveryFee}\r\n\r\n※郵送事故などにより、請求書が届かないことがございます。\r\n　一週間ほどお待ちいただいても請求書が届かない場合には、大変お手数ですが、\r\n　下記連絡先へご一報くださいますよう、お願い申し上げます。\r\n\r\n※商品につきましても、メール便などの配送方法の場合には、配送事故などにより\r\n　届かない場合がございます。\r\n　万が一、商品が届いていない場合には大変お手数ではございますが、ご注文された\r\n　店舗様まで直接お問合せくださいませ。\r\n\r\n※請求書並びに本メール、商品よりも早く到着してしまうことがございますが、\r\n何卒ご容赦下さいますようお願い申し上げます。\r\nまた、請求書内に明細が含まれておりますのでご確認くださいませ。\r\n\r\n詳しくは下記パソコン用URLをご覧下さい。\r\n\r\nhttp://www.seino.co.jp/financial/atobarai/guidance/\r\n\r\nご不明な点などございましたら、お気軽に下記までお問合せ下さい。\r\n\r\n※メールにてお問合せをいただく場合は、必ずご注文時のお名前（フルネーム）を\r\n　本文に入れてお問合せください。\r\n\r\n※キャンセル（解約申請）されている場合でも、行き違いにて当メールが\r\n　配信されてしまう場合がございます。その際は大変お手数ですが、下記\r\n　購入店舗様に直接お問合せください。\r\n\r\n■商品・返品・配送に関するお問い合わせは：\r\n直接購入店舗様にお問い合わせ下さい。\r\n購入店舗：{SiteNameKj}　\r\n電話：{Phone}\r\n\r\n■お支払いに関するお問い合わせは：\r\nセイノーフィナンシャル株式会社　後払い決済サービス担当\r\n住所：〒503-8501 岐阜県大垣市田口町１番地\r\nTEL:03-6908-7888 9:00～18:00　年中無休（年末・年始のぞく）\r\nMail: sfc-atobarai@seino.co.jp\r\nURL: http://www.seino.co.jp/financial（パソコン専用）\r\n\r\n--------------------------------------------------------------\r\n\r\n【後払い決済サービス】～最も消費者に愛される決済サービス～\r\n\r\n  お問合せ先：03-6908-7888\r\n  営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: sfc-atobarai@seino.co.jp\r\n\r\n  運営会社：セイノーフィナンシャル株式会社\r\n　住所：〒503-8501 岐阜県大垣市田口町１番地\r\n\r\n--------------------------------------------------------------', '3', now(), '9', now(), '9', '1');
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `OemId`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('100', '口振請求書発行案内メール（PC）', '【BASE後払い決済】', '=?UTF-8?B?GyRCIVobKEJCQVNFGyRCOGVKJyQkN2g6USFbGyhC?=', 'atobarai@thebase.in', '【BASE後払い決済】口振請求書発行案内　（ハガキで届きます）', '=?UTF-8?B?44CQQkFTReW+jOaJleOBhOaxuua4iOOAkQ==?=', '──────────────────────────────────\r\n◇お問い合わせいただく際、下記メール文面を残したままご返信ください◇\r\n────────────────────────────────── \r\n\r\n{CustomerNameKj}様\r\n\r\n先日は {SiteNameKj}様でお買い物をして頂き\r\nまことにありがとうございます。\r\n\r\n下記のショッピングのご請求書を本日発行いたしますので、請求書到着後、\r\n請求書に記載されているお支払期限日までにお支払いいただきますよう、\r\nお願い申し上げます。\r\n\r\n【ご注文内容】\r\n\r\nお支払者：{CustomerNameKj}　様\r\n\r\nご購入店舗名：{SiteNameKj}\r\n\r\nご購入日：{OrderDate}\r\n\r\nお支払金額：{UseAmount}\r\n\r\nご購入商品明細：商品名／個数／購入品目計\r\n\r\n{OrderItems}\r\n\r\n決済手数料                              \\{SettlementFee}\r\n\r\n送料                                    \\{DeliveryFee}\r\n\r\n※郵送事故などにより、請求書が届かないことがございます。\r\n　一週間ほどお待ちいただいても請求書が届かない場合には、大変お手数ですが、\r\n　下記連絡先へご一報くださいますよう、お願い申し上げます。\r\n\r\n※商品につきましても、メール便などの配送方法の場合には、配送事故などにより\r\n　届かない場合がございます。\r\n　万が一、商品が届いていない場合には大変お手数ではございますが、ご注文された\r\n　店舗様まで直接お問合せくださいませ。\r\n\r\n※請求書並びに本メールが、商品よりも早く到着してしまうことがございますが、\r\n　何卒ご容赦下さいますようお願い申し上げます。\r\n　また、請求書内に明細が含まれておりますのでご確認くださいませ。\r\n\r\n\r\n詳しくは下記URLをご覧下さい。\r\nhttp://thebase.in/pages/help.html#category14_146\r\n\r\nご不明な点などございましたら、お気軽に下記までお問合せ下さい。\r\n\r\n※メールにてお問合せをいただく場合は、必ずご注文時のお名前（フルネーム）を\r\n　本文に入れてお問合せください。\r\n\r\n※キャンセル（解約申請）されている場合でも、行き違いにて当メールが\r\n　配信されてしまう場合がございます。その際は大変お手数ですが、下記\r\n　購入店舗様に直接お問合せください。\r\n\r\n\r\n■商品・返品・配送に関するお問い合わせは：\r\n\r\n直接購入店舗様にお問い合わせ下さい。\r\n購入店舗：{SiteNameKj}　\r\n電話：{Phone}\r\n\r\n※商品到着から7日以降のキャンセルはできませんのでご注意ください。\r\n店舗との同意の上キャンセルにより商品を返品される場合はその旨、\r\n下記メールアドレスまで注文内容のご連絡をお願いします。\r\n\r\nsupport@thebase.in\r\n\r\nキャンセルを行なわないと\r\n商品代金支払いの\r\nご請求届き続けますのでご注意ください。\r\n\r\n{SiteNameKj} は BASE ( https://thebase.in ) で作成されています。 \r\nBASEは誰でも簡単に無料でネットショップが開設できるサービスです。\r\n\r\n■お支払いに関するお問い合わせは：\r\n\r\nBASE 後払い決済　窓口\r\nTEL:[03-6279-1149](平日土日9:00～18:00)\r\nMail: atobarai@thebase.in\r\n\r\n\r\n───────────────────────────────────\r\n\r\nBASE (ベイス)\r\nhttps://thebase.in\r\n\r\n お問合せ先:[03-6279-1149]\r\n 営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: atobarai@thebase.in\r\n\r\n───────────────────────────────────', '4', now(), '9', now(), '9', '1');
INSERT INTO `T_MailTemplate` (`Class`, `ClassName`, `FromTitle`, `FromTitleMime`, `FromAddress`, `Subject`, `SubjectMime`, `Body`, `OemId`, `RegistDate`, `RegistId`, `UpdateDate`, `UpdateId`, `ValidFlg`) VALUES ('101', '口振請求書発行案内メール（CEL）', '【BASE後払い決済】', '=?UTF-8?B?GyRCIVobKEJCQVNFGyRCOGVKJyQkN2g6USFbGyhC?=', 'atobarai@thebase.in', '【BASE後払い決済】口振請求書発行案内　（ハガキで届きます）', '=?UTF-8?B?44CQQkFTReW+jOaJleOBhOaxuua4iOOAkQ==?=', '──────────────────────────────────\r\n◇お問い合わせいただく際、下記メール文面を残したままご返信ください◇\r\n────────────────────────────────── \r\n\r\n{CustomerNameKj}様\r\n\r\n先日は {SiteNameKj}様でお買い物をして頂き\r\nまことにありがとうございます。\r\n\r\n下記のショッピングのご請求書を本日発行いたしますので、請求書到着後、\r\n請求書に記載されているお支払期限日までにお支払いいただきますよう、\r\nお願い申し上げます。\r\n\r\n【ご注文内容】\r\n\r\nお支払者：{CustomerNameKj}　様\r\n\r\nご購入店舗名：{SiteNameKj}\r\n\r\nご購入日：{OrderDate}\r\n\r\nお支払金額：{UseAmount}\r\n\r\nご購入商品明細：商品名／個数／購入品目計\r\n\r\n{OrderItems}\r\n\r\n決済手数料                              \\{SettlementFee}\r\n\r\n送料                                    \\{DeliveryFee}\r\n\r\n※郵送事故などにより、請求書が届かないことがございます。\r\n　一週間ほどお待ちいただいても請求書が届かない場合には、大変お手数ですが、\r\n　下記連絡先へご一報くださいますよう、お願い申し上げます。\r\n\r\n※商品につきましても、メール便などの配送方法の場合には、配送事故などにより\r\n　届かない場合がございます。\r\n　万が一、商品が届いていない場合には大変お手数ではございますが、ご注文された\r\n　店舗様まで直接お問合せくださいませ。\r\n\r\n※請求書並びに本メールが、商品よりも早く到着してしまうことがございますが、\r\n　何卒ご容赦下さいますようお願い申し上げます。\r\n　また、請求書内に明細が含まれておりますのでご確認くださいませ。\r\n\r\n\r\n詳しくは下記URLをご覧下さい。\r\nhttp://thebase.in/pages/help.html#category14_146\r\n\r\nご不明な点などございましたら、お気軽に下記までお問合せ下さい。\r\n\r\n※メールにてお問合せをいただく場合は、必ずご注文時のお名前（フルネーム）を\r\n　本文に入れてお問合せください。\r\n\r\n※キャンセル（解約申請）されている場合でも、行き違いにて当メールが\r\n　配信されてしまう場合がございます。その際は大変お手数ですが、下記\r\n　購入店舗様に直接お問合せください。\r\n\r\n\r\n■商品・返品・配送に関するお問い合わせは：\r\n\r\n直接購入店舗様にお問い合わせ下さい。\r\n購入店舗：{SiteNameKj}　\r\n電話：{Phone}\r\n\r\n※商品到着から7日以降のキャンセルはできませんのでご注意ください。\r\n店舗との同意の上キャンセルにより商品を返品される場合はその旨、\r\n下記メールアドレスまで注文内容のご連絡をお願いします。\r\n\r\nsupport@thebase.in\r\n\r\nキャンセルを行なわないと\r\n商品代金支払いの\r\nご請求届き続けますのでご注意ください。\r\n\r\n{SiteNameKj} は BASE ( https://thebase.in ) で作成されています。 \r\nBASEは誰でも簡単に無料でネットショップが開設できるサービスです。\r\n\r\n■お支払いに関するお問い合わせは：\r\n\r\nBASE 後払い決済　窓口\r\nTEL:[03-6279-1149](平日土日9:00～18:00)\r\nMail: atobarai@thebase.in\r\n\r\n\r\n───────────────────────────────────\r\n\r\nBASE (ベイス)\r\nhttps://thebase.in\r\n\r\n お問合せ先:[03-6279-1149]\r\n 営業時間：9:00～18:00　年中無休（年末・年始のぞく）\r\n  mail: atobarai@thebase.in\r\n\r\n───────────────────────────────────\r\n', '4', now(), '9', now(), '9', '1');

/* 加盟店 */
ALTER TABLE T_Enterprise ADD COLUMN CreditTransferFlg TINYINT NOT NULL DEFAULT 0 AFTER ApiOrderRestTimeOutFlg;

/* サイト */
ALTER TABLE  T_Site ADD COLUMN FirstCreditTransferClaimFee INT NULL AFTER ReClaimFee;
ALTER TABLE  T_Site ADD COLUMN CreditTransferClaimFee INT NULL AFTER FirstCreditTransferClaimFee;

/* 注文_会計 */
ALTER TABLE  AT_Order ADD COLUMN CreditTransferRequestFlg INT DEFAULT 0 AFTER ResumeFlg;


-- ---------------------------
-- マイページスキーマ向け
-- ---------------------------
-- Viewの再構成 ※運用環境、公開環境はスキーマが異なるので注意
DROP VIEW IF EXISTS `MAV_Order`;

CREATE VIEW `MAV_Order` AS
    SELECT *
    FROM coraldb_new01.AT_Order
;

DROP VIEW IF EXISTS `MV_EnterpriseCustomer`;

CREATE VIEW `MV_EnterpriseCustomer` AS
    SELECT *
    FROM coraldb_new01.T_EnterpriseCustomer
;
