/* T_Enterprise çÄñ⁄í«â¡ */
ALTER TABLE T_Enterprise ADD COLUMN `BillingAgentFlg` TINYINT NOT NULL DEFAULT 0 AFTER `SubscriberCode`;
ALTER TABLE T_Enterprise ADD COLUMN `IluCooperationFlg` TINYINT NOT NULL DEFAULT 1 AFTER `BillingAgentFlg`;

/* T_SiteçÄñ⁄í«â¡ */
ALTER TABLE T_Site ADD COLUMN `ReissueCount` INT NULL AFTER `CSClaimFeeDK`;

/* T_ClaimControlçÄñ⁄í«â¡ */
ALTER TABLE T_ClaimControl ADD COLUMN `ReissueCount` INT NOT NULL DEFAULT 0 AFTER `CreditSettlementDecisionDate`;

/* T_OrderAddInfo í«â¡ */
DROP TABLE IF EXISTS `T_OrderAddInfo`;
CREATE TABLE `T_OrderAddInfo` (
  `OrderSeq` bigint(20) NOT NULL ,
  `Free1` text DEFAULT NULL,
  `Free2` text DEFAULT NULL,
  `Free3` text DEFAULT NULL,
  `Free4` text DEFAULT NULL,
  `Free5` text DEFAULT NULL,
  `Free6` text DEFAULT NULL,
  `Free7` text DEFAULT NULL,
  `Free8` text DEFAULT NULL,
  `Free9` text DEFAULT NULL,
  `Free10` text DEFAULT NULL,
  `Free11` text DEFAULT NULL,
  `Free12` text DEFAULT NULL,
  `Free13` text DEFAULT NULL,
  `Free14` text DEFAULT NULL,
  `Free15` text DEFAULT NULL,
  `Free16` text DEFAULT NULL,
  `Free17` text DEFAULT NULL,
  `Free18` text DEFAULT NULL,
  `Free19` text DEFAULT NULL,
  `Free20` text DEFAULT NULL,
  PRIMARY KEY (`OrderSeq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- êøãÅCSVÉeÉìÉvÉåÅ[ÉgÅyêøãÅë„çsÉvÉâÉìópÅz
INSERT INTO M_TemplateHeader VALUES( 98 , 'CKI04048_1', 0, 0, 0, 'êøãÅë„çsÉvÉâÉìóp', 1, ',', '\"' ,'*' ,0,'KI04048', NULL, NOW(), 9, NOW(), 9,1);
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 1, 'PostalCode', 'å⁄ãqóXï÷î‘çÜ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 2, 'UnitingAddress', 'å⁄ãqèZèä', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 3, 'NameKj', 'å⁄ãqéÅñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 4, 'OrderId', 'íçï∂ÇhÇc', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 5, 'ReceiptOrderDate', 'íçï∂ì˙', 'DATE', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 6, 'SiteNameKj', 'çwì¸ìXñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 7, 'Url', 'çwì¸ìXURL', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 8, 'ContactPhoneNumber', 'çwì¸ìXìdòbî‘çÜ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 9, 'ClaimAmount', 'êøãÅã‡äz', 'BIGINT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 10, 'CarriageFee', 'ëóóø', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 11, 'ChargeFee', 'åàçœéËêîóø', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 12, 'ReIssueCount', 'êøãÅâÒêî', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 13, 'LimitDate', 'éxï•ä˙å¿ì˙', 'DATE', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 14, 'Cv_BarcodeData2', 'ÉoÅ[ÉRÅ[ÉhÉfÅ[É^', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 15, 'ItemNameKj_1', 'è§ïiñºÇP', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 16, 'ItemNum_1', 'êîó ÇP', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 17, 'UnitPrice_1', 'íPâøÇP', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 18, 'ItemNameKj_2', 'è§ïiñºÇQ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 19, 'ItemNum_2', 'êîó ÇQ', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 20, 'UnitPrice_2', 'íPâøÇQ', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 21, 'ItemNameKj_3', 'è§ïiñºÇR', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 22, 'ItemNum_3', 'êîó ÇR', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 23, 'UnitPrice_3', 'íPâøÇR', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 24, 'ItemNameKj_4', 'è§ïiñºÇS', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 25, 'ItemNum_4', 'êîó ÇS', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 26, 'UnitPrice_4', 'íPâøÇS', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 27, 'ItemNameKj_5', 'è§ïiñºÇT', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 28, 'ItemNum_5', 'êîó ÇT', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 29, 'UnitPrice_5', 'íPâøÇT', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 30, 'ItemNameKj_6', 'è§ïiñºÇU', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 31, 'ItemNum_6', 'êîó ÇU', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 32, 'UnitPrice_6', 'íPâøÇU', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 33, 'ItemNameKj_7', 'è§ïiñºÇV', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 34, 'ItemNum_7', 'êîó ÇV', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 35, 'UnitPrice_7', 'íPâøÇV', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 36, 'ItemNameKj_8', 'è§ïiñºÇW', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 37, 'ItemNum_8', 'êîó ÇW', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 38, 'UnitPrice_8', 'íPâøÇW', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 39, 'ItemNameKj_9', 'è§ïiñºÇX', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 40, 'ItemNum_9', 'êîó ÇX', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 41, 'UnitPrice_9', 'íPâøÇX', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 42, 'ItemNameKj_10', 'è§ïiñºÇPÇO', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 43, 'ItemNum_10', 'êîó ÇPÇO', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 44, 'UnitPrice_10', 'íPâøÇPÇO', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 45, 'ItemNameKj_11', 'è§ïiñºÇPÇP', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 46, 'ItemNum_11', 'êîó ÇPÇP', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 47, 'UnitPrice_11', 'íPâøÇPÇP', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 48, 'ItemNameKj_12', 'è§ïiñºÇPÇQ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 49, 'ItemNum_12', 'êîó ÇPÇQ', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 50, 'UnitPrice_12', 'íPâøÇPÇQ', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 51, 'ItemNameKj_13', 'è§ïiñºÇPÇR', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 52, 'ItemNum_13', 'êîó ÇPÇR', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 53, 'UnitPrice_13', 'íPâøÇPÇR', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 54, 'ItemNameKj_14', 'è§ïiñºÇPÇS', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 55, 'ItemNum_14', 'êîó ÇPÇS', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 56, 'UnitPrice_14', 'íPâøÇPÇS', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 57, 'ItemNameKj_15', 'è§ïiñºÇPÇT', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 58, 'ItemNum_15', 'êîó ÇPÇT', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 59, 'UnitPrice_15', 'íPâøÇPÇT', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 60, 'ItemNameKj_16', 'è§ïiñºÇPÇU', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 61, 'ItemNum_16', 'êîó ÇPÇU', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 62, 'UnitPrice_16', 'íPâøÇPÇU', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 63, 'ItemNameKj_17', 'è§ïiñºÇPÇV', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 64, 'ItemNum_17', 'êîó ÇPÇV', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 65, 'UnitPrice_17', 'íPâøÇPÇV', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 66, 'ItemNameKj_18', 'è§ïiñºÇPÇW', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 67, 'ItemNum_18', 'êîó ÇPÇW', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 68, 'UnitPrice_18', 'íPâøÇPÇW', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 69, 'ItemNameKj_19', 'è§ïiñºÇPÇX', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 70, 'ItemNum_19', 'êîó ÇPÇX', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 71, 'UnitPrice_19', 'íPâøÇPÇX', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 72, 'ClaimFee', 'çƒêøãÅî≠çséËêîóø', 'BIGINT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 73, 'DamageInterestAmount', 'íxâÑëπäQã‡', 'BIGINT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 74, 'TotalItemPrice', 'è¨åv', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 75, 'Ent_OrderId', 'îCà”íçï∂î‘çÜ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 76, 'TaxAmount', 'è¡îÔê≈äz', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 77, 'Cv_ReceiptAgentName', 'CVSé˚î[ë„çsâÔé–ñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 78, 'Cv_SubscriberName', 'CVSé˚î[ë„çsâ¡ì¸é“ñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 79, 'Cv_BarcodeData', 'ÉoÅ[ÉRÅ[ÉhÉfÅ[É^(CDït);', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 80, 'Cv_BarcodeString1', 'ÉoÅ[ÉRÅ[Éhï∂éö1', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 81, 'Cv_BarcodeString2', 'ÉoÅ[ÉRÅ[Éhï∂éö2', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 82, 'Bk_BankCode', 'ã‚çså˚ç¿ - ã‚çsÉRÅ[Éh', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 83, 'Bk_BranchCode', 'ã‚çså˚ç¿ - éxìXÉRÅ[Éh', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 84, 'Bk_BankName', 'ã‚çså˚ç¿ - ã‚çsñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 85, 'Bk_BranchName', 'ã‚çså˚ç¿ - éxìXñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 86, 'Bk_DepositClass', 'ã‚çså˚ç¿ - å˚ç¿éÌï ', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 87, 'Bk_AccountNumber', 'ã‚çså˚ç¿ - å˚ç¿î‘çÜ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 88, 'Bk_AccountHolder', 'ã‚çså˚ç¿ - å˚ç¿ñºã`', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 89, 'Bk_AccountHolderKn', 'ã‚çså˚ç¿ - å˚ç¿ñºã`ÉJÉi', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 90, 'Yu_SubscriberName', 'Ç‰Ç§ÇøÇÂå˚ç¿ - â¡ì¸é“ñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 91, 'Yu_AccountNumber', 'Ç‰Ç§ÇøÇÂå˚ç¿ - å˚ç¿î‘çÜ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 92, 'Yu_ChargeClass', 'Ç‰Ç§ÇøÇÂå˚ç¿ - ï•çûïâíSãÊï™', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 93, 'Yu_MtOcrCode1', 'Ç‰Ç§ÇøÇÂå˚ç¿ - MTópOCRÉRÅ[Éh1', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 94, 'Yu_MtOcrCode2', 'Ç‰Ç§ÇøÇÂå˚ç¿ - MTópOCRÉRÅ[Éh2', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 95, 'MypageToken', 'É}ÉCÉyÅ[ÉWÉçÉOÉCÉìÉpÉXÉèÅ[Éh', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 96, 'ItemsCount', 'è§ïiçáåvêî', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 97, 'TaxClass', 'è¡îÔê≈ãÊï™', 'INT', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 98, 'CorporateName', 'ñ@êlñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 99, 'DivisionName', 'ïîèêñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 100, 'CpNameKj', 'íSìñé“ñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 101, 'FreeColumn1', 'é©óRçÄñ⁄ÇP', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 102, 'FreeColumn2', 'é©óRçÄñ⁄ÇQ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 103, 'FreeColumn3', 'é©óRçÄñ⁄ÇR', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 104, 'FreeColumn4', 'é©óRçÄñ⁄ÇS', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 105, 'FreeColumn5', 'é©óRçÄñ⁄ÇT', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 106, 'FreeColumn6', 'é©óRçÄñ⁄ÇU', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 107, 'FreeColumn7', 'é©óRçÄñ⁄ÇV', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 108, 'FreeColumn8', 'é©óRçÄñ⁄ÇW', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 109, 'FreeColumn9', 'é©óRçÄñ⁄ÇX', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 110, 'FreeColumn10', 'é©óRçÄñ⁄ÇPÇO', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 111, 'FreeColumn11', 'é©óRçÄñ⁄ÇPÇP', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 112, 'FreeColumn12', 'é©óRçÄñ⁄ÇPÇQ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 113, 'FreeColumn13', 'é©óRçÄñ⁄ÇPÇR', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 114, 'FreeColumn14', 'é©óRçÄñ⁄ÇPÇS', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 115, 'FreeColumn15', 'é©óRçÄñ⁄ÇPÇT', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 116, 'FreeColumn16', 'é©óRçÄñ⁄ÇPÇU', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 117, 'FreeColumn17', 'é©óRçÄñ⁄ÇPÇV', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 118, 'FreeColumn18', 'é©óRçÄñ⁄ÇPÇW', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 119, 'FreeColumn19', 'é©óRçÄñ⁄ÇPÇX', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 120, 'FreeColumn20', 'é©óRçÄñ⁄ÇQÇO', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 121, 'EntNameKj', 'î≠çså≥ñº', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 122, 'EntPostalCode', 'î≠çså≥óXï÷î‘çÜ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 123, 'EntAddress1', 'î≠çså≥èZèäÇP', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`)
VALUES ( 98, 124, 'EntAddress2', 'î≠çså≥èZèäÇQ', 'VARCHAR', 0, NULL, 0, NULL, NULL, NULL, NOW(), 9, NOW(), 9, 1 );


-- ì¸ã‡ï˚ñ@ÅiPayPayÅj
INSERT INTO M_Code(CodeId, KeyCode, KeyContent, Class1, Class2, Class3, Note, SystemFlg, RegistDate, RegistId, UpdateDate, UpdateId, ValidFlg)
VALUES (198, 6, 'PayPay', null, null, null, 'âº', 0, NOW(), 83, NOW(), 83,1 );


/* àÍäáíçï∂ìoò^ÅiCSVégópÅj */
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free1',  'é©óRì¸óÕèÓïÒÇPçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free2',  'é©óRì¸óÕèÓïÒÇQçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free3',  'é©óRì¸óÕèÓïÒÇRçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free4',  'é©óRì¸óÕèÓïÒÇSçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free5',  'é©óRì¸óÕèÓïÒÇTçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free6',  'é©óRì¸óÕèÓïÒÇUçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free7',  'é©óRì¸óÕèÓïÒÇVçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free8',  'é©óRì¸óÕèÓïÒÇWçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free9',  'é©óRì¸óÕèÓïÒÇXçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free10', 'é©óRì¸óÕèÓïÒÇPÇOçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free11', 'é©óRì¸óÕèÓïÒÇPÇPçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free12', 'é©óRì¸óÕèÓïÒÇPÇQçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free13', 'é©óRì¸óÕèÓïÒÇPÇRçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free14', 'é©óRì¸óÕèÓïÒÇPÇSçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free15', 'é©óRì¸óÕèÓïÒÇPÇTçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free16', 'é©óRì¸óÕèÓïÒÇPÇUçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free17', 'é©óRì¸óÕèÓïÒÇPÇVçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free18', 'é©óRì¸óÕèÓïÒÇPÇWçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free19', 'é©óRì¸óÕèÓïÒÇPÇXçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free20', 'é©óRì¸óÕèÓïÒÇQÇOçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 9, NOW(), 9, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_1' ) group by TemplateSeq;

/* àÍäáíçï∂èCê≥ÅiCSVégópÅj */
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free1',  'é©óRì¸óÕèÓïÒÇPçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free2',  'é©óRì¸óÕèÓïÒÇQçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free3',  'é©óRì¸óÕèÓïÒÇRçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free4',  'é©óRì¸óÕèÓïÒÇSçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free5',  'é©óRì¸óÕèÓïÒÇTçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free6',  'é©óRì¸óÕèÓïÒÇUçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free7',  'é©óRì¸óÕèÓïÒÇVçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free8',  'é©óRì¸óÕèÓïÒÇWçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free9',  'é©óRì¸óÕèÓïÒÇXçsñ⁄',   'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free10', 'é©óRì¸óÕèÓïÒÇPÇOçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free11', 'é©óRì¸óÕèÓïÒÇPÇPçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free12', 'é©óRì¸óÕèÓïÒÇPÇQçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free13', 'é©óRì¸óÕèÓïÒÇPÇRçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free14', 'é©óRì¸óÕèÓïÒÇPÇSçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free15', 'é©óRì¸óÕèÓïÒÇPÇTçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free16', 'é©óRì¸óÕèÓïÒÇPÇUçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free17', 'é©óRì¸óÕèÓïÒÇPÇVçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free18', 'é©óRì¸óÕèÓïÒÇPÇWçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free19', 'é©óRì¸óÕèÓïÒÇPÇXçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
INSERT INTO `M_TemplateField` (`TemplateSeq`,`ListNumber`,`PhysicalName`,`LogicalName`,`FieldClass`,`RequiredFlg`,`DefaultValue`,`DispWidth`,`TableName`,`ValidationRegex`,`ApplicationData`,`RegistDate`,`RegistId`,`UpdateDate`,`UpdateId`,`ValidFlg`) SELECT TemplateSeq, MAX(ListNumber)+1, 'Free20', 'é©óRì¸óÕèÓïÒÇQÇOçsñ⁄', 'VARCHAR', 0, null, 0, 'T_OrderAddInfo', '/^.{0,60}$/', '{"group":"order"}', NOW(), 1, NOW(), 1, 0 from M_TemplateField where TemplateSeq IN (SELECT TemplateSeq FROM M_TemplateHeader WHERE TemplateId = 'CKA01001_2' ) group by TemplateSeq;
