/*ÉRÉÅÉìÉgê›íËÉhÉçÉbÉvÉ_ÉEÉìÇ…í«â¡*/
INSERT INTO M_CodeManagement VALUES(207,'êøãÅèëCSVÇÃè§ïiñæç◊êîëùâ¡ëŒè€OEM',NULL,'êøãÅèëCSVÇÃè§ïiñæç◊êîëùâ¡ëŒè€OEM',0,NULL,0,NULL,0,NULL,NOW(),1,NOW(),1,1);
/*ÉRÉÅÉìÉgê›íËÇÃÉtÉBÅ[ÉãÉhÇ…í«â¡*/
INSERT INTO M_Code VALUES(207,1,'ëŒè€OEM',NULL,NULL,NULL,'6',0,NOW(),1,NOW(),1,1);

/* ÉyÉCÉWÅ[ópÉeÉìÉvÉåÅ[Égí«â¡ */
INSERT INTO M_TemplateHeader VALUES('104', 'CKI04049_2', '0', '0', '0', 'ÉyÉCÉWÅ[êøãÅÉfÅ[É^CSVÅièââÒïïèëÅj', '1', ',', '\"', '*', '0', 'KI04049', NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateHeader VALUES('105', 'CKI04049_3', '0', '0', '0', 'ÉyÉCÉWÅ[êøãÅÉfÅ[É^CSVÅièââÒïïèëå¬ï Åj', '1', ',', '\"', '*', '0', 'KI04049', NULL, NOW(), '9', NOW(), '9', '1');

/*ÉeÉìÉvÉåÅ[Égí«â¡( è§ïi20-30ì¸ÇÍë÷Ç¶çœÇ› & ÉyÉCÉWÅ[çÄñ⁄çûÇ› )*/
INSERT INTO M_TemplateField VALUES('104', '1', 'PostalCode', 'å⁄ãqóXï÷î‘çÜ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '2', 'UnitingAddress', 'å⁄ãqèZèä', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '3', 'NameKj', 'å⁄ãqéÅñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '4', 'OrderId', 'íçï∂ÇhÇc', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '5', 'ReceiptOrderDate', 'íçï∂ì˙', 'DATE', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '6', 'SiteNameKj', 'çwì¸ìXñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '7', 'Url', 'çwì¸ìXURL', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '8', 'ContactPhoneNumber', 'çwì¸ìXìdòbî‘çÜ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '9', 'ClaimAmount', 'êøãÅã‡äz', 'BIGINT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '10', 'CarriageFee', 'ëóóø', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '11', 'ChargeFee', 'åàçœéËêîóø', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '12', 'ReIssueCount', 'êøãÅâÒêî', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '13', 'LimitDate', 'éxï•ä˙å¿ì˙', 'DATE', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '14', 'Cv_BarcodeData2', 'ÉoÅ[ÉRÅ[ÉhÉfÅ[É^', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '15', 'ItemNameKj_1', 'è§ïiñºÇP', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '16', 'ItemNum_1', 'êîó ÇP', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '17', 'UnitPrice_1', 'íPâøÇP', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '18', 'ItemNameKj_2', 'è§ïiñºÇQ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '19', 'ItemNum_2', 'êîó ÇQ', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '20', 'UnitPrice_2', 'íPâøÇQ', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '21', 'ItemNameKj_3', 'è§ïiñºÇR', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '22', 'ItemNum_3', 'êîó ÇR', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '23', 'UnitPrice_3', 'íPâøÇR', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '24', 'ItemNameKj_4', 'è§ïiñºÇS', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '25', 'ItemNum_4', 'êîó ÇS', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '26', 'UnitPrice_4', 'íPâøÇS', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '27', 'ItemNameKj_5', 'è§ïiñºÇT', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '28', 'ItemNum_5', 'êîó ÇT', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '29', 'UnitPrice_5', 'íPâøÇT', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '30', 'ItemNameKj_6', 'è§ïiñºÇU', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '31', 'ItemNum_6', 'êîó ÇU', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '32', 'UnitPrice_6', 'íPâøÇU', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '33', 'ItemNameKj_7', 'è§ïiñºÇV', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '34', 'ItemNum_7', 'êîó ÇV', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '35', 'UnitPrice_7', 'íPâøÇV', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '36', 'ItemNameKj_8', 'è§ïiñºÇW', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '37', 'ItemNum_8', 'êîó ÇW', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '38', 'UnitPrice_8', 'íPâøÇW', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '39', 'ItemNameKj_9', 'è§ïiñºÇX', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '40', 'ItemNum_9', 'êîó ÇX', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '41', 'UnitPrice_9', 'íPâøÇX', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '42', 'ItemNameKj_10', 'è§ïiñºÇPÇO', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '43', 'ItemNum_10', 'êîó ÇPÇO', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '44', 'UnitPrice_10', 'íPâøÇPÇO', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '45', 'ItemNameKj_11', 'è§ïiñºÇPÇP', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '46', 'ItemNum_11', 'êîó ÇPÇP', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '47', 'UnitPrice_11', 'íPâøÇPÇP', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '48', 'ItemNameKj_12', 'è§ïiñºÇPÇQ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '49', 'ItemNum_12', 'êîó ÇPÇQ', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '50', 'UnitPrice_12', 'íPâøÇPÇQ', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '51', 'ItemNameKj_13', 'è§ïiñºÇPÇR', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '52', 'ItemNum_13', 'êîó ÇPÇR', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '53', 'UnitPrice_13', 'íPâøÇPÇR', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '54', 'ItemNameKj_14', 'è§ïiñºÇPÇS', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '55', 'ItemNum_14', 'êîó ÇPÇS', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '56', 'UnitPrice_14', 'íPâøÇPÇS', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '57', 'ItemNameKj_15', 'è§ïiñºÇPÇT', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '58', 'ItemNum_15', 'êîó ÇPÇT', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '59', 'UnitPrice_15', 'íPâøÇPÇT', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '60', 'ItemNameKj_16', 'è§ïiñºÇPÇU', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '61', 'ItemNum_16', 'êîó ÇPÇU', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '62', 'UnitPrice_16', 'íPâøÇPÇU', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '63', 'ItemNameKj_17', 'è§ïiñºÇPÇV', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '64', 'ItemNum_17', 'êîó ÇPÇV', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '65', 'UnitPrice_17', 'íPâøÇPÇV', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '66', 'ItemNameKj_18', 'è§ïiñºÇPÇW', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '67', 'ItemNum_18', 'êîó ÇPÇW', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '68', 'UnitPrice_18', 'íPâøÇPÇW', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '69', 'ItemNameKj_19', 'è§ïiñºÇPÇX', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '70', 'ItemNum_19', 'êîó ÇPÇX', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '71', 'UnitPrice_19', 'íPâøÇPÇX', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '72', 'ClaimFee', 'çƒêøãÅî≠çséËêîóø', 'BIGINT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '73', 'DamageInterestAmount', 'íxâÑëπäQã‡', 'BIGINT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '74', 'TotalItemPrice', 'è¨åv', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '75', 'Ent_OrderId', 'îCà”íçï∂î‘çÜ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '76', 'TaxAmount', 'è¡îÔê≈äz', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '77', 'Cv_ReceiptAgentName', 'CVSé˚î[ë„çsâÔé–ñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '78', 'Cv_SubscriberName', 'CVSé˚î[ë„çsâ¡ì¸é“ñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '79', 'Cv_BarcodeData', 'ÉoÅ[ÉRÅ[ÉhÉfÅ[É^(CDït)', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '80', 'Cv_BarcodeString1', 'ÉoÅ[ÉRÅ[Éhï∂éö1', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '81', 'Cv_BarcodeString2', 'ÉoÅ[ÉRÅ[Éhï∂éö2', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '82', 'Bk_BankCode', 'ã‚çså˚ç¿ - ã‚çsÉRÅ[Éh', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '83', 'Bk_BranchCode', 'ã‚çså˚ç¿ - éxìXÉRÅ[Éh', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '84', 'Bk_BankName', 'ã‚çså˚ç¿ - ã‚çsñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '85', 'Bk_BranchName', 'ã‚çså˚ç¿ - éxìXñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '86', 'Bk_DepositClass', 'ã‚çså˚ç¿ - å˚ç¿éÌï ', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '87', 'Bk_AccountNumber', 'ã‚çså˚ç¿ - å˚ç¿î‘çÜ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '88', 'Bk_AccountHolder', 'ã‚çså˚ç¿ - å˚ç¿ñºã`', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '89', 'Bk_AccountHolderKn', 'ã‚çså˚ç¿ - å˚ç¿ñºã`ÉJÉi', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '90', 'Yu_SubscriberName', 'Ç‰Ç§ÇøÇÂå˚ç¿ - â¡ì¸é“ñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '91', 'Yu_AccountNumber', 'Ç‰Ç§ÇøÇÂå˚ç¿ - å˚ç¿î‘çÜ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '92', 'Yu_ChargeClass', 'Ç‰Ç§ÇøÇÂå˚ç¿ - ï•çûïâíSãÊï™', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '93', 'Yu_MtOcrCode1', 'Ç‰Ç§ÇøÇÂå˚ç¿ - MTópOCRÉRÅ[Éh1', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '94', 'Yu_MtOcrCode2', 'Ç‰Ç§ÇøÇÂå˚ç¿ - MTópOCRÉRÅ[Éh2', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '95', 'MypageToken', 'É}ÉCÉyÅ[ÉWÉçÉOÉCÉìÉpÉXÉèÅ[Éh', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '96', 'ItemsCount', 'è§ïiçáåvêî', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '97', 'TaxClass', 'è¡îÔê≈ãÊï™', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '98', 'CorporateName', 'ñ@êlñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '99', 'DivisionName', 'ïîèêñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '100', 'CpNameKj', 'íSìñé“ñº', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '101', 'CustomerNumber'     , 'Ç®ãqólî‘çÜ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '102', 'ConfirmNumber'      , 'ämîFî‘çÜ', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '103', 'Bk_Number'          , 'é˚î[ã@ä÷î‘çÜ', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '104', 'ItemNameKj_20', 'è§ïiñºÇQÇO', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '105', 'ItemNum_20', 'êîó ÇQÇO', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '106', 'UnitPrice_20', 'íPâøÇQÇO', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '107', 'ItemNameKj_21', 'è§ïiñºÇQÇP', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '108', 'ItemNum_21', 'êîó ÇQÇP', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '109', 'UnitPrice_21', 'íPâøÇQÇP', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '110', 'ItemNameKj_22', 'è§ïiñºÇQÇQ', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '111', 'ItemNum_22', 'êîó ÇQÇQ', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '112', 'UnitPrice_22', 'íPâøÇQÇQ', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '113', 'ItemNameKj_23', 'è§ïiñºÇQÇR', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '114', 'ItemNum_23', 'êîó ÇQÇR', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '115', 'UnitPrice_23', 'íPâøÇQÇR', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '116', 'ItemNameKj_24', 'è§ïiñºÇQÇS', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '117', 'ItemNum_24', 'êîó ÇQÇS', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '118', 'UnitPrice_24', 'íPâøÇQÇS', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '119', 'ItemNameKj_25', 'è§ïiñºÇQÇT', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '120', 'ItemNum_25', 'êîó ÇQÇT', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '121', 'UnitPrice_25', 'íPâøÇQÇT', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '122', 'ItemNameKj_26', 'è§ïiñºÇQÇU', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '123', 'ItemNum_26', 'êîó ÇQÇU', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '124', 'UnitPrice_26', 'íPâøÇQÇU', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '125', 'ItemNameKj_27', 'è§ïiñºÇQÇV', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '126', 'ItemNum_27', 'êîó ÇQÇV', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '127', 'UnitPrice_27', 'íPâøÇQÇV', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '128', 'ItemNameKj_28', 'è§ïiñºÇQÇW', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '129', 'ItemNum_28', 'êîó ÇQÇW', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '130', 'UnitPrice_28', 'íPâøÇQÇW', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '131', 'ItemNameKj_29', 'è§ïiñºÇQÇX', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '132', 'ItemNum_29', 'êîó ÇQÇX', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '133', 'UnitPrice_29', 'íPâøÇQÇX', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '134', 'ItemNameKj_30', 'è§ïiñºÇRÇO', 'VARCHAR', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '135', 'ItemNum_30', 'êîó ÇRÇO', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES('104', '136', 'UnitPrice_30', 'íPâøÇRÇO', 'INT', '0', NULL, '0', NULL, NULL, NULL, NOW(), '9', NOW(), '9', '1');

/*ÉeÉìÉvÉåÅ[Égí«â¡( è§ïi20-30ì¸ÇÍë÷Ç¶çœÇ› & ÉyÉCÉWÅ[çÄñ⁄çûÇ› )*/
INSERT INTO M_TemplateField VALUES ('105', '1', 'PostalCode'           ,'å⁄ãqóXï÷î‘çÜ'                  ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '2', 'UnitingAddress'       ,'å⁄ãqèZèä'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '3', 'NameKj'               ,'å⁄ãqéÅñº'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '4', 'OrderId'              ,'íçï∂ÇhÇc'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '5', 'ReceiptOrderDate'     ,'íçï∂ì˙'                        ,'DATE'    ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '6', 'SiteNameKj'           ,'çwì¸ìXñº'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '7', 'Url'                  ,'çwì¸ìXURL'                     ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '8', 'ContactPhoneNumber'   ,'çwì¸ìXìdòbî‘çÜ'                ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '9', 'ClaimAmount'          ,'êøãÅã‡äz'                      ,'BIGINT'  ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '10', 'CarriageFee'         ,'ëóóø'                          ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '11', 'ChargeFee'           ,'åàçœéËêîóø'                    ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '12', 'ReIssueCount'        ,'êøãÅâÒêî'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '13', 'LimitDate'           ,'éxï•ä˙å¿ì˙'                    ,'DATE'    ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '14', 'Cv_BarcodeData2'     ,'ÉoÅ[ÉRÅ[ÉhÉfÅ[É^'              ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '15', 'ItemNameKj_1'        ,'è§ïiñºÇP'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '16', 'ItemNum_1'           ,'êîó ÇP'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '17', 'UnitPrice_1'         ,'íPâøÇP'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '18', 'ItemNameKj_2'        ,'è§ïiñºÇQ'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '19', 'ItemNum_2'           ,'êîó ÇQ'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '20', 'UnitPrice_2'         ,'íPâøÇQ'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '21', 'ItemNameKj_3'        ,'è§ïiñºÇR'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '22', 'ItemNum_3'           ,'êîó ÇR'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '23', 'UnitPrice_3'         ,'íPâøÇR'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '24', 'ItemNameKj_4'        ,'è§ïiñºÇS'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '25', 'ItemNum_4'           ,'êîó ÇS'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '26', 'UnitPrice_4'         ,'íPâøÇS'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '27', 'ItemNameKj_5'        ,'è§ïiñºÇT'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '28', 'ItemNum_5'           ,'êîó ÇT'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '29', 'UnitPrice_5'         ,'íPâøÇT'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '30', 'ItemNameKj_6'        ,'è§ïiñºÇU'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '31', 'ItemNum_6'           ,'êîó ÇU'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '32', 'UnitPrice_6'         ,'íPâøÇU'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '33', 'ItemNameKj_7'        ,'è§ïiñºÇV'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '34', 'ItemNum_7'           ,'êîó ÇV'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '35', 'UnitPrice_7'         ,'íPâøÇV'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '36', 'ItemNameKj_8'        ,'è§ïiñºÇW'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '37', 'ItemNum_8'           ,'êîó ÇW'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '38', 'UnitPrice_8'         ,'íPâøÇW'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '39', 'ItemNameKj_9'        ,'è§ïiñºÇX'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '40', 'ItemNum_9'           ,'êîó ÇX'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '41', 'UnitPrice_9'         ,'íPâøÇX'                        ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '42', 'ItemNameKj_10'       ,'è§ïiñºÇPÇO'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '43', 'ItemNum_10'          ,'êîó ÇPÇO'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '44', 'UnitPrice_10'        ,'íPâøÇPÇO'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '45', 'ItemNameKj_11'       ,'è§ïiñºÇPÇP'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '46', 'ItemNum_11'          ,'êîó ÇPÇP'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '47', 'UnitPrice_11'        ,'íPâøÇPÇP'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '48', 'ItemNameKj_12'       ,'è§ïiñºÇPÇQ'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '49', 'ItemNum_12'          ,'êîó ÇPÇQ'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '50', 'UnitPrice_12'        ,'íPâøÇPÇQ'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '51', 'ItemNameKj_13'       ,'è§ïiñºÇPÇR'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '52', 'ItemNum_13'          ,'êîó ÇPÇR'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '53', 'UnitPrice_13'        ,'íPâøÇPÇR'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '54', 'ItemNameKj_14'       ,'è§ïiñºÇPÇS'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '55', 'ItemNum_14'          ,'êîó ÇPÇS'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '56', 'UnitPrice_14'        ,'íPâøÇPÇS'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '57', 'ItemNameKj_15'       ,'è§ïiñºÇPÇT'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '58', 'ItemNum_15'          ,'êîó ÇPÇT'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '59', 'UnitPrice_15'        ,'íPâøÇPÇT'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '60', 'ItemNameKj_16'       ,'è§ïiñºÇPÇU'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '61', 'ItemNum_16'          ,'êîó ÇPÇU'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '62', 'UnitPrice_16'        ,'íPâøÇPÇU'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '63', 'ItemNameKj_17'       ,'è§ïiñºÇPÇV'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '64', 'ItemNum_17'          ,'êîó ÇPÇV'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '65', 'UnitPrice_17'        ,'íPâøÇPÇV'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '66', 'ItemNameKj_18'       ,'è§ïiñºÇPÇW'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '67', 'ItemNum_18'          ,'êîó ÇPÇW'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '68', 'UnitPrice_18'        ,'íPâøÇPÇW'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '69', 'ItemNameKj_19'       ,'è§ïiñºÇPÇX'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '70', 'ItemNum_19'          ,'êîó ÇPÇX'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '71', 'UnitPrice_19'        ,'íPâøÇPÇX'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '72', 'ClaimFee'            ,'çƒêøãÅî≠çséËêîóø'              ,'BIGINT'  ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '73', 'DamageInterestAmount','íxâÑëπäQã‡'                    ,'BIGINT'  ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '74', 'TotalItemPrice'      ,'è¨åv'                          ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '75', 'Ent_OrderId'         ,'îCà”íçï∂î‘çÜ'                  ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '76', 'TaxAmount'           ,'è¡îÔê≈äz'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '77', 'Cv_ReceiptAgentName' ,'CVSé˚î[ë„çsâÔé–ñº'             ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '78', 'Cv_SubscriberName'   ,'CVSé˚î[ë„çsâ¡ì¸é“ñº'           ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '79', 'Cv_BarcodeData'      ,'ÉoÅ[ÉRÅ[ÉhÉfÅ[É^(CDït)'        ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '80', 'Cv_BarcodeString1'   ,'ÉoÅ[ÉRÅ[Éhï∂éö1'               ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '81', 'Cv_BarcodeString2'   ,'ÉoÅ[ÉRÅ[Éhï∂éö2'               ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '82', 'Bk_BankCode'         ,'ã‚çså˚ç¿ - ã‚çsÉRÅ[Éh'         ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '83', 'Bk_BranchCode'       ,'ã‚çså˚ç¿ - éxìXÉRÅ[Éh'         ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '84', 'Bk_BankName'         ,'ã‚çså˚ç¿ - ã‚çsñº'             ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '85', 'Bk_BranchName'       ,'ã‚çså˚ç¿ - éxìXñº'             ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '86', 'Bk_DepositClass'     ,'ã‚çså˚ç¿ - å˚ç¿éÌï '           ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '87', 'Bk_AccountNumber'    ,'ã‚çså˚ç¿ - å˚ç¿î‘çÜ'           ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '88', 'Bk_AccountHolder'    ,'ã‚çså˚ç¿ - å˚ç¿ñºã`'           ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '89', 'Bk_AccountHolderKn'  ,'ã‚çså˚ç¿ - å˚ç¿ñºã`ÉJÉi'       ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '90', 'Yu_SubscriberName'   ,'Ç‰Ç§ÇøÇÂå˚ç¿ - â¡ì¸é“ñº'       ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '91', 'Yu_AccountNumber'    ,'Ç‰Ç§ÇøÇÂå˚ç¿ - å˚ç¿î‘çÜ'       ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '92', 'Yu_ChargeClass'      ,'Ç‰Ç§ÇøÇÂå˚ç¿ - ï•çûïâíSãÊï™'   ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '93', 'Yu_MtOcrCode1'       ,'Ç‰Ç§ÇøÇÂå˚ç¿ - MTópOCRÉRÅ[Éh1' ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '94', 'Yu_MtOcrCode2'       ,'Ç‰Ç§ÇøÇÂå˚ç¿ - MTópOCRÉRÅ[Éh2' ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '95', 'MypageToken'         ,'É}ÉCÉyÅ[ÉWÉçÉOÉCÉìÉpÉXÉèÅ[Éh'  ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '96', 'ItemsCount'          ,'è§ïiçáåvêî'                    ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '97', 'TaxClass'            ,'è¡îÔê≈ãÊï™'                    ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '98', 'CorporateName'       ,'ñ@êlñº'                        ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '99', 'DivisionName'        ,'ïîèêñº'                        ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '100', 'CpNameKj'           ,'íSìñé“ñº'                      ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '101', 'CustomerNumber'     , 'Ç®ãqólî‘çÜ'                   ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '102', 'ConfirmNumber'      , 'ämîFî‘çÜ'                     ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '103', 'Bk_Number'          , 'é˚î[ã@ä÷î‘çÜ'                 ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '104', 'FreeColumn1'        ,'é©óRçÄñ⁄ÇP'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '105', 'FreeColumn2'        ,'é©óRçÄñ⁄ÇQ'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '106', 'FreeColumn3'        ,'é©óRçÄñ⁄ÇR'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '107', 'FreeColumn4'        ,'é©óRçÄñ⁄ÇS'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '108', 'FreeColumn5'        ,'é©óRçÄñ⁄ÇT'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '109', 'FreeColumn6'        ,'é©óRçÄñ⁄ÇU'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '110', 'FreeColumn7'        ,'é©óRçÄñ⁄ÇV'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '111', 'FreeColumn8'        ,'é©óRçÄñ⁄ÇW'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '112', 'FreeColumn9'        ,'é©óRçÄñ⁄ÇX'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '113', 'FreeColumn10'       ,'é©óRçÄñ⁄ÇPÇO'                  ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '114', 'ItemNameKj_20'      ,'è§ïiñºÇQÇO'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '115', 'ItemNum_20'         ,'êîó ÇQÇO'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '116', 'UnitPrice_20'       ,'íPâøÇQÇO'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '117', 'ItemNameKj_21'      ,'è§ïiñºÇQÇP'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '118', 'ItemNum_21'         ,'êîó ÇQÇP'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '119', 'UnitPrice_21'       ,'íPâøÇQÇP'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '120', 'ItemNameKj_22'      ,'è§ïiñºÇQÇQ'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '121', 'ItemNum_22'         ,'êîó ÇQÇQ'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '122', 'UnitPrice_22'       ,'íPâøÇQÇQ'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '123', 'ItemNameKj_23'      ,'è§ïiñºÇQÇR'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '124', 'ItemNum_23'         ,'êîó ÇQÇR'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '125', 'UnitPrice_23'       ,'íPâøÇQÇR'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '126', 'ItemNameKj_24'      ,'è§ïiñºÇQÇS'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '127', 'ItemNum_24'         ,'êîó ÇQÇS'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '128', 'UnitPrice_24'       ,'íPâøÇQÇS'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '129', 'ItemNameKj_25'      ,'è§ïiñºÇQÇT'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '130', 'ItemNum_25'         ,'êîó ÇQÇT'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '131', 'UnitPrice_25'       ,'íPâøÇQÇT'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '132', 'ItemNameKj_26'      ,'è§ïiñºÇQÇU'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '133', 'ItemNum_26'         ,'êîó ÇQÇU'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '134', 'UnitPrice_26'       ,'íPâøÇQÇU'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '135', 'ItemNameKj_27'      ,'è§ïiñºÇQÇV'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '136', 'ItemNum_27'         ,'êîó ÇQÇV'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '137', 'UnitPrice_27'       ,'íPâøÇQÇV'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '138', 'ItemNameKj_28'      ,'è§ïiñºÇQÇW'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '139', 'ItemNum_28'         ,'êîó ÇQÇW'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '140', 'UnitPrice_28'       ,'íPâøÇQÇW'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '141', 'ItemNameKj_29'      ,'è§ïiñºÇQÇX'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '142', 'ItemNum_29'         ,'êîó ÇQÇX'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '143', 'UnitPrice_29'       ,'íPâøÇQÇX'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '144', 'ItemNameKj_30'      ,'è§ïiñºÇRÇO'                    ,'VARCHAR' ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '145', 'ItemNum_30'         ,'êîó ÇRÇO'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');
INSERT INTO M_TemplateField VALUES ('105', '146', 'UnitPrice_30'       ,'íPâøÇRÇO'                      ,'INT'     ,'0' ,NULL ,'0' ,NULL ,NULL ,NULL , NOW(), '9', NOW(), '9', '1');

