<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<style>
.rowNotVisible tr:not(.titlerow) {
    display: none;
}
.rowVisible tr[errrow] {
    display: table-row;
}
td.update {
    background-color : yellow;
}
td.error {
    background-color : pink;
    /* color: white; */
}
</style>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/rwordercsv/page_menu.php'); ?>
  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">備考コメント一括登録</h3>

    <form id="saveForm" action="rwordercsv/save1" method="post">
    <input type="hidden" name="fileName" id="fileName" value="<?php echo f_e($this->fileName); ?>" />
    <input type="hidden" name="nrmCount" id="nrmCount" value="<?php echo $this->nrmCount; ?>" />
    <div style="margin: 5px 25px;">
    <?php if (strlen($this->message) > 0 ) { /* エラーメッセージあり */ ?>
        <h4><?php echo $this->message; ?></span></h4>
    <?php }elseif ($this->errCount > 0 ) {  /* エラーデータあり */ ?>
        <span style="font-size: 11px;">
            対象ファイル「<?php echo f_e($this->fileName); ?>」でエラーがあります。<BR>
            エラー内容を確認し、ファイルを修正後、再度取込してください。<BR>
            (対象件数：<?php echo $this->sumCount; ?>件&nbsp;取込OK件数：<?php echo $this->nrmCount; ?>件&nbsp;エラー件数：<?php echo $this->errCount; ?>件)
        </span>
    <?php }else{ ?>
        <span style="font-size: 11px;">
            インポートしようとしている内容は、以下の内容になります。<BR>
            間違いなければ、CSVダウンロードを行った後、確定ボタンを押してください。キャンセルする場合、キャンセルボタンを押してください。<BR>
            (対象件数：<?php echo $this->sumCount; ?>件&nbsp;取込OK件数：<?php echo $this->nrmCount; ?>件&nbsp;エラー件数：<?php echo $this->errCount; ?>件)
        </span>
    <?php } ?>
        &nbsp;<input type="checkbox" id="chkFilter">エラーのみ表示<BR>
        <div style="margin: 0px; height: 500px; border: 1px solid gray; overflow-y: scroll; ">
          <table style="margin: 0px; clear:both; font-size: 11px; table-layout:auto; white-space: nowrap;" width="100%" class="datatable" cellpadding="1" cellspacing="1" border="0" id="resultTable">
            <tbody>
              <tr class="titlerow">
                <th>行No</th>
                <th>ファイル区分</th>
                <th>注文ＩＤ</th>
                <th style="white-space: nowrap;">備考</th>
                <th>紙ストップ区分</th>
                <th>メールストップ区分</th>
                <th>請求ストップ解除日</th>
                <th>支払約束日</th>
                <th>訪問済処理区分</th>
                <th>最終回収手段</th>
                <th>最終督促日</th>
                <th>督促分類</th>
                <th>ＴＥＬ有効</th>
                <th>住所有効</th>
                <th>メール有効</th>
                <th>エラー情報</th>
              </tr>
              <?php $i = 0; ?>
              <?php foreach ($this->listData as $row) { ?>
              <tr style="background-color: red;" <?php if (strlen($row['Error']) > 0){ echo 'errrow'; } else { ; } ?>>
                <!-- 登録用項目 -->
                <input type="hidden" id="OrderSeq<?php echo $i; ?>" name="OrderSeq<?php echo $i; ?>" value="<?php echo $row['OrderSeq']; ?>" />
                <input type="hidden" id="Incre_Note<?php echo $i; ?>" name="Incre_Note<?php echo $i; ?>" value="<?php echo $row['Incre_Note']; ?>" />
                <input type="hidden" id="LetterClaimStopFlg<?php echo $i; ?>" name="LetterClaimStopFlg<?php echo $i; ?>" value="<?php echo $row['LetterClaimStopFlg']; ?>" />
                <input type="hidden" id="MailClaimStopFlg<?php echo $i; ?>" name="MailClaimStopFlg<?php echo $i; ?>" value="<?php echo $row['MailClaimStopFlg']; ?>" />
                <input type="hidden" id="ClaimStopReleaseDate<?php echo $i; ?>" name="ClaimStopReleaseDate<?php echo $i; ?>" value="<?php echo $row['ClaimStopReleaseDate']; ?>" />
                <input type="hidden" id="PromPayDate<?php echo $i; ?>" name="PromPayDate<?php echo $i; ?>" value="<?php echo $row['PromPayDate']; ?>" />
                <input type="hidden" id="VisitFlg<?php echo $i; ?>" name="VisitFlg<?php echo $i; ?>" value="<?php echo $row['VisitFlg']; ?>" />
                <input type="hidden" id="FinalityCollectionMean<?php echo $i; ?>" name="FinalityCollectionMean<?php echo $i; ?>" value="<?php echo $row['FinalityCollectionMean']; ?>" />
                <input type="hidden" id="FinalityRemindDate<?php echo $i; ?>" name="FinalityRemindDate<?php echo $i; ?>" value="<?php echo $row['FinalityRemindDate']; ?>" />
                <input type="hidden" id="RemindClass<?php echo $i; ?>" name="RemindClass<?php echo $i; ?>" value="<?php echo $row['RemindClass']; ?>" />
                <input type="hidden" id="ValidTel<?php echo $i; ?>" name="ValidTel<?php echo $i; ?>" value="<?php echo $row['ValidTel']; ?>" />
                <input type="hidden" id="ValidAddress<?php echo $i; ?>" name="ValidAddress<?php echo $i; ?>" value="<?php echo $row['ValidAddress']; ?>" />
                <input type="hidden" id="ValidMail<?php echo $i; ?>" name="ValidMail<?php echo $i; ?>" value="<?php echo $row['ValidMail']; ?>" />
                <!-- 表示項目 -->
                <td class="r_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } else { ; } ?>"><?php echo $row['RowNo']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } else { ; } ?>"><?php echo $row['FileKbn']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } else { ; } ?>"><a target="_blank" href="rworder/detail/oseq/<?php echo $row['OrderSeq']; ?>"><?php echo $row['OrderId']; ?></a></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif (strlen($row['Incre_Note']) > 0){ echo 'update'; } ?>"><?php echo $row['CaptionIncre_Note']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['LetterClaimStopFlg']      != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionLetterClaimStopFlg']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['MailClaimStopFlg']        != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionMailClaimStopFlg']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['ClaimStopReleaseDate']    != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionClaimStopReleaseDate']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['PromPayDate']             != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionPromPayDate']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['VisitFlg']                != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionVisitFlg']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['FinalityCollectionMean']  != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionFinalityCollectionMean']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['FinalityRemindDate']      != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionFinalityRemindDate']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['RemindClass']             != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionRemindClass']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['ValidTel']                != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionValidTel']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['ValidAddress']            != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionValidAddress']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } elseif ($row['ValidMail']               != $this->NO_UPDATE_VALUE) { echo 'update'; } ?>"><?php echo $row['CaptionValidMail']; ?></td>
                <td class="l_data <?php if (strlen($row['Error']) > 0){ echo 'error'; } else { ; } ?>"><?php echo $row['Error']; ?></td>
              </tr>
              <?php $i++; ?>
              <?php } ?>
            </tbody>
          </table>
        </div>
    </div>

    <table width="860" cellpadding="1" cellspacing="1" border="0">
        <tbody>
            <tr align="center">
                <td style="padding: 2px 0px">
                    <input type="button" id="download_button" value="　CSVﾀﾞｳﾝﾛｰﾄﾞ　" <?php echo ($this->errCount > 0 || strlen($this->message) > 0) ? 'disabled="disabled"' : ''; ?> />&nbsp;
                    <input type="submit" id="submit_button" value="　確　定　" disabled="disabled"; />&nbsp;
                    <input type="button" id="cancel_edit" value="キャンセル" />
                </td>
            </tr>
        </tbody>
    </table>
</form>
<br/>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
<script>
Event.observe(window, "load", function() {
  Event.observe($("download_button"), "click", function() {
	    // AJAX通信でフォーム情報をセッションに設定
	    var str = Form.serialize('saveForm');   // フォーム内容をシリアライズ
	    var url = "<?php echo $this->baseUrl; ?>/rwordercsv/jobparamset";
	    var ajax = new Ajax.Request( url, {method: 'post', parameters: str, asynchronous: false });

	    // CSV出力処理
	    var url = "<?php echo $this->baseUrl; ?>/rwordercsv/csvoutput1";
	    var ref = window.open( url );

	    // CSV出力が終わったら確定ボタンを有効にする
	    // 最大10秒待機させる
	    var wait = 0;
	    var intvl = setInterval(function() {
	    	wait++;
	        if (ref.closed == true || wait == 50){
	            clearInterval(intvl);
	            $("submit_button").disabled = "";
	        }
	    }, 200);

	    return false;
  });
  Event.observe($("cancel_edit"), "click", function() {
	location.href = "rwordercsv/form";
    return false;
  });
  $("chkFilter").onchange = function() {
		var table = $("resultTable");
		var className = "datatable";

	    if ($("chkFilter").checked) {
	    	className += " rowNotVisible rowVisible";
		}

		table.className = className;

	    return false;
  };
});
</script>
</body>
</html>
