<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<style type="text/css">
<!--
#formdiv {
	margin-left: 25px;
	text-align: center;
}
-->
</style>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/rwordercsv/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">備考コメント一括登録</h3>
    <form name="form" id="form" enctype="multipart/form-data" method="post" action="rwordercsv/confirm1">
      <div id="formdiv">
      <BR>
      登録区分&nbsp;<?php echo $this->fileClass; ?>
      <BR>
      <BR>
      備考コメント一括登録ファイル　
        <input type="file" name="cres" size="80" />
        <p><button id="import" type="button">　　インポート　　</button></p>
      </div>
    </form>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
<script>
Event.observe(window, "load", function() {
  Event.observe($("import"), "click", function() {
    var fClass = $("fileClass").value;
    if (fClass == 1) {
    	$("form").action = "rwordercsv/confirm1";
    } else {
    	$("form").action = "rwordercsv/confirm2";
    }
    $("form").submit();
    return false;
  });
});
</script>
</body>
</html>
