<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<script type="text/javascript">
Event.observe(window, 'load', function() {
	setTimeout(function() {
		window.location.href = (function(baseEle) {
			return [
				(baseEle || { href : ''}).href,
				'paying/fix'
			].map(function(path) {
				return path.replace(/^\/*/, '').replace(/\/*$/, '');
			}).join('/');
		})(document.getElementsByTagName('base')[0]);
	}, 500);
});
</script>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/paying/page_menu_for_fix.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">立替確認</h3>
    <div style="clear:both;">
		<div id="lbl1">
			事業者「<?php echo f_e($this->last_ent_name); ?>」までの処理が完了（残り：<?php echo f_e($this->remain_count); ?> 事業者）
		</div>
	</div>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
