DROP VIEW IF EXISTS AV_Order;

CREATE VIEW AV_Order
AS
SELECT 
     a.OrderSeq
    ,a.OrderId
    ,a.ReceiptOrderDate
    ,a.EnterpriseId
    ,a.SiteId
    ,a.UseAmount
    ,a.AnotherDeliFlg
    ,a.DataStatus
    ,a.CloseReason
    ,a.Incre_Status
    ,a.Incre_AtnEnterpriseScore
    ,a.Incre_AtnEnterpriseNote
    ,a.Incre_BorderScore
    ,a.Incre_BorderNote
    ,a.Incre_LimitCheckScore
    ,a.Incre_LimitCheckNote
    ,a.Incre_ScoreTotal
    ,a.Incre_DecisionDate
    ,a.Incre_DecisionOpId
    ,a.Dmi_Status
    ,a.Dmi_ResponseCode
    ,a.Dmi_DecisionDate
    ,a.Chg_Status
    ,a.Chg_FixedDate
    ,a.Chg_DecisionDate
    ,a.Chg_ExecDate
    ,a.Chg_ChargeAmount
    ,a.Rct_RejectFlg
    ,a.Rct_RejectReason
    ,a.Rct_Status
    ,a.Cnl_CantCancelFlg
    ,a.Cnl_Status
    ,a.Dmg_DecisionFlg
    ,a.Dmg_DecisionDate
    ,a.Dmg_DecisionAmount
    ,a.Dmg_DecisionReason
    ,a.Ent_OrderId
    ,a.Ent_Note
    ,a.Incre_Note
    ,a.Dmi_ResponseNote
    ,a.RegistDate
    ,a.Chg_Seq
    ,a.Bekkan
    ,a.Dmi_DecSeqId
    ,a.Rct_MailFlg
    ,a.StopClaimFlg
    ,a.MailPaymentSoonDate
    ,a.MailLimitPassageDate
    ,a.MailLimitPassageCount
    ,a.ReturnClaimFlg
    ,a.RemindClass
    ,a.TouchHistoryFlg
    ,a.BriefNote
    ,a.LonghandLetter
    ,a.VisitFlg
    ,a.FinalityCollectionMean
    ,a.FinalityRemindDate
    ,a.FinalityRemindOpId
    ,a.PromPayDate
    ,a.ClaimStopReleaseDate
    ,a.LetterClaimStopFlg
    ,a.MailClaimStopFlg
    ,a.InstallmentPlanAmount
    ,a.OutOfAmends
    ,a.OrderRegisterMethod
    ,a.ApiUserId
    ,a.CreditConditionMatchData
    ,a.Cnl_ReturnSaikenCancelFlg
    ,a.PrintedTransBeforeCancelled
    ,a.Deli_ConfirmArrivalFlg
    ,a.Deli_ConfirmArrivalDate
    ,a.CombinedClaimTargetStatus
    ,a.CombinedClaimParentFlg
    ,a.Jintec_Flags
    ,a.OemId
    ,a.Oem_OrderId
    ,a.Oem_Note
    ,a.OemBadDebtSeq
    ,a.OemBadDebtType
    ,a.T_OrderClass
    ,a.T_OrderAutoCreditJudgeClass
    ,a.ServiceTargetClass
    ,a.ServiceExpectedDate
    ,a.DailySummaryFlg
    ,a.PendingReasonCode
    ,a.ClaimSendingClass
    ,a.P_OrderSeq
    ,a.CancelBefDataStatus
    ,a.Tel30DaysFlg
    ,a.Tel90DaysFlg
    ,a.NewSystemFlg
    ,a.CreditReplyDate
    ,a.OemClaimTransDate
    ,a.OemClaimTransFlg
    ,a.ConfirmWaitingFlg
    ,a.CreditNgHiddenFlg
    ,a.Incre_JudgeScoreTotal
    ,a.Incre_CoreScoreTotal
    ,a.Incre_ItemScoreTotal
    ,a.Incre_NoteScore
    ,a.Incre_PastOrderScore
    ,a.Incre_UnpaidScore
    ,a.Incre_NonPaymentScore
    ,a.Incre_IdentityDocumentScore
    ,a.Incre_MischiefCancelScore
    ,a.Chg_NonChargeFlg
    ,a.Dmg_DecisionUseAmount
    ,a.Dmg_DecisionClaimFee
    ,a.Dmg_DecisionDamageInterestAmount
    ,a.Dmg_DecisionAdditionalClaimFee
    ,a.RegistId
    ,a.UpdateDate
    ,a.UpdateId
    ,a.ValidFlg
    ,b.Dmg_DailySummaryFlg
    
FROM T_Order a
    ,AT_Order b
WHERE a.OrderSeq = b.OrderSeq
;
