DROP VIEW IF EXISTS AV_OemClaimed;

CREATE VIEW AV_OemClaimed
AS
SELECT 
     a.OemClaimedSeq
    ,a.OemId
    ,a.FixedMonth
    ,a.Ordinal
    ,a.ProcessDate
    ,a.SettlePlanDate
    ,a.SpanFrom
    ,a.SpanTo
    ,a.OrderCount
    ,a.UseAmount
    ,a.CB_MonthlyFee
    ,a.CB_SettlementCountRKF
    ,a.CB_SettlementFeeRKF
    ,a.CB_SettlementCountSTD
    ,a.CB_SettlementFeeSTD
    ,a.CB_SettlementCountEXP
    ,a.CB_SettlementFeeEXP
    ,a.CB_SettlementCountSPC
    ,a.CB_SettlementFeeSPC
    ,a.CB_SettlementCount
    ,a.CB_SettlementFee
    ,a.CB_ClaimCountBS
    ,a.CB_ClaimFeeBS
    ,a.CB_ClaimCountDK
    ,a.CB_ClaimFeeDK
    ,a.CB_EntMonthlyCountRKF
    ,a.CB_EntMonthlyFeeRKF
    ,a.CB_EntMonthlyCountSTD
    ,a.CB_EntMonthlyFeeSTD
    ,a.CB_EntMonthlyCountEXP
    ,a.CB_EntMonthlyFeeEXP
    ,a.CB_EntMonthlyCountSPC
    ,a.CB_EntMonthlyFeeSPC
    ,a.CB_EntMonthlyCount
    ,a.CB_EntMonthlyFee
    ,a.OpDkInitCount
    ,a.OpDkInitFee
    ,a.OpDkMonthlyCount
    ,a.OpDkMonthlyFee
    ,a.OpApiRegOrdMonthlyCount
    ,a.OpApiRegOrdMonthlyFee
    ,a.OpApiAllInitCount
    ,a.OpApiAllInitFee
    ,a.OpApiAllMonthlyCount
    ,a.OpApiAllMonthlyFee
    ,a.TfReclaimCount
    ,a.TfReclaimFee
    ,a.TfDamageInterestCount
    ,a.TfDamageInterestAmount
    ,a.TfMissedReceiptCount
    ,a.TfMissedReceiptAmount
    ,a.TfDoubleReceiptCount
    ,a.TfDoubleReceiptAmount
    ,a.TfCancelCount
    ,a.TfCancelAmount
    ,a.TfDevideReceiptCount
    ,a.TfDevideReceiptAmount
    ,a.CB_AdjustmentAmount
    ,a.CB_ClaimTotal
    ,a.OM_ShopTotal
    ,a.OM_SettleShopTotal
    ,a.OM_SettlementCountRKF
    ,a.OM_SettlementFeeRKF
    ,a.OM_SettlementCountSTD
    ,a.OM_SettlementFeeSTD
    ,a.OM_SettlementCountEXP
    ,a.OM_SettlementFeeEXP
    ,a.OM_SettlementCountSPC
    ,a.OM_SettlementFeeSPC
    ,a.OM_SettlementCount
    ,a.OM_SettlementFee
    ,a.OM_ClaimCountBS
    ,a.OM_ClaimFeeBS
    ,a.OM_ClaimCountDK
    ,a.OM_ClaimFeeDK
    ,a.OM_EntMonthlyCountRKF
    ,a.OM_EntMonthlyFeeRKF
    ,a.OM_EntMonthlyCountSTD
    ,a.OM_EntMonthlyFeeSTD
    ,a.OM_EntMonthlyCountEXP
    ,a.OM_EntMonthlyFeeEXP
    ,a.OM_EntMonthlyCountSPC
    ,a.OM_EntMonthlyFeeSPC
    ,a.OM_EntMonthlyCount
    ,a.OM_EntMonthlyFee
    ,a.OM_AdjustmentAmount
    ,a.OM_TotalProfit
    ,a.CR_TotalAmount
    ,a.CR_OemAmount
    ,a.CR_EntAmount
    ,a.PayingMethod
    ,a.PC_CarryOver
    ,a.PC_ChargeCount
    ,a.PC_ChargeAmount
    ,a.PC_SettlementFee
    ,a.PC_ClaimFee
    ,a.PC_CancelCount
    ,a.PC_CalcelAmount
    ,a.PC_StampFeeCount
    ,a.PC_StampFeeTotal
    ,a.PC_MonthlyFee
    ,a.PC_TransferCommission
    ,a.PC_DecisionPayment
    ,a.PC_AdjustmentAmount
    ,a.FixedTransferAmount
    ,a.PayBackCount
    ,a.PayBackAmount
    ,a.AgencyFee
    ,a.CB_SettlementCountPlan
    ,a.CB_SettlementFeePlan
    ,a.CB_EntMonthlyCountPlan
    ,a.CB_EntMonthlyFeePlan
    ,a.OM_SettlementCountPlan
    ,a.OM_SettlementFeePlan
    ,a.OM_EntMonthlyCountPlan
    ,a.OM_EntMonthlyFeePlan
    ,a.PayingControlStatus
    ,a.RegistDate
    ,a.RegistId
    ,a.UpdateDate
    ,a.UpdateId
    ,a.ValidFlg
    ,b.DailySummaryFlg
FROM T_OemClaimed a
    ,AT_OemClaimed b
WHERE a.OemClaimedSeq = b.OemClaimedSeq
;
