DROP VIEW IF EXISTS `V_EnterpriseOperator`;

CREATE VIEW V_EnterpriseOperator AS
    SELECT
           e.EnterpriseId
          ,e.RegistDate
          ,eo.LoginId
          ,eo.LoginPasswd
          ,e.EnterpriseNameKj
          ,e.EnterpriseNameKn
          ,e.PostalCode
          ,e.PrefectureCode
          ,e.PrefectureName
          ,e.City
          ,e.Town
          ,e.Building
          ,e.Phone
          ,e.Fax
          ,e.Industry
          ,e.Plan
          ,e.MonthlyFee
          ,e.FfName
          ,e.FfCode
          ,e.FfBranchName
          ,e.FfBranchCode
          ,e.FfAccountNumber
          ,e.FfAccountClass
          ,e.FfAccountName
          ,e.CpNameKj
          ,e.CpNameKn
          ,e.DivisionName
          ,e.MailAddress
          ,e.ContactPhoneNumber
          ,e.Note
          ,e.B_ChargeFixedDate
          ,e.B_ChargeDecisionDate
          ,e.B_ChargeExecDate
          ,e.N_ChargeFixedDate
          ,e.N_ChargeDecisionDate
          ,e.N_ChargeExecDate
          ,e.ValidFlg
          ,e.InvalidatedDate
          ,e.InvalidatedReason
          ,e.RepNameKj
          ,e.RepNameKn
          ,e.PreSales
          ,e.Salesman
          ,e.TcClass
          ,e.ContactFaxNumber
          ,e.ApplicationDate
          ,e.PublishingConfirmDate
          ,e.ServiceInDate
          ,e.DocCollect
          ,e.ExaminationResult
          ,e.N_MonthlyFee
          ,e.Notice
          ,e.UnitingAddress
          ,e.Memo
          ,e.Special01Flg
          ,e.SelfBillingMode
          ,e.SelfBillingKey
          ,e.AutoCreditJudgeMode
          ,e.SelfBillingExportAllow
          ,e.CjMailMode
          ,e.CombinedClaimMode
          ,e.AutoClaimStopFlg
          ,e.UseAmountLimitForCreditJudge
          ,e.DkInitFee
          ,e.DkMonthlyFee
          ,e.ApiRegOrdMonthlyFee
          ,e.ApiAllInitFee
          ,e.ApiAllMonthlyFee
          ,e.N_DkMonthlyFee
          ,e.N_ApiRegOrdMonthlyFee
          ,e.N_ApiAllMonthlyFee
          ,e.OemId
          ,e.N_OemEntMonthlyFee
          ,e.N_OemDkMonthlyFee
          ,e.N_OemApiRegOrdMonthlyFee
          ,e.N_OemApiAllMonthlyFee
          ,eo.Hashed
          ,e.OemMonthlyFee
          ,e.N_OemMonthlyFee
          ,e.PrintEntOrderIdOnClaimFlg
          ,e.UserAmountOver
          ,e.TaxClass
          ,e.ClaimClass
          ,e.SystemClass
          ,e.JudgeSystemFlg
          ,e.AutoJudgeFlg
          ,e.JintecFlg
          ,e.ManualJudgeFlg
          ,e.CreditNgDispDays
          ,e.CombinedClaimFlg
          ,e.AutoCombinedClaimDay
          ,e.PayBackFlg
          ,e.JournalRegistDispClass
          ,e.DispOrder1
          ,e.DispOrder2
          ,e.DispOrder3
          ,e.RegUnitingAddress
          ,e.RegEnterpriseNameKj
          ,e.RegCpNameKj
          ,e.PrintAdjustmentX
          ,e.PrintAdjustmentY
          ,e.PayingCycleId
          ,e.N_PayingCycleId
          ,e.DamageInterestRate
          ,e.AutoNoGuaranteeFlg
          ,e.DispDecimalPoint
          ,e.UseAmountFractionClass
          ,e.PrintEntComment
          ,e.CombinedClaimChargeFeeFlg
          ,e.CsvRegistClass
          ,e.CsvRegistErrorClass
          ,e.ReceiptStatusSearchClass
          ,e.NN_ChargeFixedDate
          ,e.NN_ChargeExecDate
          ,e.B_MonthlyFee
          ,e.B_OemMonthlyFee
          ,e.CreditJudgePendingRequest
          ,e.HideToCbButton
          ,e.LastPasswordChanged
          ,e.OrderRevivalDisabled
          ,e.PayingMail
          ,e.DetailApiOrderStatusClass
          ,e.RegistId
          ,e.UpdateDate
          ,e.UpdateId
          ,eo.RoleCode -- 権限
          ,eo.NameKj AS UserNameKj -- ユーザー名
    FROM T_EnterpriseOperator eo
         INNER JOIN T_Enterprise e
                 ON e.EnterpriseId = eo.EnterpriseId
    WHERE eo.ValidFlg = 1 -- 有効なオペレータのみ
UNION ALL
    SELECT
           e.EnterpriseId
          ,e.RegistDate
          ,e.LoginId
          ,e.LoginPasswd
          ,e.EnterpriseNameKj
          ,e.EnterpriseNameKn
          ,e.PostalCode
          ,e.PrefectureCode
          ,e.PrefectureName
          ,e.City
          ,e.Town
          ,e.Building
          ,e.Phone
          ,e.Fax
          ,e.Industry
          ,e.Plan
          ,e.MonthlyFee
          ,e.FfName
          ,e.FfCode
          ,e.FfBranchName
          ,e.FfBranchCode
          ,e.FfAccountNumber
          ,e.FfAccountClass
          ,e.FfAccountName
          ,e.CpNameKj
          ,e.CpNameKn
          ,e.DivisionName
          ,e.MailAddress
          ,e.ContactPhoneNumber
          ,e.Note
          ,e.B_ChargeFixedDate
          ,e.B_ChargeDecisionDate
          ,e.B_ChargeExecDate
          ,e.N_ChargeFixedDate
          ,e.N_ChargeDecisionDate
          ,e.N_ChargeExecDate
          ,e.ValidFlg
          ,e.InvalidatedDate
          ,e.InvalidatedReason
          ,e.RepNameKj
          ,e.RepNameKn
          ,e.PreSales
          ,e.Salesman
          ,e.TcClass
          ,e.ContactFaxNumber
          ,e.ApplicationDate
          ,e.PublishingConfirmDate
          ,e.ServiceInDate
          ,e.DocCollect
          ,e.ExaminationResult
          ,e.N_MonthlyFee
          ,e.Notice
          ,e.UnitingAddress
          ,e.Memo
          ,e.Special01Flg
          ,e.SelfBillingMode
          ,e.SelfBillingKey
          ,e.AutoCreditJudgeMode
          ,e.SelfBillingExportAllow
          ,e.CjMailMode
          ,e.CombinedClaimMode
          ,e.AutoClaimStopFlg
          ,e.UseAmountLimitForCreditJudge
          ,e.DkInitFee
          ,e.DkMonthlyFee
          ,e.ApiRegOrdMonthlyFee
          ,e.ApiAllInitFee
          ,e.ApiAllMonthlyFee
          ,e.N_DkMonthlyFee
          ,e.N_ApiRegOrdMonthlyFee
          ,e.N_ApiAllMonthlyFee
          ,e.OemId
          ,e.N_OemEntMonthlyFee
          ,e.N_OemDkMonthlyFee
          ,e.N_OemApiRegOrdMonthlyFee
          ,e.N_OemApiAllMonthlyFee
          ,e.Hashed
          ,e.OemMonthlyFee
          ,e.N_OemMonthlyFee
          ,e.PrintEntOrderIdOnClaimFlg
          ,e.UserAmountOver
          ,e.TaxClass
          ,e.ClaimClass
          ,e.SystemClass
          ,e.JudgeSystemFlg
          ,e.AutoJudgeFlg
          ,e.JintecFlg
          ,e.ManualJudgeFlg
          ,e.CreditNgDispDays
          ,e.CombinedClaimFlg
          ,e.AutoCombinedClaimDay
          ,e.PayBackFlg
          ,e.JournalRegistDispClass
          ,e.DispOrder1
          ,e.DispOrder2
          ,e.DispOrder3
          ,e.RegUnitingAddress
          ,e.RegEnterpriseNameKj
          ,e.RegCpNameKj
          ,e.PrintAdjustmentX
          ,e.PrintAdjustmentY
          ,e.PayingCycleId
          ,e.N_PayingCycleId
          ,e.DamageInterestRate
          ,e.AutoNoGuaranteeFlg
          ,e.DispDecimalPoint
          ,e.UseAmountFractionClass
          ,e.PrintEntComment
          ,e.CombinedClaimChargeFeeFlg
          ,e.CsvRegistClass
          ,e.CsvRegistErrorClass
          ,e.ReceiptStatusSearchClass
          ,e.NN_ChargeFixedDate
          ,e.NN_ChargeExecDate
          ,e.B_MonthlyFee
          ,e.B_OemMonthlyFee
          ,e.CreditJudgePendingRequest
          ,e.HideToCbButton
          ,e.LastPasswordChanged
          ,e.OrderRevivalDisabled
          ,e.PayingMail
          ,e.DetailApiOrderStatusClass
          ,e.RegistId
          ,e.UpdateDate
          ,e.UpdateId
          ,399 AS RoleCode  -- 権限
          ,e.EnterpriseNameKj AS UserNameKj -- ユーザー名
    FROM T_Enterprise e
;
