<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">詳細入金処理</h3>
    <?php if ($this->errorCount == 0) { ?>
    <h4>詳細入金処理を完了しました。</h4>
    <?php } else { ?>
    <h4 style="color: red;">
      詳細入金処理に失敗しました。以下の事由が考えられます。
      <ul>
        <li>その他データベーストラブル等</li>
      </ul>各種設定を見直してください
    </h4>
    <?php } ?>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
