<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/rwrcptcfm/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">コンビニ入金CSVインポート</h3>
	<h4><?php echo $this->message; ?></h4>
      <table style="clear:both; font-size: 11px;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
            <th>ホスト処理日</th>
            <th>顧客コード</th>
            <th>支払期限</th>
            <th>支払金額</th>
            <th>請求額</th>
            <th>差額</th>
            <th>収納日付</th>
            <th>エラー</th>
          </tr>
          <?php 
          // count関数対策
            $dataCount = 0;
            if (!empty($this->data)) {
            $dataCount = count($this->data);
            }
            for ($i = 0 ; $i < $dataCount ; $i++) { ?>
          <tr>
            <td class="r_data"><?php echo $this->data[$i][1]; ?></td>
            <td class="r_data"><?php echo $this->data[$i][3]; ?></td>
            <td class="r_data"><?php echo $this->data[$i][4]; ?></td>
            <td class="r_data"><?php echo $this->data[$i][5]; ?></td>
            <td class="r_data"><?php echo $this->data[$i][10]; ?></td>
            <td class="r_data"><?php echo $this->data[$i][11]; ?></td>
            <td class="r_data"><?php echo $this->data[$i][7]; ?></td>
            <td class="l_data"><?php echo $this->data[$i][9]; ?></td>
          </tr>
          <?php } ?>
        </tbody>
      </table>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
