<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<style type="text/css">
<!--
#formdiv {
	margin-left: 25px;
	text-align: center;
}
-->
</style>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/rwrcptcfm/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">みずほファクター結果詳細<?php if (isset($this->filename)) { echo ' (' . f_e($this->filename) . ') '; }; ?></h3>
    <?php echo $this->errormessage; ?>

    <!-- ■サマリーあり時に表示 -->
    <?php if (isset($this->summary)) { ?>
    <p>【サマリー】</p>
    <table style="clear:both; font-size: 11px;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
      <tbody>
        <tr>
          <th>支払方法</th>
          <th>取込件数</th>
          <th>支払金額総計</th>
          <th>請求金額総計</th>
          <th>差額総計</th>
        </tr>
        <?php if (isset($this->summary)) { ?>
        <?php foreach ($this->summary as $key => $classSummary) { ?>
        <tr>
          <td class="l_data" width="200px;"><?php echo 'コンビニ払い'; ?></td>
          <td class="r_data" width="120px;"><?php echo f_nf($classSummary['recordCount'], '#,##0'); ?></td>
          <td class="r_data" width="180px;"><?php echo f_nf($classSummary['paymentAmount'], '#,##0'); ?></td>
          <td class="r_data" width="180px;"><?php echo f_nf($classSummary['claimAmount'], '#,##0'); ?></td>
          <td class="r_data"><?php echo f_nf($classSummary['sagakuAmount'], '#,##0'); ?></td>
        </tr>
        <?php } ?>
        <?php } ?>
      </tbody>
    </table>
    <br/>
    <?php } ?>

    <!-- ■入金エラーデータあり時に表示 -->
    <?php if (isset($this->edata)) { ?>
    <p>【入金エラーデータ】</p>
    <table style="clear:both; font-size: 11px;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
      <tbody>
        <tr>
          <th>支払方法</th>
          <th>注文ID</th>
          <th>収納金額</th>
          <th>エラー理由</th>
        </tr>
        <?php if (isset($this->edata)) { ?>
        <?php foreach ($this->edata as $row) { ?>
        <tr>
          <?php $key = $row['syunoKbnCode'] ?>
          <td class="l_data" width="200px;"><?php echo 'コンビニ払い'; ?></td>
          <td class="l_data" width="120px;"><a target="_blank" href="rworder/detail/oseq/<?php echo f_e($row['orderSeq']); ?>"><?php echo f_e($row['orderId']); ?></a></td>
          <td class="r_data" width="120px;"><?php echo f_nf($row['paymentAmount'], '#,##0'); ?></td>
          <td class="l_data"><?php echo f_e( $row['note']); ?></td>
        </tr>
        <?php } ?>
        <?php } ?>
      </tbody>
    </table>
    <br/>
    <?php } ?>

    <!-- ■取消データあり時に表示 -->
    <?php if (isset($this->cdata)) { ?>
    <p>【取消データ】</p>
    <table style="clear:both; font-size: 11px;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
      <tbody>
        <tr>
          <th>支払方法</th>
          <th>注文ID</th>
          <th>収納金額</th>
          <th>備考</th>
        </tr>
        <?php if (isset($this->cdata)) { ?>
        <?php foreach ($this->cdata as $row) { ?>
        <tr>
          <?php $key = $row['syunoKbnCode'] ?>
          <td class="l_data" width="200px;"><?php echo 'コンビニ払い'; ?></td>
          <td class="l_data" width="120px;"><a target="_blank" href="rworder/detail/oseq/<?php echo f_e($row['orderSeq']); ?>"><?php echo f_e($row['orderId']); ?></a></td>
          <td class="r_data" width="120px;"><?php echo f_nf($row['paymentAmount'], '#,##0'); ?></td>
          <td class="l_data"><?php echo f_e( $row['note']); ?></td>
        </tr>
        <?php } ?>
        <?php } ?>
      </tbody>
    </table>
    <br/>
    <?php } ?>

    <!-- ■その他(入金処理対象外データ)あり時に表示 -->
    <?php if (isset($this->adata)) { ?>
    <p>【その他(入金処理対象外データ)】</p>
    <table style="clear:both; font-size: 11px;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
      <tbody>
        <tr>
          <th>支払方法</th>
          <th>取込件数</th>
          <th>金額総計</th>
        </tr>
        <?php if (isset($this->adata)) { ?>
        <?php foreach ($this->adata as $row) { ?>
        <tr>
          <?php $key = $row['syunoKbnCode'] ?>
          <td class="l_data" width="200px;">(確報)<?php echo 'コンビニ払い'; ?></td>
          <td class="r_data" width="120px;"><?php echo f_nf($row['recordCount'], '#,##0'); ?></td>
          <td class="r_data"><?php echo f_nf($row['paymentAmount'], '#,##0'); ?></td>
        </tr>
        <?php } ?>
        <?php } ?>
      </tbody>
    </table>
    <br/>
    <?php } ?>

  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
