<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
$colInfo = $this->colInfo;
?>
<style type="text/css">
.datatable thead th {
  line-height: 1.4;
  padding-top: 3px;
  padding-bottom: 3px;
}
.datatable td.error_col {
  font-weight: bold;
  color: crimson;
  background-color: mistyrose;
}
.nav-left {
  float: left;
  display: inline-block;
}
.nav-right {
  float: right;
  display: inline-block;
}
.clear-float {
  float: none;
  clear: both;
  font-size: 0;
  display: block;
  line-height: 0;
  height: 0;
}
</style>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/jnbgrp/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">
      CSVエラー一覧
      (<?php echo sprintf('%s 件中', f_nf($this->totalCount, '#,##0')); ?>
      <?php echo f_nf($this->ipp * ($this->page - 1) + 1, '#,##0'); ?>
      ～
      <?php
      // count関数対策
        $listCount = 0;
        if (!empty($this->list)){
          $listCount = count($this->list);
        }
        echo f_nf($this->ipp * ($this->page - 1) + $listCount, '#,##0'); ?>
      件目を表示)
    </h3>
    <table class="datatable" cellpadding="1" cellspacing="1" width="862">
      <thead>
        <tr>
          <th>行</th>
          <th>エラー内容</th>
          <th>店番号</th>
          <th>口座番号</th>
          <th>ワンタイム口座名</th>
          <th>ワンタイム管理番号</th>
          <th>管理番号名</th>
          <th>採番日</th>
          <th>適用日</th>
          <th>更新日</th>
          <th>ステータス</th>
          <th>有効期限</th>
          <th>最新入金日</th>
          <th>入金開放日</th>
        </tr>
      </thead>
      <tbody>
    <?php foreach($this->list as $data) { ?>
        <?php $errInfo = explode(',', $data['CsvError']); $lineNum = array_shift($errInfo); $errMsg = join(',', $errInfo); ?>
        <tr>
          <td class="r_data"><?php echo f_e($lineNum); ?></td>
          <td class="l_data"><?php echo f_e(preg_match('/カラム/', $errMsg) ? $errMsg : '形式エラー：' . $errMsg); ?></td>
        <?php foreach($colInfo as $col => $info) { ?>
          <td class="l_data<?php if(!preg_match($info['match'], $data[$col])) echo ' error_col'; ?>"><?php echo f_e($data[$col]); ?></td>
        <?php } ?>
        </tr>
    <?php } ?>
      </tbody>
    </table>
    <div class="submit-area">
      <a href="jnbgrp/continue/oid/<?php echo f_e($this->oid); ?>/tid/<?php echo f_e($this->tranId); ?>">　インポート確認画面へ戻る　</a>
      <a href="jnbgrp/csverrclear/oid/<?php echo f_e($this->oid); ?>/tid/<?php echo f_e($this->tranId); ?>">　エラー情報をクリア　</a>
      <div class="nav-left">
      <?php if($this->page > 1) { ?>
        <a href="jnbgrp/csverr/oid/<?php echo f_e($this->oid); ?>/tid/<?php echo f_e($this->tranId); ?>/page/<?php echo f_e($this->page - 1); ?>">&laquo; 前のページ</a>
      <?php } else { ?>
        <span>&laquo; 前のページ</span>
      <?php } ?>
      </div>
      <div class="nav-right">
      <?php if($this->page < $this->maxPage) { ?>
        <a href="jnbgrp/csverr/oid/<?php echo f_e($this->oid); ?>/tid/<?php echo f_e($this->tranId); ?>/page/<?php echo f_e($this->page + 1); ?>">次のページ &raquo;</a>
      <?php } else { ?>
        <span>次のページ &raquo;</span>
      <?php } ?>
      </div>
      <div class="clear-float">&nbsp; </div>
    </div>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>

</div>
<!-- end wrapper -->
</body>
</html>
