<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
if( ! isset($this->error) || ! is_array($this->error) ) $this->error = array();

function show_error_message($messages) {
    if( empty($messages) ) return;
    if( ! is_array($messages) ) $messages = array($messages);
    $list = array();
    foreach($messages as $msg) $list[] = f_e($msg);
    echo '<div class="input_error_message">';
    echo join('<br />', $list);
    echo '</div>';
}
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/jnb/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">JNB<?php echo $this->mode == 'add' ? '新規登録' : '登録内容編集'; ?></h3>
    <form id="jnb-form" class="main-form" action="jnb/confirm" method="post">
      <table class="formtable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
            <td class="r_label">OEM先</td>
            <td class="l_data">
            <?php if($this->mode == 'add') { ?>
              <select name="form[OemId]" value="<?php echo f_e($this->oid); ?>">
                <option value="-1">(選択してください)</option>
              <?php foreach($this->oemList as $oemInfo) { ?>
                <option value="<?php echo f_e($oemInfo['OemId']); ?>"<?php if($oemInfo['OemId'] == $this->oid) echo ' selected="selected"'; ?>>
                  <?php echo f_e(sprintf('%d：%s', $oemInfo['OemId'], $oemInfo['OemNameKj'])); ?>
                </option>
              <?php } ?>
              </select>
              <?php show_error_message($this->error['OemId']); ?>
            <?php } else { ?>
              <?php echo f_e(sprintf('%d：%s', $this->data['OemId'], $this->data['OemNameKj'])); ?>
              <input name="form[OemId]" type="hidden" value="<?php echo f_e($this->data['OemId']); ?>" />
              <input name="form[OemNameKj]" type="hidden" value="<?php echo f_e($this->data['OemNameKj']); ?>" />
            <?php } ?>
            </td>
          </tr>

        <?php if($this->mode == 'edit') { ?>
          <tr>
            <td class="r_label">登録日時</td>
            <td class="l_data">
              <?php echo f_df($this->data['RegistDate'], 'Y年n月j日 H時i分'); ?>
              <input name="form[RegistDate]" type="hidden" value="<?php echo f_e($this->data['RegistDate']); ?>" />
            </td>
          </tr>
        <?php } ?>

          <tr>
            <td class="r_label">名称</td>
            <td class="l_data">
              <input name="form[DisplayName]" type="text" size="60" value="<?php echo f_e($this->data['DisplayName']); ?>" />
              <?php show_error_message($this->error['DisplayName']); ?>
            </td>
          </tr>

          <tr>
            <td class="r_label">銀行名</td>
            <td class="l_data">
              <input name="form[BankName]" type="text" size="40" value="<?php echo f_e($this->data['BankName']); ?>" />
              <?php show_error_message($this->error['BankName']); ?>
            </td>
          </tr>

          <tr>
            <td class="r_label">銀行コード</td>
            <td class="l_data">
              <input name="form[BankCode]" type="text" size="5" value="<?php echo f_e($this->data['BankCode']); ?>" />
              <?php show_error_message($this->error['BankCode']); ?>
            </td>
          </tr>

          <tr>
            <td class="r_label">メモ</td>
            <td class="l_data">
              <textarea name="form[Memo]" style="width: 400px; height: 120px"><?php echo f_e($this->data['Memo']); ?></textarea>
              <?php show_error_message($this->error['Memo']); ?>
            </td>
          </tr>
      </table>

      <div class="submit-area">
        <input name="mode" type="hidden" value="<?php echo f_e($this->mode); ?>" />
        <input name="form[ValidFlg]" type="hidden" value="<?php echo f_e($this->data['ValidFlg']); ?>" />
        <button type="submit">確認</button>
      <?php if($this->mode == 'edit') { ?>
        <a class="action" href="jnb/detail/oid/<?php echo f_e($this->data['OemId']); ?>">　JNB登録内容詳細へ戻る　</a>
      <?php } ?>
      </div>
    </form>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>

</div>
<!-- end wrapper -->
</body>
</html>
