DROP procedure IF EXISTS `procMigrateOemEnterpriseClaimed`;

DELIMITER $$
CREATE PROCEDURE `procMigrateOemEnterpriseClaimed` ()
BEGIN

    /* 移行処理：OEM加盟店請求 */

    DECLARE
        updDttm    datetime;            -- 更新日時

    SET updDttm = now();

    INSERT INTO `T_OemEnterpriseClaimed`
        (`OemEnterpriseClaimedSeq`,
        `OemId`,
        `EnterpriseId`,
        `FixedMonth`,
        `ProcessDate`,
        `SpanFrom`,
        `SpanTo`,
        `OrderCount`,
        `UseAmount`,
        `CB_MonthlyFee`,
        `AppPlan`,
        `SettlementFeeRate`,
        `OemSettlementFeeRate`,
        `CB_SettlementCount`,
        `CB_SettlementFee`,
        `CB_ClaimCountBS`,
        `CB_ClaimFeeBS`,
        `CB_ClaimCountDK`,
        `CB_ClaimFeeDK`,
        `CB_EntMonthlyFee`,
        `CB_AdjustmentAmount`,
        `CB_ClaimTotal`,
        `OM_SettlementCount`,
        `OM_SettlementFee`,
        `OM_ClaimCountBS`,
        `OM_ClaimFeeBS`,
        `OM_ClaimCountDK`,
        `OM_ClaimFeeDK`,
        `OM_EntMonthlyFee`,
        `OM_AdjustmentAmount`,
        `OM_TotalProfit`,
        `CR_TotalAmount`,
        `CR_OemAmount`,
        `CR_EntAmount`,
        `PayingMethod`,
        `PC_CarryOver`,
        `PC_ChargeCount`,
        `PC_ChargeAmount`,
        `PC_SettlementFee`,
        `PC_ClaimFee`,
        `PC_CancelCount`,
        `PC_CalcelAmount`,
        `PC_StampFeeCount`,
        `PC_StampFeeTotal`,
        `PC_MonthlyFee`,
        `PC_TransferCommission`,
        `PC_DecisionPayment`,
        `PC_AdjustmentAmount`,
        `FixedTransferAmount`,
        `OemClaimedSeq`,
        `PayBackCount`,
        `PayBackAmount`,
        `AgencyFee`,
        `RegistDate`,
        `RegistId`,
        `UpdateDate`,
        `UpdateId`,
        `ValidFlg`)
    SELECT
        `T_OemEnterpriseClaimed`.`OemEnterpriseClaimedSeq`,
        `T_OemEnterpriseClaimed`.`OemId`,
        `T_OemEnterpriseClaimed`.`EnterpriseId`,
        `T_OemEnterpriseClaimed`.`FixedMonth`,
        `T_OemEnterpriseClaimed`.`ProcessDate`,
        `T_OemEnterpriseClaimed`.`SpanFrom`,
        `T_OemEnterpriseClaimed`.`SpanTo`,
        `T_OemEnterpriseClaimed`.`OrderCount`,
        `T_OemEnterpriseClaimed`.`UseAmount`,
        `T_OemEnterpriseClaimed`.`CB_MonthlyFee`,
        `T_OemEnterpriseClaimed`.`AppPlan`,
        `T_OemEnterpriseClaimed`.`SettlementFeeRate` / 100000,
        `T_OemEnterpriseClaimed`.`OemSettlementFeeRate` / 100000,
        `T_OemEnterpriseClaimed`.`CB_SettlementCount`,
        `T_OemEnterpriseClaimed`.`CB_SettlementFee`,
        `T_OemEnterpriseClaimed`.`CB_ClaimCountBS`,
        `T_OemEnterpriseClaimed`.`CB_ClaimFeeBS`,
        `T_OemEnterpriseClaimed`.`CB_ClaimCountDK`,
        `T_OemEnterpriseClaimed`.`CB_ClaimFeeDK`,
        `T_OemEnterpriseClaimed`.`CB_EntMonthlyFee`,
        `T_OemEnterpriseClaimed`.`CB_AdjustmentAmount`,
        `T_OemEnterpriseClaimed`.`CB_ClaimTotal`,
        `T_OemEnterpriseClaimed`.`OM_SettlementCount`,
        `T_OemEnterpriseClaimed`.`OM_SettlementFee`,
        `T_OemEnterpriseClaimed`.`OM_ClaimCountBS`,
        `T_OemEnterpriseClaimed`.`OM_ClaimFeeBS`,
        `T_OemEnterpriseClaimed`.`OM_ClaimCountDK`,
        `T_OemEnterpriseClaimed`.`OM_ClaimFeeDK`,
        `T_OemEnterpriseClaimed`.`OM_EntMonthlyFee`,
        `T_OemEnterpriseClaimed`.`OM_AdjustmentAmount`,
        `T_OemEnterpriseClaimed`.`OM_TotalProfit`,
        `T_OemEnterpriseClaimed`.`CR_TotalAmount`,
        `T_OemEnterpriseClaimed`.`CR_OemAmount`,
        `T_OemEnterpriseClaimed`.`CR_EntAmount`,
        `T_OemEnterpriseClaimed`.`PayingMethod`,
        `T_OemEnterpriseClaimed`.`PC_CarryOver`,
        `T_OemEnterpriseClaimed`.`PC_ChargeCount`,
        `T_OemEnterpriseClaimed`.`PC_ChargeAmount`,
        `T_OemEnterpriseClaimed`.`PC_SettlementFee`,
        `T_OemEnterpriseClaimed`.`PC_ClaimFee`,
        `T_OemEnterpriseClaimed`.`PC_CancelCount`,
        `T_OemEnterpriseClaimed`.`PC_CalcelAmount`,
        `T_OemEnterpriseClaimed`.`PC_StampFeeCount`,
        `T_OemEnterpriseClaimed`.`PC_StampFeeTotal`,
        `T_OemEnterpriseClaimed`.`PC_MonthlyFee`,
        `T_OemEnterpriseClaimed`.`PC_TransferCommission`,
        `T_OemEnterpriseClaimed`.`PC_DecisionPayment`,
        `T_OemEnterpriseClaimed`.`PC_AdjustmentAmount`,
        `T_OemEnterpriseClaimed`.`FixedTransferAmount`,
        `T_OemEnterpriseClaimed`.`OemClaimedSeq`,
        0,
        0,
        0,
        updDttm,
        9,
        updDttm,
        9,
        1
    FROM `coraldb_ikou`.`T_OemEnterpriseClaimed`;
END
$$

DELIMITER ;

