<?php
// HTMLヘッダ
echo $this->render( 'oemmember/document_header.php' );

// アプリケーション名割り当て
$this->applicationTitle = '後払い決済管理システム';
?>
<style type="text/css">
.auth-error-info {
    text-align: center;
    margin: 40px auto;
}
</style>
</head>
<body>
<?php
// 共通ページヘッダ
echo $this->render( 'oemmember/page_header.php' );

// システムメッセージ
echo $this->render( 'oemmember/system_message.php' );

?>

<div class="auth-error-info">
<h3>認証エラー</h3>
<p>
    <?php echo f_e($this->errMessage); ?>
    <?php if (isset($this->isAccountLock)) { ?>
        <br>
        <?php
        if (strpos($_SERVER['REQUEST_URI'], '/seino-financial/') === 0) {
            // (セイノーフィナンシャル)
            echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
            echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。<br><br>";
            echo "サポートセンター電話番号： TEL: 03-4326-3610（9:00～18:00）";
        }
        else if (strpos($_SERVER['REQUEST_URI'], '/estore/') === 0) {
            // (Eストアー)
            echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
            echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。<br><br>";
            echo "サポートセンター電話番号： TEL: 0570-05-1210（平日 10:00～18:00）";
        }
        else if (strpos($_SERVER['REQUEST_URI'], '/smbcfs/') === 0) {
            // (SMBC)
            echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
            echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。<br><br>";
            echo "サポートセンター電話番号： TEL: 0120-667-690（10:00 ～ 18:00）";
        }
        else if (strpos($_SERVER['REQUEST_URI'], '/base/') === 0) {
            // (BASE)
            echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
            echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。";
        }
        else if (strpos($_SERVER['REQUEST_URI'], '/temona/') === 0) {
            // (テモナ)
            echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
            echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。";
        }
        else if (strpos($_SERVER['REQUEST_URI'], '/mizuho/') === 0) {
            // (みずほファクター)
            echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
            echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。";
        }
        else {
            // (直営[その他])
            echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
            echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。<br><br>";
            echo "サポートセンター電話番号： TEL: 0120-667-690（10:00 ～ 18:00）";
        }
        ?>
    <?php } ?>
</p>
</div>

<?php
// 共通ページフッタ
echo $this->render( 'oemmember/page_footer.php' );
?>
</body>
</html>

