<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/enterpriseclaim/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">事業者別請求残高一覧</h3>
    <form id="form" name="form">
      <table width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
            <th>加盟店ID</th>
            <th>加盟店名</th>
            <th>請求日付</th>
            <th>請求額</th>
            <th>入金日付</th>
            <th>入金累計額</th>
            <th>請求残高</th>
            <th>明細リンク</th>
          </tr>
          <?php foreach ($this->list as $row) { ?>
          <tr class="data">
            <td class="c_data" width="50" ><?php echo $row['EnterpriseId']; ?></td>
            <td class="l_data" width="300"><?php echo $row['EnterpriseNameKj']; ?></td>
            <td class="c_data" width="70" ><?php echo $row['ClaimDate']; ?></td>
            <td class="r_data" width="63" ><?php echo f_nf($row['ClaimAmountTotal'], '#,##0'); ?></td>
            <td class="r_data" width="70" ><?php echo $row['ReceiptDate']; ?></td>
            <td class="r_data" width="63" ><?php echo f_nf($row['ReceiptAmountTotal'], '#,##0'); ?></td>
            <td class="r_data" width="63" ><?php echo f_nf($row['ClaimedBalance'], '#,##0'); ?></td>
            <td class="c_data">
            <?php /* ① */ ?>
            <?php if ($row['ClaimAmountTotal'] != 0) { ?>
            <?php if ($row['ClaimedBalance'] == 0) { ?>
            <a target="_blank" href="enterpriseclaim/detail/eid/<?php echo $row['EnterpriseId']; ?>">都度請求分の入金</a><br>
            <?php } else { ?>
            <a target="_blank" href="enterpriseclaim/edit/eid/<?php echo $row['EnterpriseId']; ?>">都度請求分の入金</a><br>
            <?php } ?>
            <?php } ?>

            <?php /* ② */ ?>
            <a target="_blank" href="paying/elist/eid/<?php echo $row['EnterpriseId']; ?>">請求詳細</a>
            </td>
          </tr>
          <tr class="border">
            <td colspan="8">
              <img src="../images/spacer_gray.gif" height="1" width="1">
            </td>
          </tr>
        <?php } ?>
        </tbody>
      </table>
    </form>
    </div>
    <!-- end contents -->

    <?php echo $this->render('cbadmin/page_footer.php'); ?>
  </div>
</body>
</html>
