<?php
// HTMLヘッダ
echo $this->render( 'orderpage/document_header_sp.php' );

// アプリケーション名割り当て
$this->applicationTitle = '注文マイページ';
?>
</head>
<body>
<div id="wrapper">
<?php
// 共通ページヘッダ
echo $this->render( 'orderpage/creditsettlement/page_header_sp.php' );

// システムメッセージ
echo $this->render( 'orderpage/system_message_sp.php' );
?>
<!-- start contents -->
<div id="contents">
  <div id="Tcreditsettlement_area">
    <h5 style="line-height:30px;">アプリ決済（エラー情報）</h5>
    <table width="300px">
      <tr>
        <td class="l_area" style="font-size: 14px; font-weight: bold">ご注文番号 : <?php echo f_e($this->orderId); ?></td>
      </tr>
      <tr>
        <td class="l_area" style="font-size: 14px; font-weight: bold">ご請求金額 : <?php echo f_nf($this->claimedBalance, '#,##0'); ?> 円</td>
      </tr>
    </table>
  </div>

  <div id="creditsettlement_area">
      <table width="300px">
        <tr>
           <?php if ($this->errorMessages) { ?>
          <td class="l_area" style = "font-size: 14px; font-weight: normal;">支払い手続きに失敗しました。以下をご確認頂き、必要に応じて購入履歴画面から処理をやり直してください。</td>
          <?php } else { ?>
          <td class="l_area" style = "font-size: 14px; font-weight: normal;">支払い手続きに失敗しました。購入履歴画面から処理をやり直してください。</td>
          <?php } ?>
          <td ></td>
        </tr>
        <tr>
          <td class="l_area" style = "padding-top:10px;">　</td>
          <td ></td>
        </tr>
        <!-- 以下、エラーメッセージ -->
        <?php if ($this->errorMessages) { ?>
        <?php foreach ($this->errorMessages as $message) { ?>
        <tr>
          <td style="color:red ; padding-left:8%" ><?php echo f_e($message); ?></td>
        </tr>
        <?php } ?>
        <?php } ?>
      </table>

      <table width="300px">
        <tr>
          <td align="center">
          	<a id="cancel_button" float="center" target="_blank" href="index/index">購入履歴画面へ</a>
          </td>
        </tr>
      </table>
  </div>
</div>
<!-- end contents -->
<?php
// 共通ページフッタ
echo $this->render( 'orderpage/creditsettlement/page_footer_sp.php' );
?>
</div>
</body>
</html>