<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
<style>
table.datatable th {
  white-space: nowrap;
}

  a.download_link {
    padding: 8px;
    padding-left: 25px;
    background-image: url('../images/icon_download_s.gif');
    background-repeat: no-repeat;
    background-position: 8px center;
    font-size: 12px;
  }
  a.download_link,
  a.download_link:link,
  a.download_link:hover,
  a.download_link:active,
  a.download_link:visited {
    border: solid 1px silver;
    background-color: transparent;
    color: royalblue;
  }
  a.download_link:hover {
    background-color: azure;
    border-color: gray;
    color: blue;
  }

</style>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/searche/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">事業者検索</h3>
    <div style="margin: 5px 25px;">
    <h4>
      該当件数　<?php 
      // count関数対策
      $listCount = 0;
        if (!empty($this->list)){
          $listCount = count($this->list);
      }
      echo ($listCount); ?> 件
    </h4>
    <table style="margin: 0px; clear:both;" width="862" id="search_result" class="datatable" cellpadding="1" cellspacing="1" border="0">
      <div class="page_nav">
        <span class="pager"><a class="download_link" href="searche/download">一覧をCSVダウンロード</a></span>
        <span class="pager"><a class="download_link" href="searche/upload">CSV取込(登録)</a></span>
      </div>
      <tbody>
          <tr>
            <th rowspan="3">事業者ID</th>
            <th>ログインID</th>
            <th>事業者名</th>
            <th>プラン</th>
            <th>締め日</th>
            <th>担当者名</th>
            <th>担当部署</th>
            <th>連絡先</th>
            <th rowspan="3">操作</th>
          </tr>
          <tr>
            <th colspan="7">各種オプション</th>
          </tr>
          <tr>
            <th colspan="7">備考：事業者対応内容</th>
          </tr>
          <?php foreach ($this->list as $row) { ?>
          <tr class="data ent-row oem-<?php echo f_e(nvl($row['OemId'], 0)); ?>">
            <td rowspan="3" class="r_data">
            <?php if ($row['IsLatest1stOrder'] == 1) { ?>
            <font color="red"><b>New</b></font></br>
            <?php echo f_e($row['EnterpriseId']); ?>
            <?php } else { ?>
            <?php echo f_e($row['EnterpriseId']); ?>
            <?php } ?>
            </td>
            <td class="c_data"><?php echo f_e($row['LoginId']); ?></td>
            <td class="l_data"><a href="enterprise/detail/eid/<?php echo f_e($row['EnterpriseId']); ?>"><?php echo f_e($row['EnterpriseNameKj']); ?></a></td>
            <td class="l_data"><?php echo f_e($row['PlanNm']); ?></td>
            <td class="l_data"><?php echo f_e($row['FixPatternNm']); ?></td>
            <td class="l_data"><?php echo f_e($row['CpNameKj']) . '<br />(' . f_e($row['CpNameKn']) . ')'; ?></td>
            <td class="l_data"><?php echo f_e($row['DivisionName']); ?></td>
            <td class="l_data"><?php echo f_e($row['ContactPhoneNumber']); ?></td>
            <td rowspan="3" class="c_data">
              <a href="enterprise/edit/eid/<?php echo f_e($row['EnterpriseId']); ?>">編集</a><br />
              <a href="site/list/eid/<?php echo f_e($row['EnterpriseId']); ?>">Site</a>
            </td>
          </tr>
          <tr class="data ent-row oem-<?php echo f_e(nvl($row['OemId'], 0)); ?>">
            <td colspan="7" class="l_data ent-options">
              <?php
              $opt = $this->optionMap[$row['EnterpriseId']];
              if($opt) {
                $cols = array(
                  sprintf('<span class="ent-option">与信モード：%s</span>', f_e($this->master_map['AutoCreditJudgeMode'][$opt['AutoCreditJudgeMode']])),
                  sprintf('<span class="ent-option">取りまとめ請求：%s</span>', f_e($this->master_map['CombinedClaimMode'][$opt['CombinedClaimMode']]))
                );
                if($opt['UseApi']) $cols[] = '<span class="ent-option">API利用</span>';
                if($opt['UseSelfBilling']) $cols[] = '<span class="ent-option">同梱利用</span>';
                if($opt['CanJournalUpdate']) $cols[] = '<span class="ent-option">伝票番号更新可能</span>';
                if($opt['UseFirstClaimLayout']) $cols[] = '<span class="ent-option">初回封書</span>';
                if($opt['UseAutoJournalInc']) $cols[] = '<span class="ent-option">伝票自動仮登録</span>';
                echo join('/', $cols);
              } else {
                echo '&nbsp;';
              }
            ?>
            </td>
          </tr>
          <tr class="data ent-row oem-<?php echo f_e(nvl($row['OemId'], 0)); ?>">
            <td colspan="7" class="l_data"><?php echo strlen($row['Note']) ? f_e($row['Note']) : '&nbsp;'; ?></td>
          </tr>
          <tr class="border ent-row oem-<?php echo f_e(nvl($row['OemId'], 0)); ?>">
            <td colspan="9">
              <img src="../images/spacer_gray.gif" height="1" width="1">
            </td>
          </tr>
          <?php } ?>
      <tbody>
    </table>
    </div>
  </div>
  <!-- end contents -->

  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
<script>
// 結果テーブルをスクロール可能にする
// new base.UI.TableEx(document.getElementById("search_result"), { height : 500 } );
</script>
</html>
