<?php
require_once 'Zend/Json.php';
require_once 'Zend/Locale.php';

// HTMLヘッダ
echo $this->render( 'document_header.php' );

// アプリケーション名割り当て
$this->applicationTitle = '後払い決済管理システム';

$hide_default = Application::getInstance()->appGlobalConfig->hide_unregisterable_orders;

?>
</head>
<body>
<?php
// 共通ページヘッダ
echo $this->render( 'page_header.php' );
// ヘッダのメニュー
echo $this->render( 'header_menu.php' );

// システムメッセージ
echo $this->render( 'system_message.php' );

// ページタイトル
echo $this->render( 'page_title.php' );

?>

<div class="main_contents">
	<div class="command_bar">
		<div class="title">日付の指定が不正です</div>
	</div>
	<p style="width: 80%; margin: 20px auto">
		<a href="shippingsp/index">配送伝票更新ページへ戻る</a>
	</p>
</div>

<?php
// フッタメニュー
echo $this->render( 'footer_menu.php' );

// 共通ページフッタ
echo $this->render( 'page_footer.php' );
?>
</body>
</html>
