<?php
$errors = Zend_Controller_Front::getInstance()->getResponse()->getException();

// HTMLヘッダ
echo $this->render('document_header.php');
?>
<style>
    #errormess {
        margin: 20px;
    }
    h3 {
        margin-left: 25px;
    }
    h4 {
        margin: 0;
        font-weight: bold;
    }
    #preid{
        height: 400px;
        margin: 10px 25px 20px;
        padding: 10px 20px;
        overflow: auto;
        border: 2px gray solid;
        border-radius: 3px;
    }
    .default_btn {
        border: 1px gray solid;
        border-radius: 3px;
        padding: 2px 10px;
        background-color: whitesmoke;
        color: #333;
    }
</style>
</head>
<body>
<div id="contents">
  <?php echo $this->render('page_header.php'); ?>
    <div class="title"><span>システムエラー</span></div>
    <div id="errormess">エラーが発生しました。　後ほどもう一度お試しください。</div>
    <h3>詳細</h3>
    <pre id="preid">
    <?php foreach($errors as $error) { ?>
    <h4><?php echo f_e($error->getMessage()); ?></h4>
    <div><?php echo f_e($error->getTraceAsString()); ?></div>
    <hr />
    <?php } ?>
    </pre>
    <div style="text-align: center;">
    <a class="default_btn" href="." onClick="javascript:history.back();">戻　る</a>
    </div>
  <?php echo $this->render('page_footer.php'); ?>
</div>
</body>
</html>
