CREATE TABLE `T_MypageCustomer` (
  `CustomerId` bigint(20) NOT NULL AUTO_INCREMENT,
  `OemId` bigint(20) DEFAULT NULL,
  `ManCustId` bigint(20) DEFAULT NULL,
  `MailAddress` varchar(255) DEFAULT NULL,
  `LoginId` varchar(255) DEFAULT NULL,
  `LoginPasswd` varchar(100) DEFAULT NULL,
  `Hashed` int(11) NOT NULL DEFAULT '1',
  `LastLoginDate` datetime DEFAULT NULL,
  `NameSeiKj` varchar(160) DEFAULT NULL,
  `NameMeiKj` varchar(160) DEFAULT NULL,
  `NameSeiKn` varchar(160) DEFAULT NULL,
  `NameMeiKn` varchar(160) DEFAULT NULL,
  `Sex` tinyint(4) DEFAULT NULL,
  `Birthday` date DEFAULT NULL,
  `PostalCode` varchar(12) DEFAULT NULL,
  `PrefectureCode` int(11) DEFAULT NULL,
  `PrefectureName` varchar(40) DEFAULT NULL,
  `Address` varchar(255) DEFAULT NULL,
  `Building` varchar(255) DEFAULT NULL,
  `UnitingAddress` varchar(4000) DEFAULT NULL,
  `Phone` varchar(50) DEFAULT NULL,
  `MobilePhone` varchar(50) DEFAULT NULL,
  `IdentityDocumentClass` tinyint(4) NOT NULL DEFAULT '0',
  `RegNameKj` varchar(160) DEFAULT NULL,
  `RegUnitingAddress` text,
  `RegPhone` varchar(50) DEFAULT NULL,
  `RegMobilePhone` varchar(50) DEFAULT NULL,
  `MailSubject` varchar(255) DEFAULT NULL,
  `RegistDate` datetime DEFAULT NULL,
  `UpdateDate` datetime DEFAULT NULL,
  `ValidFlg` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`CustomerId`),
  UNIQUE KEY `OemId` (`OemId`,`MailAddress`),
  KEY `idx_01` (`OemId`,`MailAddress`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
