<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/enterpriseoperator/page_menu.php'); ?>

<!-- start contents -->
<div id="contents">
<h3>加盟店オペレーター登録内容確認</h3>
<form id="saveForm" method="post" action="enterpriseoperator/save">
<input name="data[ValidFlg]" type="hidden" id="ValidFlg" value="1" />
<?php if(isset($this->data['EnterpriseOpId'])) { ?><input name="data[EnterpriseOpId]" type="hidden" value="<?php echo $this->data['EnterpriseOpId']; ?>" /><?php } ?>
<table class="datatable" width="860" cellpadding="1" cellspacing="1" border="0">
  <tr>
    <td class="label">ログインID</td>
    <td class="data">
      <?php echo $this->data["LoginId"]; ?>
      <input name="data[LoginId]" type="hidden" value="<?php echo $this->data['LoginId']; ?>" />
      <input name="data[EnterpriseId]" type="hidden" value="<?php echo $this->data['EnterpriseId']; ?>" />
      </td>
  </tr>
  <tr>
    <td class="label">氏名</td>
    <td class="data">
      <?php echo $this->data["NameKj"]; ?>
      <input name="data[NameKj]" type="hidden" value="<?php echo $this->data['NameKj']; ?>" />
    </td>
  </tr>
  <tr>
    <td class="label">氏名カナ</td>
    <td class="data">
      <?php echo $this->data["NameKn"]; ?>
      <input name="data[NameKn]" type="hidden" value="<?php echo $this->data['NameKn']; ?>" />
    </td>
  </tr>
  <tr>
    <td class="label">所属</td>
    <td class="data">
      <?php echo $this->data["Division"]; ?>
      <input name="data[Division]" type="hidden" value="<?php echo $this->data['Division']; ?>" />
    </td>
  </tr>
  <tr>
    <td class="label">権限</td>
    <td class="data">
      <?php echo $this->data["RoleCodeName"]; ?>
      <input name="data[RoleCode]" type="hidden" value="<?php echo $this->data['RoleCode']; ?>" />
    </td>
  </tr>
  <tr>
    <td class="label">有効／無効</td>
    <td class="data">
      <?php echo ($this->data["InvalidFlg"] == 1) ? '無効' : '有効'; ?>
      <input name="data[InvalidFlg]" type="hidden" value="<?php echo $this->data['InvalidFlg']; ?>" />
    </td>
  </tr>
  <tr>
    <td colspan="2" align="center">
      <button type="submit">確　認</button>　　　　　<button type="button" id="goBack">戻　る</button>
    </td>
  </tr>
</table>
</form>
</div>
  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
<script>
Event.observe(window, "load", function() {
  Event.observe($("goBack"), "click", function() {
    <?php if(isset($this->data['EnterpriseOpId'])) { ?>
    $("saveForm").action = "enterpriseoperator/edit/enterpriseopid/<?php echo $this->data['EnterpriseOpId']; ?>";
    <?php } else { ?>
    $("saveForm").action = "enterpriseoperator/form/eid/<?php echo f_e($this->eid); ?>";
    <?php } ?>
    $("saveForm").submit();
  });
});
</script>
</html>
