<?php
// HTMLヘッダ
echo $this->render('oemadmin/document_header.php');
?>

<style>
    table {
        width: 900px;
        border: 1px gray solid;
    }
    table.top {
        background-color: #fff;
        border-radius: 3px;
    }
    .layout_container table.datatable {
        border: 1px lightgray solid;
    }
    table.datatable td.under {
        border-bottom: 3px solid lightgray;
    }
    .l_height {
        line-height: 17px;
    }
    .width_400 {
        width: 400px;
    }
</style>
</head>
<body>
  <!-- start contents -->
  <div id="contents">
  <?php echo $this->render('oemadmin/page_header.php'); ?>
  <?php echo $this->render('oemadmin/claim/page_menu.php'); ?>
    <div class="title"><span>債権明細</span></div>

    <form name="form" method="post" action="claim/index">
      <table class="datatable top">
        <tbody>
          <tr>
            <td class="l_data">
              <?php echo $this->fixedMonthTag; ?>
              <input class="default_btn" type="submit" style="margin-top: 1px;" value="　表　示　" />
            </td>
          </tr>
        </tbody>
      </table>
    </form>

    <div class="layout_container">
      <table class="datatable">
        <tbody>
          <tr>
              <td class="r_label width_400 under">初回請求期限</td>
              <td class="c_data under"><?php echo f_e($this->oem_bad_debit['FcSpanFrom']);?>～<?php echo f_e($this->oem_bad_debit['FcSpanTo']);?></td>
          </tr>
          <tr>
              <td class="r_label width_400 under">対象期間</td>
              <td class="c_data under"><?php echo f_e($this->oem_bad_debit['SpanFrom'])."～".f_e($this->oem_bad_debit['SpanTo']);?></td>
          </tr>
          <tr>
              <td class="r_label">請求件数</td>
              <td class="r_data"><?php echo f_e(is_null($this->oem_bad_debit['ClaimCount'])?0:$this->oem_bad_debit['ClaimCount']);?>　件</td>
          </tr>
          <tr>
              <td class="r_label">請求総額(遅延金含まず)</td>
              <td class="r_data"><?php echo f_nf(nvl(is_null($this->oem_bad_debit['ClaimAmount'])?0:$this->oem_bad_debit['ClaimAmount']),'#,##0');?>　円</td>
          </tr>
          <tr>
              <td class="r_label">入金件数</td>
              <td class="r_data"><?php echo f_e(is_null($this->oem_bad_debit['ReceiptMoneyCount'])?0:$this->oem_bad_debit['ReceiptMoneyCount']);?>　件</td>
          </tr>
          <tr>
              <td class="r_label">入金額(遅延金含まず)</td>
              <td class="r_data"><?php echo f_nf(nvl(is_null($this->oem_bad_debit['ReceiptMoneyAmount'])?0:$this->oem_bad_debit['ReceiptMoneyAmount']),'#,##0');?>　円</td>
          </tr>
          <tr>
              <td class="r_label">債権件数</td>
              <td class="r_data"><?php echo f_e(is_null($this->oem_bad_debit['BadDebtCount'])?0:$this->oem_bad_debit['BadDebtCount']);?>　件</td>
          </tr>
          <tr>
              <td class="r_label">債権総額(遅延金含まず)</td>
              <td class="r_data"><?php echo f_nf(nvl(is_null($this->oem_bad_debit['BadDebtAmount']))?0:$this->oem_bad_debit['BadDebtAmount'],'#,##0');?>　円</td>
          </tr>
        </tbody>
      </table>
    <!-- end contents -->
    <!--
    <div style="font-size: 9pt; margin: 0px 8px; float: none; clear: both; width: 870px">
        ※「印紙代合計」とは、購入者様のコンビニ決済によるお支払金額が税込で\54,000以上の場合に発生する印紙代金の合計金額です。(不必要？)
    </div>
    -->
    <div class="note">
        <ul>
            <li>
                表示金額はすべて税込金額となっております。
            </li>
            <li>
                決済手数料の1円未満の端数は切捨てとなっております。
            </li>
        </ul>
    </div>

  <?php echo $this->render('oemadmin/page_footer.php'); ?>
  </div>
</body>
</html>
