<?php
// HTMLヘッダ
echo $this->render('cbadmin/document_header.php');
?>
</head>
<body>
<div id="wrapper">
  <?php echo $this->render('cbadmin/page_header.php'); ?>
  <?php echo $this->render('cbadmin/cancel/page_menu.php'); ?>

  <!-- start contents -->
  <div id="contents">
    <h3 class="contents_title">SoftBankPaymentServiceCancelApiエラー確認</h3>
    <form name="sform" method="post" action="sbpscancelapierror/list">
        <table style="font-size: 12px;">
          	<tr>
                <td class="l_data">発生日&nbsp;</td>
                <td><input style="text-align: left;" type="text" size="10" name="RegistDateF" id="RegistDateF" value="<?php echo f_e($this->condition['RegistDateF']); ?>">&nbsp;～&nbsp;<input style="text-align: left;" type="text" size="10" name="RegistDateT" id="RegistDateT" value="<?php echo f_e($this->condition['RegistDateT']);?>">&nbsp;</td>
                <td class="l_data">注文ID&nbsp;</td>
                <td><input style="text-align: left;" type="text" size="10" name="OrderId" id="OrderId" value="<?php echo f_e($this->condition['OrderId']); ?>">&nbsp;</td>
                <td class="l_data">事業者ID&nbsp;</td>
                <td><input style="text-align: left;" type="text" size="10" name="LoginId" id="LoginId" value="<?php echo f_e($this->condition['LoginId']); ?>">&nbsp;</td>
          	</tr>
          	<tr>
                <td colspan="6" class="r_data"><input style="margin-left: 50px;" id="search" type="submit" value="　検　索　"></td>
          	</tr>
        </table>
    </form>
    <form name="form" method="post" action="cancel/done">
      <table style="clear:both;" width="862" class="datatable" cellpadding="1" cellspacing="1" border="0">
        <tbody>
          <tr>
          	<th style="width: 100px;">注文SEQ</th>
          	<th style="width: 100px;">注文ID</th>
          	<th style="width: 150px;">連携日時</th>
          	<th style="width: 80px;">エラーコード</th>
          	<th>エラーメッセージ</th>
          </tr>
          <?php
            foreach ($this->list as $key => $value) {
             ?>
          <tr>
            <td class="r_data">
              <input type="hidden" name="OrderSeq<?php echo $idx; ?>" id="OrderSeq<?php echo $idx; ?>" value="<?php echo $value["OrderSeq"]; ?>" />
              <?php echo $value["OrderSeq"]; ?>
            </td>
            <td class="l_data">
              <input type="hidden" name="OrderId<?php echo $idx; ?>" id="OrderId<?php echo $idx; ?>" value="<?php echo $value["OrderId"]; ?>" />
              <a target="_blank" href="rworder/detail/oseq/<?php echo $value["OrderSeq"]; ?>"><?php echo $value["OrderId"]; ?></a>
            </td>
            <td class="l_data"><?php echo $value["ResDate"]; ?></td>
            <td class="l_data"><?php echo $value["ResErrCode"]; ?></td>
            <td class="l_data"><?php echo $value["ErrorMessage"]; ?></td>
          </tr>
          <tr class="border">
            <td colspan="15">
              <img src="../images/spacer_gray.gif" height="1" width="1">
            </td>
          </tr>
          <?php $idx++; } ?>
          <?php if (empty($this->list)) { ?>
          <tr>
            <td class="c_data" colspan="15">
              該当なし
            </td>
          </tr>
          <?php } ?>
        </tbody>
      </table>
    </form>
  </div>
  <!-- end contents -->
  <?php echo $this->render('cbadmin/page_footer.php'); ?>
</div>
</body>
</html>
