<?php
// HTMLヘッダ
echo $this->render( 'oemmypage/document_header.php' );

// アプリケーション名割り当て
$this->applicationTitle = '顧客マイページ';
?>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new
Date();a=s.createElement(o),

m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71083479-1', 'auto');
  ga('send', 'pageview');
</script>
</head>
<body>
<div id="wrapper">
<?php
// 共通ページヘッダ
echo $this->render( 'oemmypage/login/page_header.php' );

// システムメッセージ
echo $this->render( 'oemmypage/system_message.php' );

?>
<!-- start contents -->
<div id="contents">
<div id="login_area">
    <h5>ログイン</h5>
    <h6>■ 会員の方</h6>
    <form name="login_form" method="post" action="login/auth">
    <table width="880px" style="float: left ; margin-left:25px">
        <tr>
            <td class="l_area" width="30%">会員ID<br />（メールアドレス）</td>
            <td class="l_area"><input id="login_id" name="login_id" type="text" size="64" style="height:20px" value="<?php if( $this->login_id ) echo $this->login_id; ?>" /></td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td class="l_area">パスワード</td>
            <td class="l_area"><input id="password" name="password" type="password" size="64" style="height:20px" value="<?php if( $this->password ) echo $this->password; ?>" /></td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2" class="c_area"><input name="autologin" type="checkbox" class="chkrd_info" value="1"<?php if( $this->autologin ) echo ' checked="checked"'; ?> />　次回から自動ログイン</td>
        </tr>
        <?php if( !empty( $this->loginMessages ) ){ ?>
        <?php foreach( array_reverse( $this->loginMessages ) as $message ) { ?>
        <tr>
            <td ></td>
            <td style="color:red"><?php echo $message; ?></td>
        </tr>
        <?php } ?>
        <?php } ?>
        <?php if (isset($this->isAccountLock)) { ?>
        <tr>
            <td colspan="2" align="center"><font color="red">
            <?php
            if (strpos($_SERVER['REQUEST_URI'], '/seino-financial/') === 0) {
                // (セイノーフィナンシャル)
                echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
                echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。<br><br>";
                echo "サポートセンター電話番号： TEL: 03-4326-3610（9:00～18:00）";
            }
            else if (strpos($_SERVER['REQUEST_URI'], '/estore/') === 0) {
                // (Eストアー)
                echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
                echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。<br><br>";
                echo "サポートセンター電話番号： TEL: 0570-05-1210（平日 10:00～18:00）";
            }
            else if (strpos($_SERVER['REQUEST_URI'], '/smbcfs/') === 0) {
                // (SMBC)
                echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
                echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。<br><br>";
                echo "サポートセンター電話番号： TEL: 0120-667-690（10:00 ～ 18:00）";
            }
            else if (strpos($_SERVER['REQUEST_URI'], '/base/') === 0) {
                // (BASE)
                echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
                echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。";
            }
            else {
                // (直営[その他])
                echo "ログイン エラー回数が規定回数を超えました。 セキュリティ保護のため、ログインを制限しています。<br>";
                echo "制限を解除するためには、お手数ですがサポートセンターまでお電話にてお問い合わせください。<br><br>";
                echo "サポートセンター電話番号： TEL: 0120-667-690（10:00 ～ 18:00）";
            }
            ?>
            </font>
            </td>
        </tr>
        <?php } ?>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2" align="center"><input id="goto_button" type="submit" value="ログイン" /></td>
        </tr>
    </table>
    </form>
    <table width="880px" style="float: left ; margin-left:25px">
        <tr>
            <td class="l_area"><a href="login/forgetid" target="_blank"><font id="l_pws">◇ 会員IDを忘れた方　　　　</font></a></td>
        </tr>
        <tr>
            <td class="l_area"><a href="login/reissue" target="_blank"><font id="l_pws">◇ パスワードを忘れた方　　　　</font></a></td>
        </tr>
    </table>
    <h6>■ 会員登録がお済みでない方</h6>
    <table  width="880px" style="float: left ; margin-left:25px">
        <tr>
            <td colspan="2" align="center"><input type="button" id="goto_button" onclick="window.open('regist/preregist')" value="新規会員登録" /></td>
        </tr>
    </table>
</div>
</div>
<!-- end contents -->
<?php
// 共通ページフッタ
echo $this->render( 'oemmypage/page_footer.php' );
?>

</div>
</body>
</html>

