<?php
// HTMLヘッダ
echo $this->render( 'oemmypage/document_header.php' );

// アプリケーション名割り当て
$this->applicationTitle = '顧客マイページ';
?>
<script>
function quitBox( cmd )
{
	if( cmd == 'quit' )
	{
		open( location, '_self' ).close();
	}
	return false;
}
</script>
</head>
<body>
<div id="wrapper">
<?php
// 共通ページヘッダ
echo $this->render( 'oemmypage/page_header.php' );

// システムメッセージ
echo $this->render( 'oemmypage/system_message.php' );

?>
<!-- start contents -->
    <div id="contents">
        <div style="clear: both;" id="my_title">変更完了</div>
        <?php
        echo $this->render( 'oemmypage/menu.php' );
        ?>
        <div id="d_01">退会処理が完了しました。<br />登録中のメールアドレスに退会完了メールを<br />送信致しました。</div>
        <br/>
        <div style="text-align: center;"><input id="green_btn" type="button" value="画面を閉じる" onclick="return quitBox( 'quit' );" /></div>
    </div>
<!-- end contents -->
<?php
// 共通ページフッタ
echo $this->render( 'oemmypage/page_footer.php' );
?>

</div>
</body>
</html>
