<?php
// HTMLヘッダ
echo $this->render('oemadmin/document_header.php');
?>
</head>
<body>
  <!-- start contents -->
  <div id="contents">
  <?php echo $this->render('oemadmin/page_header.php'); ?>
  <?php echo $this->render('oemadmin/site/page_menu.php'); ?>
    <div class="title"><span>「<?php echo f_e($this->EnterpriseNameKj); ?>」　サイト一覧</span></div>
    <form name="form" method="post" action="site/up">
      <table class="datatable">
        <tbody>
          <tr>
            <th rowspan="4">サイトID</th>
            <th>登録日</th>
            <th>サイト名</th>
            <th>サイト名カナ</th>
            <th>メール</th>
            <th rowspan="4">有効</th>
          </tr>
          <tr>
            <th colspan="3">URL</th>
            <th>形態</th>
          </tr>
          <tr>
            <th colspan="3"></th>
            <th>請求取りまとめ</th>
          </tr>
          <tr>
            <th colspan="3"></th>
            <th>全案件補償外</th>
          </tr>
          <?php $i = 0; foreach ($this->list as $row) { ?>
          <tr class="data">
            <td rowspan="4" class="r_data">
              <?php echo f_e($row['SiteId']); ?>
            </td>
            <td class="c_data">
              <?php echo f_e($row['RegistDate']); ?>
            </td>
            <td class="l_data">
              <?php echo f_e($row['SiteNameKj']); ?>
            </td>
            <td class="l_data">
              <?php echo f_e($row['SiteNameKn']); ?>
            </td>
            <td class="c_data">
              <?php if($row['ReqMailAddrFlg'] == 1) { echo '必須'; } else { echo '-'; } ?>
            </td>
            <td rowspan="4" class="c_data">
              <?php if($row['ValidFlg'] == 1) { echo '有効'; } else { echo '無効'; } ?>
            </td>
          </tr>
          <tr class="data">
            <td colspan="3" class="l_data">
              <?php echo f_e($row['Url']); ?>
            </td>
            <td class="c_data">
              <?php $keitai = $this->codeMaster->getSiteFormMaster(); ?>
              <?php echo $keitai[$row['SiteForm']]; ?>
            </td>
          </tr>
          <tr class="data">
            <td colspan="3" class="l_data">
            </td>
            <td class="c_data">
              <?php if($row['CombinedClaimFlg'] == 1) { echo '請求取りまとめを行う'; } else { echo '-'; } ?>
            </td>
          </tr>
          <tr class="data">
            <td colspan="3" class="l_data">
            </td>
            <td class="c_data">
              <?php if($row['OutOfAmendsFlg'] == 1) { echo '全補償外案件'; } else { echo '-'; } ?>
            </td>
          </tr>
          <tr class="border">
            <td colspan="6">
              <img src="../../images/spacer_gray.gif" height="1" width="1">
            </td>
          </tr>
          <?php $i++; } ?>
        </tbody>
      </table>
      <div class="btncontents">
              <a class="default_btn" href="enterprise/detail/eid/<?php echo f_e($this->eid); ?>">事業者詳細情報を表示</a>
              <a class="default_btn " href="enterprise/list">事業者一覧を表示</a>
      </div>
    </form>
  <!-- end contents -->

  <?php echo $this->render('oemadmin/page_footer.php'); ?>
</div>
</body>
</html>
